### ISSUE TITLE
Refactor some methods to use C# await within catch blocks

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#100]
We use some tricks in try-catch blocks to call `Async` methods. In C#5 we couldn't await in catch block. Now with C#6 it's possible. It should be changed.

**Comment by molinch** [comment]
There are much more places than just here :)

**Comment by daniel-luberda** [comment]
Ok :P I searched for "trap" word. Didn't know there's more. Will try to find it :)

**Comment by daniel-luberda** [comment]
Ok got it. Indeed, there's a lot more of it.

**Comment by daniel-luberda** [comment]
We could close it, as it's not an issue and not so urgent really.
