### ISSUE TITLE
I want re-download only one image. How I can do it?

### ISSUE THREAD

**Issue by chapayGhub** [molinch/FFImageLoading#101]

**Comment by chapayGhub** [comment]
Now I use next approach
'''c#
	MD5Helper md5 = new MD5Helper();
	string filename = md5.MD5(parameters.Path);
	ImageService.Invalidate(filename, CacheType.All);
'''
Maybe exist another way?

**Comment by molinch** [comment]
@chapayGhub yes that's the way to do it currently.
@daniel-luberda We should change it so the MD5 computation is done by the method.

**Comment by molinch** [comment]
It will be easier with the stuff from this commit.
Btw there was a bug too that prevented to remove from DiskCache (it's fixed in git now)

**Comment by daniel-luberda** [comment]
@molinch @chapayGhub I don't understand what this is about. (the first mesage is empty). Is it fixed now?

**Comment by chapayGhub** [comment]
@molinch  Thanks!
