### ISSUE TITLE
Wrong Bitmap returned from pool

### ISSUE THREAD

**Issue by molinch** [molinch/FFImageLoading#102]
From Luca.7923 posted on Xamarin Forums: http://forums.xamarin.com/discussion/comment/171904#Comment_171904

Crashlog:
[log (1).txt](https://github.com/molinch/FFImageLoading/files/68914/log.1.txt)

**Comment by molinch** [comment]
Luca could you upload a sample or some code?

**Comment by molinch** [comment]
This is the method that determines if Bitmap is reusable: https://github.com/molinch/FFImageLoading/blob/88cd3596a1df7733f81559fa2d7cd8c6b3426706/source/FFImageLoading.Droid/Cache/ReuseBitmapDrawableCache.cs#L156

**Comment by daniel-luberda** [comment]
I see two problems here: 

1.
```C#
return byteCount <= item.AllocationByteCount;
```
should be:
```C#
return byteCount < item.AllocationByteCount;
```
2. We should also pass new bitmap desired bytes per pixel as it can vary and the algorithm doesn't include that but assumes it'll be the same as bitmap which is tested if it can be used for reuse.

**Comment by molinch** [comment]
Hi Daniel

First point I don't understand why it should be strictly lower.

Second, yes we should use target image config (and not source like now)

**Comment by daniel-luberda** [comment]
First point it's just interpretation of comment: 
```C#
// From Android 4.4 (KitKat) onward we can re-use if the byte size of the new bitmap
// is smaller than the reusable bitmap candidate allocation byte count.
```
It states *smaller* not *equal or smaller*

**Comment by molinch** [comment]
Ok. I will check Android doc but I'm pretty sure it is correct.

It would be nice to have a sample with hips of images of different size and format argb888 vs rgb555.
Then we can easily validate if bitmap pool behaves as expected.

**Comment by daniel-luberda** [comment]
I could do this. I could use a Grid like images List. for that I would need to add this nuget: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/FlowListView

We could test loading many images at a time (grid)

What do you think?

**Comment by molinch** [comment]
Very good idea!

**Comment by daniel-luberda** [comment]
I have something. Will commit soon :)

**Comment by daniel-luberda** [comment]
### Error1:

[BitmapFactory] bitmap marked for reuse (136320 bytes) can't fit new bitmap (136960 bytes)

### Error2:

Generating/retrieving image: https://farm5.staticflickr.com/4141/4796759387_ebeec9a22e_z_d.jpg;GrayscaleTransformation;294x0
Generating/retrieving image: https://farm5.staticflickr.com/4141/4796759387_ebeec9a22e_z_d.jpg;GrayscaleTransformation;294x0
[SelfDisposingBitmapDrawable] OnFreeResources
[ReuseBitmapDrawableCache] OnEntryAdded(key = https://farm5.staticflickr.com/4141/4796759387_ebeec9a22e_z_d.jpg;294x0)
[SelfDisposingBitmapDrawable] OnFreeResources
[SelfDisposingBitmapDrawable] OnFreeResources
[ReuseBitmapDrawableCache] OnEntryAdded(key = https://farm5.staticflickr.com/4141/4796759387_ebeec9a22e_z_d.jpg;GrayscaleTransformation;294x0)
Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue[] parms) [0x00084] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/812ca135/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:896 
  at Android.Graphics.Drawables.BitmapDrawable.Draw (Android.Graphics.Canvas canvas) [0x00070] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/812ca135/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Graphics.Drawables.BitmapDrawable.cs:529 
  at FFImageLoading.Drawables.FFBitmapDrawable.Draw (Android.Graphics.Canvas canvas) [0x0007e] in /Users/daniel/Projects/PublicGithub/FFImageLoading/source/FFImageLoading.Droid/Drawables/FFBitmapDrawable.cs:51 
  --- End of managed exception stack trace ---
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@39460871
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:599)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:538)
	at ffimageloading.drawables.FFBitmapDrawable.n_draw(Native Method)
	at ffimageloading.drawables.FFBitmapDrawable.draw(FFBitmapDrawable.java:87)
	at android.widget.ImageView.onDraw(ImageView.java:1176)
	at android.view.View.draw(View.java:15231)

**Comment by daniel-luberda** [comment]
![ios simulator screen shot 22 gru 2015 03 05 48](https://cloud.githubusercontent.com/assets/13569983/11946254/0de87f7e-a859-11e5-98a4-130de51f0ef5.png)
![nexus 4 lollipop screenshot 13](https://cloud.githubusercontent.com/assets/13569983/11946304/69086310-a859-11e5-84c5-14dee2a410ab.png)

**Comment by lbulegato** [comment]
Hi thanks for your effort,
now I am quite busy with a severe deadline.
I hope I can upload the code you asked to me as soon as possible.
Thanks again. 
Luca

**Comment by molinch** [comment]
That issue was definitely coming from wrong Bitmap.Config, as @daniel-luberda suggested. We have in crashlog:
<pre>[BitmapFactory] bitmap marked for reuse (64800 bytes) can't fit new bitmap (129600 bytes)</pre>
It confirms it.

This now fixed in git.

**Comment by daniel-luberda** [comment]
Please try 2.0.1-alpha1

**Comment by daniel-luberda** [comment]
Please try 2.0.1-alpha1
