### ISSUE TITLE
Load the cache from bytearray, map it to URL

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [molinch/FFImageLoading#1035]
### Description
This is not an issue.

I am writing Photo Bytes to Azure Storage from the Xamarin.Forms mobile app.
The Azure is returning the blobURL for the blob. Is there a way I can map the byte array to the blobURL from the azure, cache it for using in CachedImage?

This way I don't have to call the 
ImageService.Instance.LoadUrl(blobURL).Preload();

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform:

**Comment by pravinpatil83** [comment]
Hi, Can you please provide the solution you found?

**Comment by sawankumarbundelkhandi** [comment]
```
public async Task CacheBytesWithURL(string url, byte[] photoBytes)
{
 await ImageService.Instance.Config.DiskCache.AddToSavingQueueIfNotExistsAsync(MD5(url), photoBytes, TimeSpan.FromDays(30));
}

private static string MD5(string input)
{
 using (var hashProvider = new MD5CryptoServiceProvider())
 {
  var bytes = hashProvider.ComputeHash(Encoding.UTF8.GetBytes(input));
  return BitConverter.ToString(bytes).ToSanitizedKey();
  }
}
```
