### ISSUE TITLE
Cannot redisplay this drawable, its resources have been disposed.

### ISSUE THREAD

**Issue by molinch** [molinch/FFImageLoading#105]
From time to time this issue arises, it's coming from `SelfDisposingBitmapDrawable.SetIsDisplayed()`
IMO it's easy to fix. We should make additional checks when getting the image from cache.

**Comment by molinch** [comment]
Should be fixed by 0708dbfc6106df44356b81d8dc18ec45955019b5

**Comment by molinch** [comment]
@daniel-luberda Could you play with the heavy list and tell me if you still get it?
I cannot reproduce it anymore.

**Comment by daniel-luberda** [comment]
@molinch Couldn't reproduce it either.

**Comment by molinch** [comment]
Ok let's close it for now then
