### ISSUE TITLE
Xamarin.Forms component that wraps FFImageLoading

### ISSUE THREAD

**Issue by molinch** [molinch/FFImageLoading#11]
It could be nice to have a Xamarin.Forms component that wraps FFImageLoading using a custom renderer.
I would be very happy to merge that if somebody wants to work it out!

**Comment by dhaligas** [comment]
I might be interested.  we are running into a lot of OOM issues with the xamarin.forms image renderer.  

how is you library on handling bitmaps and downsampling?

**Comment by molinch** [comment]
There is a sample you can try it. The lib works very efficiently on Android, offers downsampling of course but also a couple of other options.
I have not faced any issue on iOS even tough downsampling there isn't yet implemented.

**Comment by daniel-luberda** [comment]
I created CachedImage - Image compatible renderer for Xamarin.Forms. Here: https://gist.github.com/daniel-luberda/f2381b736eb62afd238a

**Comment by molinch** [comment]
Hi @daniel-luberda that's very cool!! :+1: 
Would you mind making a PR for it?

It can be in a folder like FFImageLoading.Forms and ideally have another namespace name.
If that's fine for you I'm happy to merge it and make a Nuget for it!

**Comment by daniel-luberda** [comment]
Thanks! Of course but I need to:
 - add more options (transparency setting etc)
 - test and debug iOS renderer (I have it but currently don't have access to Xamarin.iOS for about two weeks). I can bypass this by making only Android renderer for now and add a render for iOS which is just normal XF.Image inside (FFImageLoading disabled). Is it ok for a temporal solution?

**Comment by molinch** [comment]
Don't worry if you make a PR which has the iOS renderer I can test it and update it (if needed) before merge :)

**Comment by daniel-luberda** [comment]
Ok :) I'll make a PR then.

**Comment by daniel-luberda** [comment]
Added PR https://github.com/molinch/FFImageLoading/pull/32

**Comment by molinch** [comment]
We have now a NuGet package that wraps FFImageLoading thanks to @daniel-luberda 
https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/
