### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by kalarepa** [molinch/FFImageLoading#110]
Couple of days ago I deployed an update to my app that contains this very library. My userbase consists of roughly 1000 people - it's not huge, but significant.
Everything (that's related to this library) seems to work great, except for one thing. Sometimes, usually on phones with 512 MB of RAM, System.OutOfMemoryException is thrown.
It originates from `FFImageLoading.Extensions.ImageExtensions.ToBitmapImageAsync()`, specifically from `WriteableBitmap`'s contructor.
I use downsampling wherever I can, but apparently it's not enough.

So, essentially I can see two issues here:
- exception from library is not caught and causes app to crash. This is easy to fix.
- library uses all of phone's memory. Can I set in-memory cache's maximum size, or something like that?

Crashing is not that common, but nonetheless I'd like it to stop.
I almost forgot - it runs under Windows Phone 8.1. Windows 10 version is much less popular, so I don't have similiar data.

**Comment by molinch** [comment]
Thanks for the detailed feedback.
So all crashes are on Windows platform only?

**Comment by kalarepa** [comment]
Yes, but my app is Windows-only.

**Comment by molinch** [comment]
I see many issues in ImageCache on Windows: https://github.com/molinch/FFImageLoading/blob/82c9bf40cc9ee9a6818a18e5bfc40b4a38712d90/source/FFImageLoading.Windows/Cache/ImageCache.cs

Since it is not LRU based & does not use maxCacheSize parameter, stuff goes in but never out.

**Comment by ravensorb** [comment]
Wouldn't implementing IDisposable help address remove the objects correctly?

**Comment by molinch** [comment]
For the LRU cache we can simply link & reuse the one from Android:
https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Droid/Collections/ByteBoundStrongLruCache.cs

We can instanciate it in a similar way: https://github.com/molinch/FFImageLoading/blob/e81687c03edab837ca82d422d03c7a25278903d7/source/FFImageLoading.Droid/Cache/ImageCache.cs#L23

**Comment by daniel-luberda** [comment]
@molinch It's not based on LRU, but it's not needed because of using WeakReferences. It doesn't hold any bitmap instances, so it they're recycled with garbage collector - it is automatically evicted.

**Comment by daniel-luberda** [comment]
I don't think it's the FFImageLoading problem itself, but we will have to check it anyway. I'm worried about this part: 

							try
							{
								generatingImageSucceeded = await TryGeneratingImageAsync().ConfigureAwait(false);
							}
							catch (OutOfMemoryException oom)
							{
								Logger.Error("Received an OutOfMemory we will clear the cache", oom);
								ImageCache.Instance.Clear();
								ex = oom;
							}

We shouldn't actually clear the cache because it's based on WeakReferences anyway.

**Comment by daniel-luberda** [comment]
@kalarepa Setting maximum cache size on Windows doesn't have any practical usage. While Windows is using some bitmap in any control - it's cache. If Windows will free its resources (no control is using bitmap anymore) - it's automatically evicted.

**Comment by molinch** [comment]
@daniel-luberda this part is definitely useful on iOS/Android: if there is an OOM we need memory reclaimed ASAP, so it cleares the cache and triggers a GC (inside Clear method).
On Windows you are right, bitmaps are managed and not native. Therefore I really don't think that this issue comes from that part, when this code is hit it's already bad: you got an OOM.

As said by @kalarepa the issue originates from `FFImageLoading.Extensions.ImageExtensions.ToBitmapImageAsync()`, specifically from `WriteableBitmap`'s contructor. 
This means that performing transformations is too memory intensive.

**Comment by daniel-luberda** [comment]
> @daniel-luberda this part is definitely useful on iOS/Android: if there is an OOM we need memory reclaimed ASAP, so it cleares the cache and triggers a GC (inside Clear method).
On Windows you are right, bitmaps are managed and not native. Therefore I really don't think that this issue comes from that part, when this code is hit it's already bad: you got an OOM.

Yes, I was referring to Windows only, but the file which executes cache clearing is shared with all platforms - we should modify it to disable cache clearing for Windows.

Things to check:
- We should also check if  BitmapHolder (pixel `int[] array`) is disposed correctly but 
- Expensive transformations / downsampling (large files)
- Disable cache clearing when out of memory for Windows

But I think that it also could not be a FFImageLoading bug - it's just device capacity limit when handling many pictures / large pictures.

**Comment by kalarepa** [comment]
> @kalarepa Which transformations are you using?

@molinch: That depends on image. Some of them lead to GIFs, some to videos, some are just plain images. In two first two cases I use bliting transform: https://gist.github.com/kalarepa/a4b12eec540dc23c66e8.

In general, there are three types of images in my app: avatars, preview images and full images. Transforms apply only to preview images. Full images can be huge (over 1080p), but don't have to be and usually aren't. And, according to my telemetry data, OOM occurs most rarely when viewing full images. Quite contrary to what one might expect.

> But all in all, I think that it isn't FFImageLoading bug - it's just device capacity limit when handling many pictures / large pictures.

@daniel-luberda: sure, I understand the limits. Yet, I'd prefer if app showed error placeholder rather than just crashed. And besides, you rarely have many images displayed at the same time. Unused ones can be just unloaded. I'll see if I can make ListView use less containers.

**Comment by molinch** [comment]
@daniel-luberda Transformations on WP could use a trick like here to reclaim memory sooner for old bitmap:
https://issues.apache.org/jira/browse/CB-5102

**Comment by molinch** [comment]
I have now in a branch: https://github.com/molinch/FFImageLoading/commit/9709bc21564a02bf226a4756faf0eb396e54c445

2 Disposable resources were not disposed, and old transformation data is nullified now.

**Comment by daniel-luberda** [comment]
@molinch Thanks for adding `using` - I missed that. 

But this: https://github.com/molinch/FFImageLoading/commit/9709bc21564a02bf226a4756faf0eb396e54c445#diff-c77559e28f7ebcd88b6ae27a8ad5796dL307 won't work because on Windows the same instance of BitmapHolder (and pixel array) is used for all transformations and other operations.

**Comment by molinch** [comment]
It's not always the same instance. Look at FlipTransformation for example.

**Comment by daniel-luberda** [comment]
Yes, `FlipTransformation` is one of rare exceptions - and it's nullified explictly. The whole point why BitmapHolder is reused in Windows is that in most of cases (transformations) we're dealing with pixel operation - there's no point to create int array every time as we only modify some pixels. We should definitely remove those lines.

**Comment by molinch** [comment]
They will not stop working. Look at the code it nullifies only if needed.

**Comment by daniel-luberda** [comment]
Ahhh ok! Sorry didn't see that: `if (old != null && old != imageIn && old.Pixels != imageIn.Pixels)` :)

**Comment by daniel-luberda** [comment]
But this `old.Pixels != imageIn.Pixels` had to be removed. As sometimes in transformations Pixels are changed to different instance currently with `bitmapHolder.SetPixels` method.

**Comment by molinch** [comment]
We could do that but still you won't control transformations done by other persons so I would suggest keeping the check

**Comment by daniel-luberda** [comment]
So we should modify transformations to return new instance of bitmap holder if pixel data was changed completely.

**Comment by daniel-luberda** [comment]
> @daniel-luberda: sure, I understand there are limits. Yet, I'd prefer if app showed error placeholder rather than just crashed. And besides, you rarely have many images displayed at the same time. Unused ones can be just unloaded. I'll see if I can make ListView use less containers.

@kalarepa I'll see what can be done.

**Comment by daniel-luberda** [comment]
@molinch It can be a little misleading: 

- User creates a custom transformation
- User replaces pixels with `SetPixels` method
- `old.Pixels != imageIn.Pixels` bitmap holder is null and we'll a null exception

We could make `SetPixels` internal or remove the check. What do you think?

**Comment by molinch** [comment]
3rd point is not valid because:
`if (old != null``

But it's up to you. Basically my concern was mainly when we create another byte array of pixels and leave the old one.

**Comment by daniel-luberda** [comment]
Once again you're right. I definitely need a cup of coffee :P

**Comment by daniel-luberda** [comment]
https://github.com/molinch/FFImageLoading/commit/9c16aa2da5edc709c5b4bebc7789b657c5a7f787

**Comment by ravensorb** [comment]
Question -- is there a way to set a callback or "fallback" to a default image if a failure occurs (as an alternative to bubbling up the exception for a image load failure)?

**Comment by molinch** [comment]
@daniel-luberda Can I let you merge the changes since I cannot test on WP?

@ravensorb Yes there is a callback for that, it is `Error()` https://github.com/molinch/FFImageLoading/wiki/API#error
In any case exceptions are trapped, with or without the callback. The OutOfMemoryException is a special case: when it occurs you cannot always trap it & be safe, the OS might kill your app.

**Comment by daniel-luberda** [comment]
@molinch I made some optimizations https://github.com/molinch/FFImageLoading/commits/windows-changes

**Comment by daniel-luberda** [comment]
@kalarepa Could you test the actual repo? It should be better now :)

**Comment by daniel-luberda** [comment]
@molinch One more thing, I didn't do anything related to catching out of memory exceptions. Any advice where could we do that?

**Comment by daniel-luberda** [comment]
@molinch  Also would it do anything at all if OutOfMemory exception on Windows basically means that nothing could be done.

**Comment by kalarepa** [comment]
@daniel-luberda: thanks, I'll test it soon.

**Comment by molinch** [comment]
@daniel-luberda It's already behaving like that whatever the exception we get (on iOS/Android).
There's not much you can do when you get an OOM anyway.

**Comment by daniel-luberda** [comment]
Ok, so we could close the issue now as nothing more can be done here. 

@kalarepa Thanks for the info :) If you'll have any issues feel free to reopen it.

**Comment by kalarepa** [comment]
@daniel-luberda @molinch 
I deployed an update with all those recent improvements. On top of that, I added `Image.Source = null;` in `Page.Unloaded` event (as well as logic to set source when loaded again). This change cuts down RAM usage by 10-15 MB when switching image-filled pages.
Update is still propagating to users, so I don't know if it significantly improves the situation. But what I do know is that OOM still happens. I just don't know if less often.

Also, it doesn't seem that FFImage is leaking memory on it's own. When scrolling through virtualized ListView full with images, memory usage doesn't increase. Quite the opposite in fact - it decreases slightly.

Anyway, thanks a lot for responding so quickly. I'll let you know how this pans out.

**Comment by daniel-luberda** [comment]
@kalarepa Thanks, let us know - it's a very useful information.

If you have any idea how could we be more memory efficient, just tell us. My ideas so far: 

- Change BitmapHolder to use `byte[]` instead `int[]` internally - that way we could omit fast copying data from `byte[]` to `int[]` when creating `WriteableBitmap` - but GC should collect old `int[]` anyway and making custom transformations would be  lot less intuitive as some helpers methods should be used to operate on `byte[]` instead on pixels `int[]`
- Replace `WriteableBitmap` with custom implementation of `BitmapSource` - it could use `int[]` internally and it would be superb if it didn't require UI thread to modify it (I don't now if it's possible)
