### ISSUE TITLE
Limit disk cache allocated space

### ISSUE THREAD

**Issue by molinch** [molinch/FFImageLoading#111]
Currently the disk cache as an unlimited space: what goes in, never goes out unless you call some `ImageService.InvalidateXxx` methods.

Should we limit allocated space for the disk cache? That could bring some benefit for people loading random images that change all the time (not my use case at all though).

If we go in that direction then it's maybe time to try to use Akavache for the disk cache.
Therefore that would be a massive change so we would need to benchmark it to ensure it's not less performant in the end.

**Comment by ravensorb** [comment]
Having a "max cache size" would be great -- then use can remove images based on least used?

**Comment by daniel-luberda** [comment]
> Currently the disk cache as an unlimited space
You forgot about deleting old files which are expired (CacheDuration) - we do that currently.

Does Akavache uses only disk or does it cache also in memory? Currently, we use a Dictionary, it would be hard to have something more performant than that :) 

Limiting cache size is a great idea though. +1

**Comment by molinch** [comment]
you are totally right @daniel-luberda! I forgot about cache duration. I guess I was tired when I wrote this :)

In that case it's more a nice to have. And yes @ravensorb we could imagine a LRU disk cache.

**Comment by daniel-luberda** [comment]
Another alternative is to provide something like `public Task<long> GetDiskUsageInBytes()` method. This way users could clear cache by themselves just by checking if a specific value was reached. It would be a lot easier to implement. What do you think?

**Comment by Mookker** [comment]
Guys, what max cache size uses as value, Mbs, Kbs, percent of memory? There is nothing in documentation. Thank you

**Comment by molinch** [comment]
@Mookker It is in bytes and only used for the memory cache: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Common/Config/Configuration.cs#L30

Furthermore it cannot be greater than 20% of available memory. We automatically limit to that, it's the upper limit.

**Comment by Mookker** [comment]
Thank you!

**Comment by daniel-luberda** [comment]
Potential issue: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Shared/Cache/DiskCache.cs#L191-L204

Shouldn't we call `InitializeWithJournal()` after removing all the cache files (including journal)?

**Comment by molinch** [comment]
yes we should good catch :+1:

**Comment by daniel-luberda** [comment]
I'll fix that! It's also needed in Windows implementation too.

**Comment by daniel-luberda** [comment]
@molinch iOS/Android fixed: https://github.com/molinch/FFImageLoading/commit/91ba594516694935b8aed4d0cdf0ae4bcdbf5593

Checked Windows implementation and it doesn't need a fix.

**Comment by molinch** [comment]
Let's close this task since we talked about totally unrelated stuff and we won't develop a disk LRU cache in short/medium time anyway.
