### ISSUE TITLE
Remove quality parameter for GetImageAsPNG(int quality)

### ISSUE THREAD

**Issue by PaulAchess** [molinch/FFImageLoading#114]
The quality parameter does not make sense for PNG files.

It is not used in the iOS / Windows code and ignored by the Android framework ([here](http://developer.android.com/reference/android/graphics/Bitmap.html#compress(android.graphics.Bitmap.CompressFormat, int, java.io.OutputStream))).

I think it should be removed: I was really trying to understand what this parameter meant the first time, as PNG is a lossless compression.

**Comment by daniel-luberda** [comment]
Yes, that's true, but the only, quite important thing is that it could break existing code - quality parameter will become desiredWidth parameter. That's a problem - we should leave it as is now but we could add XML info that this parameter is ignored.

**Comment by molinch** [comment]
We can have two methods and one of them marked as obsolete.
Then in the future we remove the obsolete one.

**Comment by daniel-luberda** [comment]
I could do that - but look at the method signature: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Forms/CachedImage.cs#L520

Default parameter values :/

**Comment by molinch** [comment]
Yes kinda sucks :(
Another alternative which is more verbose is:
```c#
public Task<byte[]> GetImageAsPNGWithDesiredWidth(int width)

public Task<byte[]> GetImageAsPNGWithDesiredHeight(int height)
```

and then we mark the other method as obsolete.  But to be honest it's a lot of change for not much...

**Comment by daniel-luberda** [comment]
I'll add an XML comment for now and then we'll decide what to do. It's not that much issue after all.

**Comment by molinch** [comment]
:+1:

**Comment by PaulAchess** [comment]
I did not think about breaking existing code, that is indeed pretty hard to solve.

The xml documentation is already a good thing in my opinion.

Or you could use this opportunity to rename the method `GetImageAsPNGAsync(…)` (add Async)

**Comment by PaulAchess** [comment]
:+1:
