### ISSUE TITLE
FFImageLoading is unable to generate image

### ISSUE THREAD

**Issue by Bonelol** [molinch/FFImageLoading#115]
Unable to get image from Facebook in iOS, when image url is like bellow
https://graph.facebook.com/1006568059385230/picture?type=normal.

Here is the code I used to do initializing:
ImageService.Initialize(httpClient: new HttpClient(new NativeMessageHandler()));

**Comment by daniel-luberda** [comment]
I think it's related to http redirects. 
- If you're using custom HttpClient you have to configure it to follow redirects. Did you try that? 
- Did you try if it's working without using custom HttpClient?

**Comment by Bonelol** [comment]
Hi Daniel, just found out it is my fault that I forgot to clear OAuth token from header. It all works now, thanks.

**Comment by daniel-luberda** [comment]
Ok, no problem. Cheers.
