### ISSUE TITLE
Xamarin.Forms - ListViewCachingStrategy.RecycleElement issue

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#117]
**Problem:**

If we use Bindings for setting `Source` property in a ViewCells which are used in a ListViews with ListViewCachingStrategy.RecycleElement enabled - images get loaded into CachedImage not correctly (they are mixed).

**It's because:**
> Note: When devolopers specify ListViewCachingStrategy.RecycleElement, OnElementChanged events are not raised when cells are recycled. Instead, the cell is retained and its property values change when the binding context is updated to that of an available cell, OnElementPropertyChanged events are raised. Application developers should remember to listen for the correct events, and should note that their renderers will need to be updated if the default behavior changes to ListViewCachingStrategy.RecycleElement in a future release.

**To avoid it:**

#### Instead using bindings for setting Source property - please use ViewCell's OnBindingContextChanged override to update it avoiding loading images to wrong views.

Any ideas how can we overcome that? Or should we leave it as is as maybe it's intended behavior when using this kind of ListViewCachingStrategy?

**Comment by molinch** [comment]
I would suggest writing about it in XF Slack room: https://xamarinchat.slack.com
Maybe some XF guys is there

**Comment by ahohns** [comment]
@daniel-luberda What are the symptoms of this exactly? We occasionally have an issue where the wrong image gets cached - eg: user 1's profile image is actually displaying user 3's profile image and it stays that way throughout the app (so the wrong image is being attached to the cache key somehow). Haven't looked into it too much but it could always be occurring on the main page which uses recycled cells.
If this isn't a symptom of this I may need to open a new issue.

**Comment by daniel-luberda** [comment]
@ahohns Hi, sorry for answering so late. I've been quite busy. 

Symptoms are that images get mixed between ListViews rows (eg. image from third row shows image from first row, etc). Did you try to use `OnBindingContextChanged` override instead using bindings?

**Comment by ahohns** [comment]
mm completely different issue then, thanks.

**Comment by molinch** [comment]
@ahohns would it be possible to open an issue about it and add some sample there?

**Comment by ahohns** [comment]
Possibly - it's one of those "it very rarely happens but it does happen" things so there's no reliable way to repro and I'd need to make sure it isn't our server causing the problem first.

**Comment by adrianknight89** [comment]
Hi all, I was seeing mixed images as I scrolled fast. I'm setting properties in `OnBindingContextChanged`. Please see here http://forums.xamarin.com/discussion/59402/implementation-of-custom-view-cells-for-a-listview-with-recycleelement#latest

This seems to fix the issue.

**Comment by coonmoo** [comment]
I think it's an intended behaviour. As Xamarin states, do not use bindings. This problem otherwise occurs on many other controls, too.

**Comment by molinch** [comment]
@coonmoo @daniel-luberda  John Miller from Xamarin confirmed it

> Note: When developers specify ListViewCachingStrategy.RecycleElement, OnElementChanged events are not raised when cells are recycled. Instead, the cell is retained and its property values change when the binding context is updated to that of an available cell, OnElementPropertyChanged events are raised. Application developers should remember to listen for the correct events, and should note that their renderers will need to be updated if the default behavior changes to ListViewCachingStrategy.RecycleElement in a future release.

> It's mentioned in the API documentation: https://developer.xamarin.com/api/type/Xamarin.Forms.ListViewCachingStrategy/

@daniel-luberda Do we need to do anything in the renderer? If not then let's close this

**Comment by daniel-luberda** [comment]
@molinch We don't need to change anything in renderers. I'll update WIKI.
