### ISSUE TITLE
FFimage loading in cells of a tableview

### ISSUE THREAD

**Issue by rusty21** [molinch/FFImageLoading#119]
I'm creating a news feed type tableview where each cell will need to have at least 3 images loaded when the cell scrolls onto the screen. When using ff image loading my tableview is very laggy. When a new cell is about to enter this is a very noticeable stutter that make the tableview almost unusable. If I comment out all of my ImageService.LoadUrl().Into()'s the lag goes a way. Is there anything I can do to avoid this problem?

**Comment by molinch** [comment]
Could you post the image loading request that you write?
Also which platform and device model?

**Comment by rusty21** [comment]
It's actually happening on both iOS and Android. For iOS the test device is an iPhone 5 running iOS 8. The android device is a Samsung Galaxy s5 running android 4.4.
I have varius other things in my "GetCell" method but here are the ff image loading parts.
Android:
    if (!string.IsNullOrEmpty (item.SiteIconUrl))
    {
    	ImageService.LoadUrl (item.SiteIconUrl).IntoAsync (view.FindViewById<ImageViewAsync> (Resource.Id.imgSiteIcon));
    }
    else
    {
    	view.FindViewById<ImageViewAsync> (Resource.Id.imgSiteIcon).SetImageBitmap (null);
    }
    
    ImageService.LoadUrl (item.UserProfileUrl).Transform (new CircleTransformation ()).IntoAsync(view.FindViewById<ImageViewAsync>(Resource.Id.imgProfileImage));
    
    ImageService.LoadUrl(item.PostedImageUrl).IntoAsync(view.FindViewById<ImageViewAsync>(Resource.Id.imgPostedImage));

iOS:
    if (!string.IsNullOrEmpty (item.SiteIconUrl))
    {
    	ImageService.LoadUrl (item.SiteIconUrl).Into (cell.ViewWithTag (1) as UIImageView);
    }
    else
    {
    	(cell.ViewWithTag (1) as UIImageView).Image = null;
    }
    ImageService.LoadUrl (item.UserProfileUrl).Into (cell.ViewWithTag (4) as UIImageView);
    
    var imageView = cell.ViewWithTag (16) as UIImageView;
    ImageService.LoadUrl(item.PostedImageUrl).Into(imageView);

**Comment by molinch** [comment]
@rusty21 If you are able to upload a sample or to mail it to me, I'm happy to profile it.
Would that be possible?

**Comment by molinch** [comment]
@rusty21 If you prefer to mail me a zip that's also possible.

**Comment by rusty21** [comment]
Yes, I would like to mail your a zip. I've very busy at the moment but I will try to get you a sample as soon as I can. Where can I send it once its ready?

**Comment by molinch** [comment]
fabien dot molinet at gmail dot com

**Comment by rusty21** [comment]
Thanks got it, you can remove your comment if you like.

**Comment by molinch** [comment]
Done :)

**Comment by molinch** [comment]
@rusty21 Do you still have this issue? If yes could you send me a repro?

**Comment by molinch** [comment]
Thanks for the repro

There were areas for improvements https://github.com/molinch/FFImageLoading/commit/f645c40170adc27d9c0443747e06631e4b4fa91f.

I compared before/after and the difference is huge: the UI is more reactive.

**Comment by rusty21** [comment]
I looked over your changes they looked good. Are these changes going to be reflected on Android as well?

**Comment by molinch** [comment]
Some of these will be on Android yes. Even though the major performance increase remains on iOS.
We expect to deliver a new nugets soon.

Please note that we also updated WP part which is also much faster now.
