### ISSUE TITLE
Xamarin.Forms nuget lacks Windows UWP support (currently only WinRT and SL)

### ISSUE THREAD

**Issue by coonmoo** [molinch/FFImageLoading#120]
I added the latest (2.0.3) FFImageLoading.Windows and Xamarin.FFImageLoading.Forms to my Xamarin.Forms UWP Project via nuget.

When I try to compile the Project I get the following errors:

Severity	Code	Description	Project	File	Line
Error		Cannot resolve Assembly or Windows Metadata file 'Xamarin.Forms.Platform.WinRT.dll'	MyUwpApp	D:\Apps\MyUwpApp.csproj	
Error		Type universe cannot resolve assembly: Xamarin.Forms.Platform.WinRT, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null.	MyUwpApp		

Do I miss something?

**Comment by daniel-luberda** [comment]
Currently, there's no Xamarin.Forms UWP renderer in nuget package. You have to clone the repo and build it by yourself. Nuget contains only Xamarin.Forms WinRT/Silverlight renderers.

**Comment by coonmoo** [comment]
Thanks again for the fast answer :)!

**Comment by daniel-luberda** [comment]
@coonmoo No problem. I'll try to include UWP renderer soon in nuget but to be honest - I didn't install UWP SDK's yet on my dev machine (I am using WinRT currently) :)

**Comment by coonmoo** [comment]
Thanks :)

I currently build it myself and added it to our project. Seems to work pretty solid.

**Comment by daniel-luberda** [comment]
I think I found one more bug. I'll let you now.

**Comment by daniel-luberda** [comment]
@coonmoo Thanks! :) If you have any issues - just report them here as I didn't install UWP SDKs yet. I'm only testing FFImageLoading on WinRT currently.

**Comment by escamoteur** [comment]
Is this solved? I just ran into the same error.

**Comment by daniel-luberda** [comment]
Yes :) Just a few minutes ago: try 2.0.7 nuget.
