### ISSUE TITLE
Real dimension loaded of image in CachedImage?

### ISSUE THREAD

**Issue by coonmoo** [molinch/FFImageLoading#121]
Could you add an API to fetch the real dimensions of a loaded Image (especially Xamarin.Forms).

Actually when I call cachedImage.Height/Width I get the dimensions of the Xamarin.Forms component (which is mostly larger than the image because of the aspect).

So would it be possible to read the real dimensions of the image when loading it into the view? So e.g. we could access the component "cachedImage.ImageWidth" (of course we would also need a property to get the downsampled height/width.

**Comment by daniel-luberda** [comment]
It's already possible: https://github.com/molinch/FFImageLoading/wiki/Xamarin.Forms-API#success (it returns image size). Dd you try it?

**Comment by molinch** [comment]
@coonmoo Is it OK for you?

**Comment by molinch** [comment]
I'm closing the issue since it's already present in our API.
If you are having a question regarding the usage/or have a different need then please reopen it or create a new.

**Comment by coonmoo** [comment]
Sorry for the late reply. Yes this seems to be working.
But I don't like the fact that I have to subscribe to an Event.

I'd prefer a property on the Image like "image.ImageSize" which might be null if not yet loaded.

And maybe an extension like:

await image.WaitUntilLoadFinished(timeout);

**Comment by daniel-luberda** [comment]
We introduced `SuccessComand` which is bindable and works just the same as Success event. Would it be better? `Args` are passed as command parameter.

**Comment by molinch** [comment]
@coonmoo We will not add properties where values are lazy loaded in TaskParameter.

Therefore you now have the choice between the Command or the Event.

**Comment by daniel-luberda** [comment]
@coonmoo 2.0.5 with SuccessCommand released :) Cheers
