### ISSUE TITLE
InvalidOperationException: Cannot redisplay this drawable, its resources have been disposed.

### ISSUE THREAD

**Issue by Mookker** [molinch/FFImageLoading#124]
Getting this stack-trace and exception

```c#
InvalidOperationException: Cannot redisplay this drawable, its resources have been disposed.

 FFImageLoading.Drawables.SelfDisposingBitmapDrawable.SetIsDisplayed(Boolean isDisplayed):0
 FFImageLoading.Views.ManagedImageView.UpdateDrawableDisplayedState(Android.Graphics.Drawables.Drawable drawable, Boolean isDisplayed):0
 FFImageLoading.Views.ManagedImageView.SetImageDrawable(Android.Graphics.Drawables.Drawable drawable):0
 FFImageLoading.Work.ImageLoaderTask.SetImageDrawable(Android.Widget.ImageView imageView, Android.Graphics.Drawables.Drawable drawable, Boolean fadeIn):0
 FFImageLoading.Work.ImageLoaderTask+<LoadPlaceHolderAsync>c__async4+<LoadPlaceHolderAsync>c__AnonStoreyF.<>m__1():0
 FFImageLoading.Helpers.MainThreadDispatcher+<PostAsync>c__AnonStorey0.<>m__0():0
```

Reproducible on different devices, maybe caused by slow connection, but not sure

**Comment by molinch** [comment]
Could you write your image loading request? I guess you are using 2.0.3 isn't it?

**Comment by Mookker** [comment]
Yes, 2.0.3.
				ImageService.LoadUrl(url, Constants.CacheDuration).
				LoadingPlaceholder("Images/Placeholder.jpg", FFImageLoading.Work.ImageSource.ApplicationBundle).
				TransparencyChannel(false).
				DownSample(img.Width).
				Into(img);

Image is descendent of ImageViewAsync

**Comment by molinch** [comment]
Is it used in a ListView or in a RecyclerView or something else?

**Comment by Mookker** [comment]
In ListView item

**Comment by daniel-luberda** [comment]
@molinch  https://github.com/molinch/FFImageLoading/commit/2d34a8b9dc60e0524d2001dd04a257784b06b7b0  Could you check this?

**Comment by Mookker** [comment]
@daniel-luberda  If it helps, when can it be released?

**Comment by daniel-luberda** [comment]
@Mookker Actually, in a few minutes. One more question. What is Android version of devices you got those exceptions?

**Comment by Mookker** [comment]
@daniel-luberda  4.1 4.2
Pretty old, but I didn't test on newer

**Comment by daniel-luberda** [comment]
You can now try 2.0.4 release

**Comment by Mookker** [comment]
Thank you! I'll try it and let you know, if it reproduces in future

**Comment by daniel-luberda** [comment]
@Mookker Do you still experience those issues? I'll close it but feel free to reopen it if you experience `resources have been disposed` related problems.

**Comment by BradleyDHobbs** [comment]
I'm getting this on Android API 17

**Comment by molinch** [comment]
Do you use 2.0.6 nuget?

**Comment by chamamo** [comment]
I'm getting this on Android with version 2.0.6
I'm using ImageViews in RecyclerView and I load images in OnBind method.
Before loading Image I try to recycle previous one like this:

`imageView.CancelLoading();

var drawable = imageView.Drawable;
            if (drawable is BitmapDrawable)
            {
                var bitmapDrawable = (BitmapDrawable)drawable;
                var bitmap = bitmapDrawable.Bitmap;
                if (bitmap != null)
                    bitmap.Recycle();
            }
ImageService.LoadUrl(imageUrl).Into(imageView);`

**Comment by molinch** [comment]
@chamamo You shouldn't recycle the bitmap.
We have an internal pool it will be recycled automatically when needed.

**Comment by chamamo** [comment]
@molinch Done, thanks
