### ISSUE TITLE
How to implement in Windows Universal Application?

### ISSUE THREAD

**Issue by K232** [molinch/FFImageLoading#125]
Hi all,
sorry for the beginner question but I've tried to find on my own without success :-( I want to use FFImageLoading in the Windows universal part of my Xamarin project. So I made the following steps:
1. Added FFImageLoading.Windows via nuget
2. Added  xmlns:ff="using:FFImageLoading" and xmlns:fft="using:FFImageLoading.Transformations" to my page.
3. Replaced the existing IMAGE with ff:FFImage as you've shown at http://stackoverflow.com/a/33899830/672756. The element is part of a DataTemplate used in a ListView.

Now I run in VS2015 and it works fine as long as I'm online. For testing I turned off my wifi to see the offline functionality, but it does not work. It shows the loading-image, and after around 2 seconds it goes to the error-image :-( What am I missing?
Additionally, is there somewhere an explanation of the attributes? I wonder about the unit of CacheDuration. 
Thanks!

**Comment by daniel-luberda** [comment]
> Now I run in VS2015 and it works fine as long as I'm online. For testing I turned off my wifi to see the offline functionality, but it does not work. It shows the loading-image, and after around 2 seconds it goes to the error-image :-( What am I missing?

Are you sure you're application cache files aren't deleted between builds? FFImageLoading should load images from disk cache if they exists. 

> Additionally, is there somewhere an explanation of the attributes? I wonder about the unit of CacheDuration. 

Windows documentation is on my TODO list. CacheDuration unit: days

**Comment by daniel-luberda** [comment]
BTW: We currently use `ApplicationData.Current.LocalFolder` for FFImageLoading cache but we should use `ApplicationData.Current.TemporaryFolder` instead. I think we should change that in future releases. I didn't notice it earlier. @kalarepa @PaulARoy What do you think?

**Comment by daniel-luberda** [comment]
@K232 One thing. Does you urls are the same on every subsequent request? Or do they change? (eg. some token).

**Comment by kalarepa** [comment]
@daniel-luberda: yes, I agree about TemporaryFolder.

**Comment by K232** [comment]
@daniel-luberda Thanks for fast reply.
I've checked Windows.Storage.ApplicationData.Current.LocalFolder to ensure I'm in the right path. It contains a subdirectory "ImageService" which contains a file called "FFImageLoadingCache.journal" and 17 files containing a GUID as filename, no extension. When I add ".png" the images open correct so these are the downloaded files. The files are still available when I turn off wifi and start my app in VS2015 again....nevertheless they are not displayed :-( I've also seen that most (not all!) of the icons are refreshed when I restart my app with wifi turned on so they got a new timestamp.
Regarding the filename: Yes, they are always the same. I don't use tokens or other parameters, just simple URLs. Filenames contain underscores, numbers, points and characters, but should be easy to cache. No tokens or else.
Not sure whether it's of interest: I'm using VS2015 to develop a Windows 10 Universal App. Here is the XAML code, maybe something is wrong with that?
     

    <ff:FFImage Name="Image" VerticalAlignment="Center" HorizontalAlignment="Center"
       TransformPlaceholders="False" LoadingPlaceholder="loading.png" ErrorPlaceholder="loading.png"
       CacheDuration="30" RetryCount="3" RetryDelay="250" Height="100" Width="100"
       DownsampleToViewSize="True" DownsampleMode="None" Source="{Binding ImageURL2}"
       Visibility="{Binding ShowImage, Converter={StaticResource BooleanToVisibilityConverter}}">
     </ff:FFImage>

**Comment by K232** [comment]
I made some further tests:

Now I've made the following tests:
1. Deleted directory 'ImageService'.
2. Changed XAML Code. Used hardcoded source https://pixabay.com/static/uploads/photo/2015/09/06/20/30/sport-927762_960_720.jpg
3. Turned on wifi. Started app. Item is displayed as expected. ImageService contains the journal and the downloaded file '11427b176c03b6da9af98214108feede' Timestamp: 01:06.
4. Turned off wifi. Started app. Item is displayed as expected.
5. Changed hardcoded source to https://pixabay.com/static/uploads/photo/2015/12/04/18/40/salt-shaker-set-1076953_960_720.jpg
6. Turned on wifi. Started app. Item is displayed as expected. ImageService now contains another (3rd) file, Timestamp 01:10.
7. Turned off wifi. Started app. Item is displayed as expected.
8. Wifi still turned off. Changed source back to previous https://pixabay.com/static/uploads/photo/2015/09/06/20/30/sport-927762_960_720.jpg. **Item is NOT displayed**, only loading / error. But the cached file (with timestamp 01:06) is still available in the ImageService.
9. Turned on wifi. Item is displayed as expected. Timestamp of file '11427b176c03b6da9af98214108feede' *has changed to 01:14*.

So it seems that the cache does not recognize the existing file and then recreates it with the same filename...?

**Comment by molinch** [comment]
Many thanks @K232 for your detailed feedback.
I just re-run the exact same scenario on Android and iOS.
- Android: no issues
- iOS: no issues

So, if there is an issue, I am confident it only happens on WP.
@daniel-luberda Could you have a look?

**Comment by PaulARoy** [comment]
Temporary folder seems better indeed. But I do not use the cache functionality a lot (the big plus that draw me here was the transformations) and I will not be able to help you much.

A small thing, I remember I had issues with file deletion on windows phone (files were considered in use even if they were not any longer). 

My use case was: 

* use an image in the source of Image object
* change source of Image object.
* delete the previous file: error

Might be solved by using temporary folder. If the repro is 100% with the use-case I think we should try this first.

The workaround I used was to use suffix for images and delete previous images on start. Not ideal but it works.

**Comment by daniel-luberda** [comment]
@PaulARoy @kalarepa https://github.com/molinch/FFImageLoading/commit/94d2492f8553f45c78ef34da02e62cc8dde70845

@K232 Thanks for such a detailed debugging. Indeed, I confirm the issue on Windows. I'll try to debug it and let you know.

**Comment by K232** [comment]
@daniel-luberda I'm happy you are able to recreate the problem so it's not (only) my stupidity... :)

**Comment by PaulARoy** [comment]
:+1:

**Comment by daniel-luberda** [comment]
That was such a silly and very major bug. On Windows FFImageLoading had always only one entry because every time cache entry was added, it was written to the beginning of journal file. :/ Sorry for that :/ We have to release nuget as soon as possible!

**Comment by daniel-luberda** [comment]
@kalarepa @PaulARoy @molinch @K232 Look at this: https://github.com/molinch/FFImageLoading/commit/df5009021aab01421c4ed5cf6fbbf31efde34bb2

**Comment by PaulARoy** [comment]
Tricky indeed. I am not an expert on this subject but this seems good.

Would `writer.BaseStream.Seek(…)` be better than `stream.Seek(…)`? It should be exactly the same object, but I stopped trusting properties since [this](https://github.com/molinch/FFImageLoading/issues/113)

**Comment by daniel-luberda** [comment]
@PaulARoy writer.Seek should be fine too :) 

So basically that bug caused, that disk caching was only working for a one file up to this day. @K232 Thanks for noticing it. Nasty :/ ... and once again sorry for that. I'll make 2.0.5 nugets in a few minutes.

**Comment by daniel-luberda** [comment]
I also changed journal filename as old one is probably corrupted: https://github.com/molinch/FFImageLoading/commit/f174b9183174f942eb1a4e2d3adaf3ce02fcaae3

**Comment by PaulARoy** [comment]
Will this invalidate all current cache?

**Comment by daniel-luberda** [comment]
Yes, I changed default folder anyway.

**Comment by PaulARoy** [comment]
:+1:

**Comment by daniel-luberda** [comment]
Another fix, now everything should be ok.

**Comment by K232** [comment]
Great, I'm keen on testing. Can't wait for the new nuget package.... Thanks a lot for this brilliant fast action!!! :+1:

**Comment by daniel-luberda** [comment]
@K232 @kalarepa @PaulARoy 2.0.5 with Windows fixes released!

**Comment by K232** [comment]
Works brilliant! Thanks a lot @daniel-luberda ! :+1:

**Comment by daniel-luberda** [comment]
@K232 Once again, thanks for a detailed debugging. Without it, i wouldn't be aware of such a major disk cache issue. Luckily, we got it covered. Cheers.

**Comment by K232** [comment]
@daniel-luberda No Problem. As I'm also a developer I know how strange some user error reports could be, so I always try to be as detailled as possible. In the end, it's a bigger advantage for me, because now I could release my beta app this weekend!!
