### ISSUE TITLE
UWP crash when calling "GetImageAsJpgAsync"

### ISSUE THREAD

**Issue by coonmoo** [molinch/FFImageLoading#126]
Heya,

my UWP app crashes when I'm trying to read the image from the image view:

Element not found.
Windows.Graphics.Display: GetForCurrentView must be called on a thread that is associated with a CoreWindow.

Even if I call InvokeOnMainThread(()=>image.GetImageAsJpgAsync(100)) the same exception occurs.

**Comment by daniel-luberda** [comment]
@coonmoo Do you have more detailed stack trace?

**Comment by daniel-luberda** [comment]
Could you try the newest changes? I think it should be fixed now: https://github.com/molinch/FFImageLoading/commit/e165d7102c63e32f9da4bd477597a2f1f41a6cc5 and https://github.com/molinch/FFImageLoading/commit/9b63dc49b72fa5c14b2275c5916a7ddb34859e59

**Comment by coonmoo** [comment]
Wow, I'd wish xamarin had such a great support ;).

This issue is fixed.

**Comment by daniel-luberda** [comment]
Thanks :)
