### ISSUE TITLE
Droid: Rotate Transformation Scaling Issue

### ISSUE THREAD

**Issue by highplains** [molinch/FFImageLoading#127]
Code used for multiple rotations...

```
                if (_currentDegreees == 360)
                    _currentDegreees = 0;
                
                var source = ProfileImage.Source;
                ProfileImage.Transformations.Add(new RotateTransformation(_currentDegreees + 90d,false,true));
                ProfileImage.Source = null;
                ProfileImage.Source = source;
```

Android result at 0 degrees...
![screenshot_2016-01-15-13-52-01](https://cloud.githubusercontent.com/assets/1825076/12365146/39b0598e-bb90-11e5-9512-bdc1b2a5089e.png)

Android result after 360 degree rotation (notice cropping and scaling)
![screenshot_2016-01-15-13-52-16](https://cloud.githubusercontent.com/assets/1825076/12365162/4dc4af6a-bb90-11e5-8b38-fb3317c34855.png)

iOS seems to be ok as long as resize = true, if resize = false you will notice the same behavior on iOS.

**Comment by daniel-luberda** [comment]
@highplains Hi, i tried to reproduce it but it's working fine for me. Look at: https://gist.github.com/daniel-luberda/4d75d96968a7ab86c7cf

**Comment by molinch** [comment]
I played with it too and could not reproduce it either.

Could you write your image loading request? ie:
```c#
var cachedImage = new CachedImage() {
	HorizontalOptions = LayoutOptions.Center,
	VerticalOptions = LayoutOptions.Center,
	WidthRequest = 900,
	HeightRequest = 600,
	CacheDuration = TimeSpan.FromDays(30),
	Aspect = Aspect.AspectFit,
	DownsampleToViewSize = true,
	RetryCount = 0,
	RetryDelay = 250,
	TransparencyEnabled = false,
	Source = "http://loremflickr.com/900/600/nature?filename=simple.jpg",
};
```

**Comment by highplains** [comment]
Here is a repo showing iOS behaving fine and android doing the bug.

**Comment by highplains** [comment]
https://github.com/highplains/ImageRotation

**Comment by molinch** [comment]
Ok it's clear for me now: since you reuse the already rotated bitmap and rerotate it that's why it happens.
I don't think it's a bug of the lib, it cannot handle such cases.

My suggestion would be to use the original bitmap and each time change the rotation. This way you won't have this issue. So making a new image loading request but with a different rotation degree: 90, 180, ...

**Comment by highplains** [comment]
Indeed. :) Thanks for the tip. I got it working correctly on both platforms using this.

```
private void RotatePhoto_Clicked(object sender, EventArgs e)
        {
            try
            {
                //increment rotation for next pass
                _currentDegreees += 90;
                if (_currentDegreees == 360)
                    _currentDegreees = 0;

                // wipe out existing transformations
                ProfileImage.Transformations.Clear();
                // add new transformation
                ProfileImage.Transformations.Add(new RotateTransformation(_currentDegreees));
                // reset to original source
                ProfileImage.Source = _viewModel.Profile.ImageUrl;

            }
            catch (Exception ex)
            {
                #if DEBUG
                throw ex;
                #else
                Xamarin.Insights.Report(ex);
                #endif 
            }
        }
```

Thank you!

**Comment by molinch** [comment]
Awesome! I'm glad it worked :+1:
