### ISSUE TITLE
WinRT assets not working in CachedImage

### ISSUE THREAD

**Issue by wouterh** [molinch/FFImageLoading#128]
In windows phone 8.1 (WinRT) applications, using application bundle assets as the source for a CachedImage is not working in a way interoperable with Xamarin.Forms.Image.

For example, I have the following images in my application bundle:
* Assets\image.scale-100.png
* Assets\image.scale-140.png
* Assets\image.scale-240.png

When I then set the Source of a Xamarin.Forms.Image to 'Assets\image.png' it correctly loads one of the images above depending on the scale of the device.

When I set the same Source on a CachedImage, it doesn't load.

From looking at the code here:
https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Windows/DataResolver/ResourceDataResolver.cs#L26-L27

It will try to load the file 'Assets\Assets\image.png', which obviously doesn't work.

**Comment by molinch** [comment]
@daniel-luberda I guess that regular XF Image doesn't look in "Assets" straight away
If that's the case we should mimic XF default behaviour

**Comment by wouterh** [comment]
FYI, I now use the following code in a custom renderer to work around it:
```C#
        private string ConvertFileName(string filename)
        {
            if (filename.StartsWith("Assets"))
            {
                string f = System.IO.Path.GetFileNameWithoutExtension(filename);
                string e = System.IO.Path.GetExtension(filename);
                return string.Format("{0}.scale-{1}{2}", f, Scale, e);
            }
            else {
                return filename;
            }
        }

        private static int? _scale = null;

        private static int Scale
        {
            get
            {
                if(!_scale.HasValue)
                {
                    double scale = DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;
                    if(scale > 1.40)
                    {
                        _scale = 240;
                    } else if (scale > 1.00)
                    {
                        _scale = 140;
                    } else
                    {
                        _scale = 100;
                    }
                }
                return _scale.Value;
            }
        }
```
The part for the scale calculation could be useful.

Notes:
* I am not taking scale-180 into account that does exist for Windows 8.1, but not for Windows Phone 8.1
* I do not check if the scaled file exists, because for the assets I use it for, I know they exist. In the library you'll have to do some fallback mechanism, I guess.

**Comment by daniel-luberda** [comment]
@wouterh @molinch I'll fix this today before a release :) Thanks for info!

**Comment by daniel-luberda** [comment]
@wouterh  Nuget with fixes released :)

**Comment by wouterh** [comment]
@daniel-luberda it still prefixes "Assets\" ? X.F doesn't do that.

**Comment by daniel-luberda** [comment]
@wouterh I missed that, I'll fix it. Thanks for the info!

**Comment by daniel-luberda** [comment]
@wouterh Are you sure about it? If I remove "Assets" it doesn't work anymore. 

Xamarin uses:
```C#
new BitmapImage(new Uri("ms-appx:///" + fileImageSource.File)
```
FFImageLoading uses:
```C#
string resPath = @"Assets\" + identifier.TrimStart('\\', '/');
var imgUri = new Uri("ms-appx:///" + resPath);
file = await StorageFile.GetFileFromApplicationUriAsync(imgUri);
```

Maybe BitmapImage constructor adds "Assets" prefix later.

**Comment by wouterh** [comment]
@daniel-luberda for X.F.Image, I have to manually set the source to "Assets\image.png". Thus X.F is doing nothing with the path I give it, while FFImageLoading is prepending "Assets".

**Comment by daniel-luberda** [comment]
Ok, I made some changes to support both cases. That way `Image.png` will work on all platforms which is in my opinion a lot more expected behavior. 

```C#
string resPath = identifier.TrimStart('\\', '/');

if (!resPath.StartsWith(@"Assets\") && !resPath.StartsWith(@"Assets/"))
{
	resPath = @"Assets\" + resPath;
}

var imgUri = new Uri("ms-appx:///" + resPath);
file = await StorageFile.GetFileFromApplicationUriAsync(imgUri);
```

**Comment by wouterh** [comment]
@daniel-luberda actually Xamarin says:
> Windows Phone - Place images in the application's root directory with Build Action: Content .
(https://developer.xamarin.com/guides/xamarin-forms/working-with/images/)

Which would make `Image.png` work. 

But I don't like all my images to be in the root, so I've put them in a subfolder Assets anyway :-)

**Comment by daniel-luberda** [comment]
With this https://github.com/molinch/FFImageLoading/commit/4c16701a99a9074ba1e26424af3c10217f558f2b both cases would work, we have to leave it to not break code which works on previous FFImageLoading releases. :) 

Thanks once again!
