### ISSUE TITLE
Various small enhancements proposal

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#131]
1. ~~Ability to set fade animation duration~~ DONE
1. ~~Success handler should also pass original downloaded file path of image as parameter (if loaded from cache)~~ DONE
1. ~~Success handler should also pass both original image size and resized image size (width, height)~~ DONE

What do you think?

**Comment by molinch** [comment]
1. Good idea
2. I'm not sure to understand the need/the process you are interested to have
3. Why not, any use case?

**Comment by daniel-luberda** [comment]
1. Could we also add those setting to `ImageService.Initialize`? BTW: That method is getting big... I think that adding a class for those properties and passing it as a `ImageService.Initialize` parameter would be a lot cleaner solution.
1. To get an original file that was downloaded and process it in a custom way.
1. There are many use cases. One of them is CropTransformation. If user could know both sizes, then it's easier to control transformation parameters (bounds etc).

**Comment by molinch** [comment]
1. Yes it would be much cleaner :+1:  In fact there's already a class, so it would be easy to swap it to use the class :)
2. Still I don't get the need, do you have a clear example in mind?
3. Ok sure

**Comment by daniel-luberda** [comment]
> Yes it would be much cleaner :+1: In fact there's already a class, so it would be easy to swap it to use the class :)

Cool. We could also make the old one method `Obsolete`. 

> Still I don't get the need, do you have a clear example in mind?

Eg. Add a possibility to save **original** image to image gallery after tap and hold on imageView.

**Comment by daniel-luberda** [comment]
@molinch Could you take a look at: https://github.com/molinch/FFImageLoading/commit/0d28b54e394002ba0669588e7fdfcc28179bf90e ?

**Comment by molinch** [comment]
I saw it but I don't understand what means MultiplatformConfiguration. Isn't everything multiplatform?

**Comment by daniel-luberda** [comment]
I want to use that class in a Xamarin.Forms (multi platform variation of Initialize method). We can't provide disk, logger, etc implementations there. What do you think about it? We can also move the code to Configuration class and do it on a Xamarin.Forms project level.

**Comment by molinch** [comment]
Why can't these be provided on XF?
Initalize can be called by custom renderers isn't it?

Anyway since all properties are optional, default values are enforced, I don't see why we need an extra class.

**Comment by daniel-luberda** [comment]
- Yes, it can definitely be provided on XF side. I'm just wondering which approach is better. I just tried to avoid another class creation on XF side. 
- Currently `Configuration` class inherits from `MultiplatformConfiguration`. `MultiplatformConfiguration`, can be easily removed - it's just cut&paste.

**Comment by daniel-luberda** [comment]
Another thing: 

```C#
		public void Remove(string key)
		{
			_cache.Remove(key);
		}
```

This is how memory cache items are removed currently. What about all the variants (downsampling parameters, transformation parameters). In my opinion - they should be removed too. The method should delete all entries that start with the specified key. It's much more intuitive behavior. What do you think?

**Comment by molinch** [comment]
This last point is now implement.
So points 1, 2, 3 are still remaining right?

**Comment by daniel-luberda** [comment]
@molinch Yes, I'll try to implement number one first (fade)

**Comment by softwaremills** [comment]
Hey guys, I just want to thank you for the fantastic library and express my sincere appreciation. Thanks so much for the work you've put into it. :)

**Comment by daniel-luberda** [comment]
@softwaremills Thanks! :)

**Comment by molinch** [comment]
Many thanks @softwaremills ! :+1:

**Comment by daniel-luberda** [comment]
All missing points are now implemented with https://github.com/molinch/FFImageLoading/commit/95182999641a43e5fec25084c203707fe84999da
