### ISSUE TITLE
Fast scrolling up and down crashes the app for large ListView with embedded png files

### ISSUE THREAD

**Issue by adrianknight89** [molinch/FFImageLoading#132]
[Android.txt](https://github.com/molinch/FFImageLoading/files/101976/Android.txt)
[iOS.txt](https://github.com/molinch/FFImageLoading/files/101977/iOS.txt)

Please see http://forums.xamarin.com/discussion/59431/ffimageloading-does-not-display-images-properly#latest

**Comment by molinch** [comment]
Thanks @adrianknight89 
It was an issue with Streams used in lists: while scrolling fast a task was cancelled but the TaskCancelledException wasn't catched
