### ISSUE TITLE
iOS: Callbacks no longer invoked on MainThread

### ISSUE THREAD

**Issue by highplains** [molinch/FFImageLoading#135]
This code was working fine on 2.0.5 but now throws a NRE

```
        private async void ProfileImage_Success (object sender, FFImageLoading.Forms.CachedImageEvents.SuccessEventArgs e)
        {
            if (ProfileImage != null && _viewModel != null)
                _viewModel.ImageRaw = await ProfileImage.GetImageAsJpgAsync();
        }

```

**Comment by daniel-luberda** [comment]
I think we didn't change anything related to this method in 2.0.6. 

- Could you provide more details?
- What platform? 
- Any stack trace?

**Comment by highplains** [comment]
looks like it was getting executed on a background thread and crashing out. 

```
        private void ProfileImage_Success (object sender, FFImageLoading.Forms.CachedImageEvents.SuccessEventArgs e)
        {
            Device.BeginInvokeOnMainThread(() =>
                {
                    try
                    {

                        _viewModel.ImageRaw = ProfileImage.GetImageAsJpgAsync().Result;
                    }
                    catch (Exception ex)
                    {
                        Debug.WriteLine(ex);
                    }
                });


        }
```

seems to have fixed it. Thanks!

**Comment by daniel-luberda** [comment]
@highplains But could you tell me what platform is this? I can change that it'll be executed on main thread by default to avoid `Device.BeginInvokeOnMainThread` in future releases.

**Comment by highplains** [comment]
The platform I was testing on was iOS. Thanks!

**Comment by molinch** [comment]
Callbacks should be invoked on main thread. So we should change that

**Comment by molinch** [comment]
Success callback is now ALWAYS invoked on main thread.
Remark: Error callback and Finish callback do not enforce the main thread
