### ISSUE TITLE
System.ObjectDisposedException

### ISSUE THREAD

**Issue by sebastian-frysztak** [molinch/FFImageLoading#136]
Hi there,
remember `CTS.Dispose()` in `ImageLoaderTaskBase.Cancel()`? Well, it still crashes. At lot. I updated my app, some users already have newest version but it's looking pretty terrible so far.
I'm at https://github.com/molinch/FFImageLoading/commit/91ba594516694935b8aed4d0cdf0ae4bcdbf5593.

**Comment by daniel-luberda** [comment]
I could add some additional checks if cancellation token is disposed or null.

**Comment by molinch** [comment]
@sebastian-frysztak So you use the sources and not the nuget in your app right?

**Comment by sebastian-frysztak** [comment]
@molinch: yes. I really wished to use nuget this time, but CTS fixes where not included in latest release.

I'm trying to trigger exception in ListView demo and it doesn't seem to be happening.
I suppose I could add:
`if(!_isDisposed)
    CancellationToken.Cancel();`, but I don't want to guess.

**Comment by molinch** [comment]
Do you have a stacktrace by any chance?

**Comment by sebastian-frysztak** [comment]
Sure:
`   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at FFImageLoading.Work.ImageLoaderTaskBase.Cancel()
   at FFImageLoading.FFImage.<LoadImage>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()`

I just managed to trigger the exception. I guess it only happens when image is loaded from cache.

**Comment by sebastian-frysztak** [comment]
So it looks like `if(!_isDisposed)
                CancellationToken.Cancel();` will do the job. Or maybe there's something else that also needs to be added? What do you think?

**Comment by molinch** [comment]
Damn my bad I refactored everything and forgot that one. I'm really sorry.
Thanks for the hint @sebastian-frysztak

**Comment by sebastian-frysztak** [comment]
It's okay. Thank you for reacting so quickly.

**Comment by daniel-luberda** [comment]
:thumbsup: 

@sebastian-frysztak  BTW:  I'm just curious if you profiled memory usage after Windows optimizations from 2.0.6? Are there any features that you miss in FFImage?

**Comment by sebastian-frysztak** [comment]
@daniel-luberda: yes, I did. I would just start my app and scroll, until I got to given entry. So I'm not sure how reliable it is.
But overall - It's much better. Memory usage seems lower, and so are the peaks (when opening a image). And it definitely feels faster.

And as for features, sometimes I wish that loading placeholders would show after a bit of delay. Because currently, when you're on fast Internet connection and you scroll up quickly, loading placeholder shows up for a split second. And this is bad UX.
Then again, if this was implemented, maybe app would more unresponsive on users with bad mobile connection. I don't know.

**Comment by daniel-luberda** [comment]
> But overall - It's much better. Memory usage seems lower, and so are the peaks (when opening a image). And it definitely feels faster.

@sebastian-frysztak I'm happy to hear that! There's another place for optimizations in Transformations handling. We could avoid using `int[]` which we fast-copy to `byte[]` unnecessary and could switch to using `byte[]` internally avoiding it. Did some initial changes in https://github.com/molinch/FFImageLoading/tree/windows-new-bitmapholder-optimization branch. Do you use transformations or custom transformations? 

> And as for features, sometimes I wish that loading placeholders would show after a bit of delay. Because currently, when you're on fast Internet connection and you scroll up quickly, loading placeholder shows up for a split second. And this is bad UX.a

I noticed that too. @molinch Do you have any idea how could we improve that?

**Comment by sebastian-frysztak** [comment]
@daniel-luberda: I use just one transformation. And it's not applied to every image. I think I posted it here some time ago. It's a blitting transformation - overlaying one semi-transparent image over another.
I'd have to change it a bit to make use of new BitmapHolder, but I don't mind as long as it's faster.

You can't just cast int[] to byte[] in C#, right?

**Comment by daniel-luberda** [comment]
> You can't just cast int[] to byte[] in C#, right?

Sadly, no... We use some unsafe code to make it faster:  https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Windows/Extensions/ImageExtensions.cs#L135-L152 - but it's still copying. 

@sebastian-frysztak I'll provide some extension methods that can help to operate on `byte[]` arrays. Here: https://github.com/molinch/FFImageLoading/blob/windows-new-bitmapholder-optimization/source/FFImageLoading.Windows/Transformations/TransformationExtensions.cs

**Comment by sebastian-frysztak** [comment]
@daniel-luberda: Good, it'll maybe it easier for others to port to new API.
BTW, do you have any estimates how many users use this library? I mean end-users, consumers not developers.

**Comment by daniel-luberda** [comment]
> BTW, do you have any estimates how many users use this library? I mean end-users, consumers not developers.

@sebastian-frysztak It's really hard to estimate such data. I suppose, a lot :) Do you need it for some special reason or just curious?

**Comment by sebastian-frysztak** [comment]
@daniel-luberda: just curious :).
