### ISSUE TITLE
Add ForceReload to CachedImage

### ISSUE THREAD

**Issue by adrianknight89** [molinch/FFImageLoading#137]
See https://forums.xamarin.com/discussion/60121/ffimageloading-resize-image-on-device-orientation-change#latest

Image doesn't seem to be resizing on device orientation change on Android. iOS seemed fine when I tried, but you should double check.

**Comment by adrianknight89** [comment]
Sorry i think this could be closed. Just looked at commit history.

**Comment by daniel-luberda** [comment]
@adrianknight89 Implemented here: https://github.com/molinch/FFImageLoading/commit/c9879132bf9307af509ee5fe9d7132edada188d6  :)
