### ISSUE TITLE
Android ImageViewAsync - adjustViewBounds and fitCenter

### ISSUE THREAD

**Issue by c1rus** [molinch/FFImageLoading#138]
Hi guys, again, awesome work with the library :) 

Just found one problem with ```adjustViewBounds="true"``` and ```scaleType="fitCenter"```.

This my ImageView setup:

```
    <ImageView
        android:id="@+id/imageLogoOnly"
        android:padding="16dp"
        android:layout_marginBottom="8dp"
        android:layout_width="170dp"
        android:adjustViewBounds="true"
        android:scaleType="fitCenter"
        android:layout_height="wrap_content"
        android:layout_gravity="center" />
```

And this is result with regular ImageView:

![imageview](https://cloud.githubusercontent.com/assets/11233730/12774806/a7afdf2e-ca48-11e5-8578-eb056fb10a75.png)

And ImageViewAsync:

![imageviewasync](https://cloud.githubusercontent.com/assets/11233730/12774807/abcf7060-ca48-11e5-9410-843229e1a21e.png)

Any clues?

Thanks.

**Comment by daniel-luberda** [comment]
@c1rus It should work now. Are you able to test it? :)

**Comment by c1rus** [comment]
Nope. It's weird.

I tried to comment all stuff in ImageViewAsync and ManagedImageView and same result

this is working:
```
var bitmap = Android.Graphics.BitmapFactory.DecodeFile (sponsor.LogoLocalPath);
vh.ImageLogo.SetImageBitmap (bitmap);
```
this is not:
```
ImageService
	.LoadFile(sponsor.LogoLocalPath)
	.Into(vh.ImageLogo);
```

**Comment by daniel-luberda** [comment]
@c1rus Indeed, that's weird. 
- Did you try another images? Is it the same?

**Comment by c1rus** [comment]
It's the same.

Actually before i was trying this code only with ImageView, but it is working with ImageViewAsync as well:

```
var bitmap = Android.Graphics.BitmapFactory.DecodeFile (sponsor.LogoLocalPath);
vh.ImageLogo.SetImageBitmap (bitmap);
```

So the problem has to be somewhere here:
```
ImageService
    .LoadFile(sponsor.LogoLocalPath)
    .Into(vh.ImageLogo);
```

**Comment by c1rus** [comment]
Ok, i have found it, this lines are the problem:

https://github.com/molinch/FFImageLoading/blob/2b057e28f7e29719a58a21ad2513b0fabde59038/source/FFImageLoading.Droid/Work/ImageLoaderTask.cs#L644
https://github.com/molinch/FFImageLoading/blob/2b057e28f7e29719a58a21ad2513b0fabde59038/source/FFImageLoading.Droid/Work/ImageLoaderTask.cs#L804

**Comment by daniel-luberda** [comment]
@c1rus Nice catch! It'll be definitely easier to fix now. Thanks!

BTW: @molinch Intrinsic sizes can be sometimes misleading. Nice read about this: http://stackoverflow.com/a/28159175/5064986

**Comment by molinch** [comment]
@c1rus Wow you hit some legacy code :)
https://github.com/molinch/FFImageLoading/commit/ebf52fe5c3bbb01319af83f9184c5ece128830a1
It is one of the only remaining part that was already in the first library's commit...

I'll first try to remember why this is here I come back to you soon.

**Comment by daniel-luberda** [comment]
@molinch any news, can I safely delete it?

**Comment by daniel-luberda** [comment]
@c1rus It should be fixed now as legacy code was removed.

**Comment by molinch** [comment]
You didn't removed the correct code :)

**Comment by daniel-luberda** [comment]
@molinch Sorry and thanks!
