### ISSUE TITLE
Android: .webp images are displayed black/partially when loaded from server

### ISSUE THREAD

**Issue by coonmoo** [molinch/FFImageLoading#139]
I noticed another issue when images loaded from server display partially or completly black in CachedImage. It seems to be related to .webp processing.

When I load .jpg instead of .webp from the server I have no issues.

Heres the log from loading .webp files:

This occurs very often on low-end devices (with less than 1GB ram).
```

D/ReuseBitmapDrawableCache(17126): OnEntryAdded(key = http://imageserver.com/picture46.webp;60x0)
D/dalvikvm(17126): WAIT_FOR_CONCURRENT_GC blocked 0ms
D/dalvikvm(17126): GC_EXPLICIT freed 3729K, 20% free 20948K/25991K, paused 5ms+10ms, total 61ms
D/ReuseBitmapDrawableCache(17126): OnEntryAdded(key = http://imageserver.com/picture65.webp;60x0)
D/STATUSBAR-NetworkController( 2203): refreshSignalCluster: data=-1 bt=false
E/WifiHW  ( 2035): ##################### set firmware type 0 #####################
D/WifiStateMachine( 2035): setWifiEnabled : WifiNative.setFwType(0)
I/wpa_supplicant( 2698): Scan requested (ret=0) - scan timeout 30 seconds
D/WifiService( 2035): startScan: false pid=2505, uid=10016
W/AlarmManager( 2035): FACTORY_ON= 0
W/PowerManagerService( 2035): Timer 0x3->0x3|0x0
D/SelfDisposingBitmapDrawable(17126): OnFreeResources
D/skia    (17126): --- decoder->decode returned false
D/SelfDisposingBitmapDrawable(17126): OnFreeResources
D/skia    (17126): --- decoder->decode returned false
D/SelfDisposingBitmapDrawable(17126): OnFreeResources
D/skia    (17126): --- decoder->decode returned false
D/ReuseBitmapDrawableCache(17126): OnEntryAdded(key = http://imageserver.com/picture14.webp;480x0)
D/ReuseBitmapDrawableCache(17126): Reuse pool is not full, refusing reuse request
D/ReuseBitmapDrawableCache(17126): OnEntryAdded(key = http://imageserver.com/picture32.webp;60x0)
D/ReuseBitmapDrawableCache(17126): Reuse pool is not full, refusing reuse request
D/ReuseBitmapDrawableCache(17126): OnEntryAdded(key = http://imageserver.com/picture53.webp;480x0)
```

**Comment by coonmoo** [comment]
To reproduce:

1) Load some .webp files from web (I use a Resolution of 480x480)
2) I started an Android Emulator and set the Ram Limit to 512MB.
3) The images appear to be partially displayed

[http://s23.postimg.org/xk4hexpyz/webperror.png](url)

**Comment by daniel-luberda** [comment]
It may be related to this: 

- https://bugs.chromium.org/p/webp/issues/detail?id=170
- http://stackoverflow.com/questions/18842748/certain-webp-image-not-able-to-load-in-android-4 
- https://github.com/square/picasso/issues/177#issuecomment-32117960

**Comment by molinch** [comment]
@coonmoo Could you please indicate your Android version and also deliver an image that fails?

**Comment by coonmoo** [comment]
Thanks for the fast answer.

You are probably right, it's related to the issue because some Android versions do not support alpha.

Android Version is 4.1.2.

I'll send the Images to daniel-luberda because I can't attach them here.

**Comment by molinch** [comment]
Please have a look at: http://developer.android.com/intl/es/guide/appendix/media-formats.html
WebP lossy (Android 4.0+), so similar to JPG
WebP lossless, transparency (Android 4.2.1+), so similar to PNG

If you target a 4.1.2 device make sure your WebP image is lossy/without alpha.

**Comment by daniel-luberda** [comment]
I think we could close the issue.
BTW: Does anyone know a way for full support of `webp` in older Android versions?

**Comment by molinch** [comment]
@coonmoo This issue doesn't seem to be related to FFImageLoading.
Feel free to reopen it if you believe the opposite.

**Comment by coonmoo** [comment]
Thank you very much for the information.

I solved it with lossy Images for Android < 4.2.1

**Comment by coonmoo** [comment]
I'm not completly sure if not FFImageLoading causes some issues here.

I encoded all webp files not lossy without transparency.
I see some improvements here, but occassionally some images are still only partially displayed in CachedImage.

The reported issues:
https://bugs.chromium.org/p/webp/issues/detail?id=170
http://stackoverflow.com/questions/18842748/certain-webp-image-not-able-to-load-in-android-4 

state that the images get not loaded at all.

So maybe there is an issue in FFImageLoading?

**Comment by molinch** [comment]
Could you send me a few pics that cause trouble?
fabien.molinet AT gmail.com

**Comment by coonmoo** [comment]
Hello fabien,

the issue is definitely with pictures loaded from a webserver.

I created a new xamarin.forms project and added 2 CachedImage controls. One displaying the Image from a local file and one displaying the same Image loaded from the Server.

[Image](http://s7.postimg.org/9ci5m6mor/Screenshot_2016_02_09_14_14_29.png)

Code:
```
namespace ImageWebpTest
{
    using System;

    using FFImageLoading.Forms;

    using Xamarin.Forms;

    public class App : Application
    {
        public App()
        {
            var uri = new Uri("http://www27.online-convert.com/download-file/6ea211540e900e7c8b89f8c57fec724a/converted-f92e4295.webp");

            var img = new CachedImage { HeightRequest = 200 };
            img.Source = ImageSource.FromFile("imgwebp.webp");

            var cachedImg = new CachedImage { HeightRequest = 200 };
            cachedImg.Source = ImageSource.FromUri(uri);

            this.MainPage = new ContentPage { Content = new StackLayout { VerticalOptions = LayoutOptions.Center, Children = { img, cachedImg } } };
        }
    }
}
```

**Comment by molinch** [comment]
@coonmoo Sorry for the delay. Could you reupload the picture somewhere? The link no longer works.

**Comment by coonmoo** [comment]
@molinch thanks for looking into this issue.

Yeah the host only allows like 10times Access to the link.

I just uploaded the "webptest.webp" I sent you via mail through this formular: http://image.online-convert.com/convert-to-webp.

So when the below link expires you can upload it again.

Here is another link http://www24.online-convert.com/download-file/7935cd65a3a769c42ac186439e05d934/converted-c9066a69.webp

**Comment by molinch** [comment]
Ok I reproduce the issue on a Nexus 4 with Jelly Bean.

I confirm that it's related to your webp format: if I use a lossy webp then there's no issue.
[lossy.webp.zip](https://github.com/molinch/FFImageLoading/files/149286/lossy.webp.zip)

**Comment by coonmoo** [comment]
Thanks for looking into this.

But if it's an Encoding issue, why does "ImageSource.FromFile("imgwebp.webp");" perfectly load, whereas the ImageSource.FromUri fails?

**Comment by molinch** [comment]
I really don't know why from disk it works, the only thing I'm sure is that it's related to Android version.
I tested on 4.4 and Lollipop and it worked perfectly there.
