### ISSUE TITLE
8-digit CircleTransformation border color not works on iOS

### ISSUE THREAD

**Issue by tamasszadvari** [molinch/FFImageLoading#145]
The 6-digit works well on both iOS and Android, but the 8-digit works only on Android.
Would it be possible to use the Xamarin.Forms Color class instead of hex strings?

**Comment by daniel-luberda** [comment]
We cannot use Xamarin.Forms `Color` class because the library also works on pure iOS/Android/Windows. I'll try to add support for 8-digit hex colors on other platforms instead.

**Comment by tamasszadvari** [comment]
Oh, I see. Thanks, that would be awesome! It's pretty easy to convert Xamarin.Forms `Color` objects to hex color strings, so the 8-digit hex support is more than enough. :)
