### ISSUE TITLE
Crash on Android API15 & lower

### ISSUE THREAD

**Issue by OrcJMR** [molinch/FFImageLoading#146]
FFImageLoading.Droid/Views/ImageViewAsync.cs : 106
get_AdjustViewBounds is only introduced in API 16 (despite set being available since API 1), leading to a crash on API15 and lower.

It is easy to stub it by overriding set and storing a copy locally, but maybe there's a way to not actually need it on lower API levels.

**Comment by daniel-luberda** [comment]
It's a legacy code, we'll probably remove it completely soon. Meanwhile, I rolled back commit related to https://github.com/molinch/FFImageLoading/issues/138 as it doesn't fix the issue. It should be working fine again on API < 16.
