### ISSUE TITLE
Custom Scale not working (Zoom) on Android

### ISSUE THREAD

**Issue by chamamo** [molinch/FFImageLoading#148]
Hi,

I'm tryning to include this [class](https://gist.github.com/justintoth/10663869) in my project, it's a custom ImageView wich allow you to zoom (in/out).
It's not work when this class inherit from ImageViewAsync.
Did I missed something?

Thank you in advance.

**Comment by daniel-luberda** [comment]
It's a lot of code. I'll need some more details. 

BTW: FFImageLoading has a CropTransformation which allows you too zoom in/out image. Did you try it? All you need to do is to handle touch events. https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Droid/CropTransformation.cs

**Comment by molinch** [comment]
IMO the legacy code we removed could help.
@chamamo could you try with our nuget alpha?

**Comment by chamamo** [comment]
No need to update your code, I'm using ImageView inside ViewPager, The ViewPager was handling  the touch event before ImageView.
It work now, thank you very much.
Juste a question, LoadingPlaceholder and ErrorPlaceholder methods take a string parameter, can I use a resource Id? from drawable folder for exemple?

**Comment by daniel-luberda** [comment]
> Juste a question, LoadingPlaceholder and ErrorPlaceholder methods take a string parameter, can I use a resource Id? from drawable folder for exemple?

@chamamo You have to provide resource path eg. "Loading.png" (full paths are supported).
