### ISSUE TITLE
WebException when call CancelLoading 

### ISSUE THREAD

**Issue by chamamo** [molinch/FFImageLoading#149]
Hi,

I'm using ViewPager to show pictures, before destroy page I'm tryning to cancel image loading like this:

`
public override void DestroyItem(ViewGroup container, int position, Java.Lang.Object obj)
        {
            var view = (View)obj;
            var imageView = view.FindChild<SlgImageView>().FirstOrDefault();
            if (imageView != null)
            {
                imageView.CancelLoading();
            }

            base.DestroyItem(container, position, obj);
        }
`

And sometimes I have System.Net.WebEception "Aborted" 

What is he right way to cancel loading in my case?

**Comment by molinch** [comment]
These are handled exceptions so it shouldn't be an issue.

**Comment by molinch** [comment]
Please reopen in case you have an issue.
