### ISSUE TITLE
Encrypted images

### ISSUE THREAD

**Issue by mariusmuntean** [molinch/FFImageLoading#151]
Hi,

First of all thanks for the great work!

We're starting to use encrypted image files and we're wondering what the best way would be to allow some processing(decryption) of the downloaded images.

Ideally we could hook into the download and cache mechanism to receive a byte array of the downloaded data, process it and then return it to the cache to be persisted in plain-text.

A possible solution would be to allow developers to provide their own implementation of IDownloadCache, either when initializing FFImageLoading or through IoC. Btw, does FFImageLoading use IoC?

Another, less flexible but simpler solution, would be to allow developers to provide a function when initializing FFImageLoading, that performs some processing on the downloaded byte array and then returns it, e.g.  Func<byte[], byte[]>.

What do you think about this and do you already have plans to support a scenario where the images are encoded?

**Comment by molinch** [comment]
Good news! It's already possible to provide your own IDownloadCache.
Please have a look at https://github.com/molinch/FFImageLoading/wiki/Advanced-Usage

**Comment by mariusmuntean** [comment]
Hi Fabien,

Thanks for the quick reply.
I wasn't aware of that. After looking into it for a few minutes it seems indeed that it is possible to do exactly what we want.

For the record: Call `ImageService.Initialize(customConfig)`, where `customConfig `is an instance of [`Configuration`](https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Common/Config/Configuration.cs) that has a reference to a custom implementation of `IDownloadCache`.

Thank you again and from our point of view this issue can be closed.
