### ISSUE TITLE
Image Download Priority

### ISSUE THREAD

**Issue by joeforshaw** [molinch/FFImageLoading#153]
Hi there,

I have a view which contains a bunch of images, some on-screen, some off-screen accessible by scrolling through carousels. When images are being downloaded, I want to be able to prioritise the on-screen images and download those first, then the off-screen images.

Therefore I'd like to request some download priority system be implemented which allows me to accomplish such a goal. Apologies if this already exists and I've missed it in your docs.

Cheers.

**Comment by molinch** [comment]
It would not be that hard to add such a prioritization system, we could add an overload to all `ImageService.LoadXxx` methods which would allow an enum:

```c#
LoadingPriority
{
   Lowest = -1
   Low = -2,
   Normal = 0,
   High = 1,
   Highest = 2
}
```

Defaut value would be `Normal`
@daniel-luberda @joeforshaw What do you think about it?

**Comment by joeforshaw** [comment]
Sounds perfect.

**Comment by joeforshaw** [comment]
Would it be possible to pass the priority as an int instead of an enum? That way you would have a very fine grained approach to prioritising an image.

**Comment by daniel-luberda** [comment]
Yes, we should definitely implement it. I already mentioned about it here: #143 - it would be also very useful in that case. 

+1 for WithPriority() fluent method and LoadingPriority enum

**Comment by joeforshaw** [comment]
Perfect.

**Comment by molinch** [comment]
There is now an Alpha nuget that includes it:
https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/2.1.0-alpha1

Please note that this is NOT production ready but it allows to test the functionality.
Could you give us your feedback on it?
