### ISSUE TITLE
The images are not shown in MIUI 12.5 or later versions

### ISSUE THREAD

**Issue by gureAngel** [molinch/FFImageLoading#1548]
## 🐛 Bug Report

Images are displayed on all devices: iphone, android. But xiaomi phones with a version of MIUI equal or higher than 12.5 do not show any icon in svg.

### Expected behavior
Show icons in svg
### Reproduction steps
use a MIUI 12.5

**Version:** 2.4.11.982

**Platform:** 
- [ ] :iphone: iOS
- [x]  :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by 9evxxx** [comment]
I have the same problem, it happens when I select arm64-v8A

**Comment by 9evxxx** [comment]
> ## 🐛 Bug Report
> Images are displayed on all devices: iphone, android. But xiaomi phones with a version of MIUI equal or higher than 12.5 do not show any icon in svg.
> 
> ### Expected behavior
> Show icons in svg
> 
> ### Reproduction steps
> use a MIUI 12.5
> 
> **Version:** 2.4.11.982
> 
> **Platform:**
> 
> * [ ]  📱 iOS
> * [x]   🤖 Android
> * [ ]  🏁 WPF
> * [ ]  🌎 UWP
> * [ ]  🍎 MacOS
> * [ ]  📺 tvOS
> * [ ]  🐒 Xamarin.Forms

Add nuget SkiaSharp.Views.Forms

**Comment by gureAngel** [comment]
> > ## 🐛 Bug Report
> > Images are displayed on all devices: iphone, android. But xiaomi phones with a version of MIUI equal or higher than 12.5 do not show any icon in svg.
> > ### Expected behavior
> > Show icons in svg
> > ### Reproduction steps
> > use a MIUI 12.5
> > **Version:** 2.4.11.982
> > **Platform:**
> > 
> > * [ ]   📱 iOS
> > * [x]    🤖 Android
> > * [ ]   🏁 WPF
> > * [ ]   🌎 UWP
> > * [ ]   🍎 MacOS
> > * [ ]   📺 tvOS
> > * [ ]   🐒 Xamarin.Forms
> 
> Add nuget SkiaSharp.Views.Forms

Solved by updating the version of SkiaSharp.Views.Forms thank you very much.
