### ISSUE TITLE
MvxImageLoadingView auto ImageSource detection

### ISSUE THREAD

**Issue by xleon** [molinch/FFImageLoading#155]
`ImageSource` is needed as a previous step to load any image.
This is fine and a view will normally load the same image source type. But what happens if the type changes?

*The edge case:*
I found myself doing an avatar picker. When a pic is selected, it will load the image from a local file.
If the user save changes in the form, the image will upload to server and next time he/she opens up the screen it will load the avatar from internet. So the image source type can change from "file" to "url".
I could even want to load an embedded resource when the user image is not set yet.

In a mvvm scenario this is a bit tricky as you can´t simply bind `DataLocation`. 
My idea is to detect the source type automatically by examining the image path.

I certainly know that urls will start with "http". But I´m not sure about the rest of the source types.
For instance, in mvvvmcross, they solve this by adding "res:" prefix to embedded resources. 
I would prefer to use some kind of regex to infer the source type but at this point I´m not sure it can be done for all cases (need to investigate more)

**Comment by molinch** [comment]
It's a really good idea to have a new property like `AutoDataLocation` that would accept an Uri.
Then you could easily know which scheme is used (file, url, res, ...).

I'm happy to merge such a change :)

**Comment by xleon** [comment]
yeah, I need to read about all possible uri shemes and I´ll commit it.
That could be useful outside of "Mvx" as well

**Comment by molinch** [comment]
Yes that's true. The best would be to have a new `ImageService.LoadUri` method.
This method would invoke the corresponding methods (LoadFile, LoadUrl, ...) based on Uri scheme.

Then a new property, for example `MvxImageLoadingView.DataLocationUri`, would call it.

**Comment by xleon** [comment]
mmm schemes can be tricky. Look at this:

`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
9TXL0Y4OHwAAAABJRU5ErkJggg==`

**Comment by molinch** [comment]
Currently we don't handle Base64 encoded images, is this a need for you?

**Comment by xleon** [comment]
Not at all, but if we do a ImageService.LoadUrl() it would be cool, isn´t it?

**Comment by molinch** [comment]
it is indeed cool, but we should focus on what people will really use.
I would rather add new schemes if people ask for them on github

**Comment by xleon** [comment]
You are right.
I´ll handle the most common schemes then

**Comment by daniel-luberda** [comment]
Maybe it would help: 

- https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Forms.Droid/ImageSourceBinding.cs#L30-L58
- https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Forms.Touch/ImageSourceBinding.cs#L29-L58
- https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Forms.WinRT/ImageSourceBinding.cs#L36-L73

**Comment by daniel-luberda** [comment]
And the last one, most important as it's based on strings: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Windows/FFImageSourceBinding.cs#L19-L53

**Comment by xleon** [comment]
That will definitely help

**Comment by molinch** [comment]
@xleon Have you managed to do anything? If not I can also handle the rest of the task.

**Comment by xleon** [comment]
I´ve been very busy and just had time to implement this for my project needs. I could have something for the end of next week. If you want to go ahead, please let me know

**Comment by xleon** [comment]
Nothing really useful, but just in case... the "res:" prefix is coming from mvvmcross that I was using in some value converters

```
public string DataLocationUri
		{
			get { return _dataLocationUri; }
			set
			{
				_dataLocationUri = value;

				if (string.IsNullOrEmpty(_dataLocationUri)) return;

				if (_dataLocationUri.StartsWith("res:"))
				{
					var resourcePath = _dataLocationUri.Split(new[] { "res:" }, StringSplitOptions.None)[1];
					Source = ImageSource.CompiledResource;
					DataLocation = resourcePath;
				}
				else if (_dataLocationUri.StartsWith("http"))
				{
					Source = ImageSource.Url;
					DataLocation = _dataLocationUri;
				}
				else if (_dataLocationUri.StartsWith("/"))
				{
					Source = ImageSource.Filepath;
					DataLocation = _dataLocationUri;
				}
			}
		}
```

**Comment by molinch** [comment]
:+1: I will try to integrate it during the week

**Comment by bspinner** [comment]
What's the status on this, @molinch ?

**Comment by molinch** [comment]
Sorry for the delay. This is now done in master.
Furthermore the MvvmCross helper will now be shipped with Nuget packages.

@xleon would it suit you like this?

**Comment by molinch** [comment]
FFImageLoading 2.1.0-alpha2 nuget released which brings it by default in the lib.
If you have any problems, please write details here. Many thanks.

**Comment by Damian-Pumar** [comment]
Hi all, how to set LoadingPlaceholderPath and ErrorPlaceholderPath using MVVMCross ? 
Thanks!

**Comment by Cybrosys** [comment]
Question about the "res:"-prefix, why not check against "android.resource:" instead?

I've built a resource service that probes a list of providers if they know where a specific resource can be found, and the first one to answer returns a URI to that resource. The URI can be "android.resource", if the asset is embedded, it can be a path to a local file, or point to a http resource.

I've been googling for hours trying to find anything regarding a "res:" scheme in android but come up short.

**Comment by daniel-luberda** [comment]
@bspinner `MvxImageLoadingView` is `obsolete` now and replaced with `MvxCachedImageView`
