### ISSUE TITLE
How set Bitmap?

### ISSUE THREAD

**Issue by aghamohammadi** [molinch/FFImageLoading#159]
I can set bitmap, sample:

myImageView.setImageBitmap(bmp);

**Comment by molinch** [comment]
I don't understand your question

**Comment by aghamohammadi** [comment]
How can I set bitmap in FFImageLoading?
"normal sample" 
`       myImageView.setImageBitmap(bmp);`

"FFImageLoading sample" 
        ?????

**Comment by molinch** [comment]
Please have a look at the wiki page for FFImageLoading usage: https://github.com/molinch/FFImageLoading/wiki/API

The ImageViewAsync inherits from classic ImageView so everything works the same.

**Comment by aghamohammadi** [comment]
I Know This https://github.com/molinch/FFImageLoading/wiki/Android-API
and FFImageLoading work on Android images can be loaded from Internet, Resources, Assets or File.
BUT my qustion is, how set bitmap to FFImageLoading?? No FileUrl No Assets No Stream
No !!

**Comment by molinch** [comment]
FFImageLoading does not load from bitmap.

Therefore you can do that easily with standard Android Java. Have you already tried `imageView.SetImageBitmap()`?

**Comment by aghamohammadi** [comment]
tanks for replay, i went use FFImageLoading for lazyloading and fade but for set bitmap, i shoud use standard Android Java.
tanks
