### ISSUE TITLE
iOS Fading support

### ISSUE THREAD

**Issue by molinch** [molinch/FFImageLoading#16]
Currently fading is only implemented on Android. It could be very easily added to iOS.

Something like in SO accepted answer should be enough:
http://stackoverflow.com/questions/2834573/how-to-animate-the-change-of-image-in-an-uiimageview

**Comment by daniel-luberda** [comment]
https://github.com/daniel-luberda/FFImageLoading/commit/6111457ca0976657f26fec84e8295357f793b684

**Comment by molinch** [comment]
Done by @daniel-luberda
