### ISSUE TITLE
iOS7 support

### ISSUE THREAD

**Issue by RanaInside** [molinch/FFImageLoading#162]
Hi guys, first of all - thanks for a wonderful library; now I know ffimage iteself supports ios7, but the current nuget version downloads a WebP.dll which is built against iOS8; On my project, I have minimum SDK as 7.1, and it refuses to build.

Any suggestions?

**Comment by molinch** [comment]
I just did an alpha Web.Touch package: https://www.nuget.org/packages/WebP.Touch/1.0.2-alpha
Could you try to build using it?

**Comment by RanaInside** [comment]
Hi molinch, thanks for your reply; I have actually managed to solve it. There were two issues: first minimum SDK, and the other one was missing ARMv7s; I have XCode 7, so I had to manually add the missing architecture and then build;

Sorry that I forgot to mention about the arc. before. Does your build have that?

**Comment by molinch** [comment]
I am glad you managed to do it. It would be awesome if you could make a PR with your changes: https://github.com/molinch/WebP.Touch

Yes ARC should be enabled: https://github.com/molinch/WebP.Touch/search?utf8=%E2%9C%93&q=CLANG_ENABLE_OBJC_ARC

**Comment by RanaInside** [comment]
Hi molinch, done;

**Comment by molinch** [comment]
Thanks @RanaInside 
New nuget uploaded: https://www.nuget.org/packages/WebP.Touch/
