### ISSUE TITLE
Use the library as an image resizer?

### ISSUE THREAD

**Issue by toverux** [molinch/FFImageLoading#165]
Hello,

I let my users change their profile image via the camera gallery and device. Since the upload is directly done to Azure (without transiting by our servers) I need to resize images on the client side.

According to the docs, the Downsampling properties are resizing the image to consume less memory. And since there is a `GetImageAsJpgAsync()`, I thought that I could use a  non-displayed CachedImage to resize the camera image :

```csharp
var downsampledImage = new CachedImage {
	Source = ImageSource.FromStream(() => media.GetStream()),
	DownsampleHeight = 128
};

var jpgBytes = await downsampledImage.GetImageAsJpgAsync(); // exception occurs here

await blockBlob.UploadFromByteArrayAsync(jpgBytes, 0, jpgBytes.Length);
```

But I get a not-so-helpful `NullReferenceException` on the `GetImageAsJpgAsync` line. I think the error comes from the library? Am I using it bad?

**Comment by PaulARoy** [comment]
I completely backup this request!

I tried the same thing and got the `NullReferenceException`, probably because the view was not rendered.

My solution was to create a dedicated service `ImageResizer` thanks to this forum post:

**Comment by daniel-luberda** [comment]
You must call `var jpgBytes = await downsampledImage.GetImageAsJpgAsync();` in a `OnSuccessCommand` or `OnSuccess` event (after it's loaded).

BTW: image resizer (cropping) example here:
https://github.com/molinch/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/CropTransformationPage.cs
https://github.com/molinch/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/PageModels/CropTransformationPageModel.cs

**Comment by PaulARoy** [comment]
@daniel-luberda I tried many things, including the `OnSuccess` but I was not able to achieve this.

Note: I created a CachedImage that was not included in any view and tried to downsample it.

I think the element has to be renderer somehow ?

**Comment by daniel-luberda** [comment]
Yes, it has to be rendered. Other operations are better suited for another dedicated library. Eg. https://github.com/JimBobSquarePants/ImageProcessor

**Comment by PaulARoy** [comment]
:+1: 

Good suggestion.
It might be a plus to be able to do this but I understand why you consider this out of scope.

**Comment by toverux** [comment]
> You must call var jpgBytes = await downsampledImage.GetImageAsJpgAsync(); in a OnSuccessCommand or OnSuccess event (after image is loaded).
I tried, but it seems that the event is not fired when the source is a Stream.
Thank you for you help, since I don't want the image to be rendered, I will use a specialized library.

**Comment by daniel-luberda** [comment]
Thanks!

**Comment by molinch** [comment]
Just a side note: with upcoming 2.1 this might be possible.
Target and Loading task are decoupled, it means that you will be able to do anything.

**Comment by SarathVee** [comment]
I'm developing Xamarin mobile application so for i need capture image and performing Auto edge detection on Image also giving image enhancement like Lightning the Cropped image,any help to complete it.
