### ISSUE TITLE
RecyclerView problems

### ISSUE THREAD

**Issue by c1rus** [molinch/FFImageLoading#17]
Hi, I was trying latest version from nuget in RecyclerView.

I have this code in OnBindViewHolder

```
ImageService.LoadUrl("http://files.usvit.alejtech.eu/peto/6480947_xl.jpg")
   .Retry(3, 200)
   .DownSample(100, 100)
   .LoadingPlaceholder(Constants.LoadingPlaceholderPath, FFImageLoading.Work.ImageSource.ApplicationBundle)
   .ErrorPlaceholder(Constants.ErrorPlaceholderPath, FFImageLoading.Work.ImageSource.ApplicationBundle)
   .Into(vh.Image);
```

1. on first load first row looks like this:

![2015-05-04_1902](https://cloud.githubusercontent.com/assets/11233730/7457954/91159d66-f290-11e4-99fd-554738b1380a.png)

2. when i scroll up and down, some ImageViews are suddenly blank

![2015-05-04_1902_001](https://cloud.githubusercontent.com/assets/11233730/7457957/971498c0-f290-11e4-92fb-239915458e03.png)

**Comment by molinch** [comment]
Mmh very weird. Do you have anything special in console?

**Comment by c1rus** [comment]
No :(

Not related with this issue, but i think that method GetStreamAsync should have a null check:
```
if (string.IsNullOrEmpty(path)) return null;
```

**Comment by molinch** [comment]
Updated sample from c1rus is here https://github.com/c1rus/ImageLoading.Sample

**Comment by molinch** [comment]
Could you tell me what is your latest Android SDK installed and also latest Android support library installed?

**Comment by molinch** [comment]
I'm almost 99% sure it's not a FFImageLoading bug.
I debugged and when cells are empty they didn't went into OnBindViewHolder... So something else looks wrong to me

**Comment by molinch** [comment]
When using standard ImageView instead of our ImageViewAsync I don't seem to have this issue. Even though that's quite strange, I will make additional tests.

**Comment by c1rus** [comment]
hmm, we are not only ones with that issue :)

http://stackoverflow.com/questions/29564824/recyclerview-disappearing-images

**Comment by molinch** [comment]
Yeah it's really weird... Basically RecyclerView seems to sometimes detach images so it calls ImageView.OnDetachedFromWindow(), and in our case we clear the drawable, but sometimes it won't go again in OnBindViewHolder()

**Comment by molinch** [comment]
Fixed by https://github.com/molinch/FFImageLoading/commit/f806962806960f144663c271fe622f5e09cf555b?w=1

A new NuGet is also out there. It contains minor other improvements.

**Comment by molinch** [comment]
One remark though: it could be nice to have your updated sample in this project.

**Comment by c1rus** [comment]
thx, i will create PR later.

blank cells are solved, but this issue is still there. 

![2015-05-05_1134](https://cloud.githubusercontent.com/assets/11233730/7470243/730eeae4-f31b-11e4-95f8-83eabd15eb7a.png)

**Comment by c1rus** [comment]
and one more thing :) can we get rid of flickering?

ffimageloading -> http://screencast.com/t/QOrtHbfjn
```
ImageService.LoadUrl("http://files.usvit.alejtech.eu/peto/6480947_xl.jpg")
   .Retry(3, 200)
   .DownSample(100, 100)
   .LoadingPlaceholder(Config.LoadingPlaceholderPath, FFImageLoading.Work.ImageSource.ApplicationBundle)
   .ErrorPlaceholder(Config.ErrorPlaceholderPath, FFImageLoading.Work.ImageSource.ApplicationBundle)
   .Into(vh.Image);
```

picasso -> http://screencast.com/t/i7OkWvQpksOH
```
var uri = Android.Net.Uri.Parse("http://files.usvit.alejtech.eu/peto/6480947_xl.jpg");
Squareup.Picasso.Picasso.With(context).Load(uri).Fit().Placeholder(Resource.Drawable.placeholder).Into(vh.Image);
```

**Comment by molinch** [comment]
Issue with image is weird but I should be able to find what happens.

Regarding flickering can you tell me your simulator settings? I don't experience it on my side, even with a low hardware device.

**Comment by c1rus** [comment]
Genymotion - Google Nexus 5 - 5.1.0 - API 22 - predefined settings

slow pc or am i scrolling fast? :)

**Comment by molinch** [comment]
Same configuration but still not that issue.
Anyway I refactored a bit some code so now when loading from memory cache it skips many things (and should be of course faster).
I won't make a NuGet for this unless heavily tested. Could you give me some feedback?
It is in this commit https://github.com/molinch/FFImageLoading/commit/2247205153da253c84b751eff45100a0301cc86d?w=1

**Comment by c1rus** [comment]
awesome, no flickering now :)

but i think something has broken, try run the sample and you will see.

http://screencast.com/t/ERMzONpgg5

**Comment by molinch** [comment]
Hi @c1rus this should be fixed now

**Comment by c1rus** [comment]
yes, it is fixed, thank you.

i have noticed that the sample is crashing, when url (path) is null or empty.
i can always manually check, but i want to show the placeholder, so maybe the library should handle it. What do you think?

```
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.Exception: Image loading key can not be null, empty or a whitespace
```

**Comment by molinch** [comment]
I'm very busy now but if you make a PR I would be happy to integrate it

**Comment by c1rus** [comment]
PR created, i'm just not sure if it should be considered as error.

Maybe there should be 3 kinds of placeholders :)

EmptyPlaceholder
LoadingPlaceholder
ErrorPlaceholder

or when the path is empty, show LoadingPlaceholder.
