### ISSUE TITLE
FFImageLoading and UWP issue

### ISSUE THREAD

**Issue by alexandrMykhailov** [molinch/FFImageLoading#171]
Hello!
I have Xamarin Forms app for Android and iOS, I`d like to add UWP version.
So I add UWP project, download nugets and when I launch app I have an exception:
Activated	Event	Time	Duration	Thread
	Exception thrown: 'System.MethodAccessException' in Hubber.dll ("Attempt by method 'Hubber.View.ProfilePage+<InitializeComponent>_anonXamlCDataTemplate_8.LoadDataTemplate()' to access method 'FFImageLoading.Forms.ImageSourceConverter..ctor()' failed.")	428.78s		[4700] <No Name> 

Can you help me, please? :)

**Comment by daniel-luberda** [comment]
@xleon  Should be fixed now. Thanks.

**Comment by molinch** [comment]
FFImageLoading 2.1.0-alpha2 nuget released which brings this fix.
If you have any problems, please write details here. Many thanks.
