### ISSUE TITLE
Build Process?

### ISSUE THREAD

**Issue by ravensorb** [molinch/FFImageLoading#174]
I was looking to make a few changes and submit a PR only issue is, I am running into build issues (254 to be exact)

Ex
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		'Allow unsafe code' is not supported by one or more of the project's targets.	FFImageLoading.Windows	E:\Projects\FFImageLoading\source\FFImageLoading.Windows\FFImageLoading.Windows.csproj	0	
```
or

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'ImageService' does not contain a definition for 'InvalidateDiskCache'	ListView.Universal.Sample	E:\Projects\FFImageLoading\samples\ListView.Universal.Sample\MainPage.xaml.cs	40	Active
```

Another thing I noticed is that the nuspec files are looking for assemblies that do not exist.  Are you in the process of renaming things?  Example: the FFImageLoading.Windows project creates an assembly called FFImageLoading.Platform (so does the project FFImageLoading.WinSL)

**Comment by ravensorb** [comment]
Any help here?  I was really hoping to use this library however from what I can tell, it looks like it is in the middle of some refactoring (very little compiles or runs)

**Comment by daniel-luberda** [comment]
Hi @ravensorb Yes, there are some refactorings pending. I was not available for some time, sorry for that. I'll push new commits today or tomorrow. Then, all you'll need to build is MakeFile and it should build just fine.

**Comment by daniel-luberda** [comment]
@ravensorb It should build now. If something doesn't work feel free to reopen the issue. 

Some additional info: 

There's a `MakeFile` support, so you only need to run `make` command from source directory and it will build all projects (from mac). For building additional Windows files you can use `MakefileWindows.bat`. To generate nuget packages just use `make package`

**Comment by ravensorb** [comment]
Does the Visual Studio solution build process work?

**Comment by daniel-luberda** [comment]
@ravensorb Yes, it should build fine. Just one note: Use `Release` configuration for Common/Android/iOS, then `Windows Release` for Windows specific projects.
