### ISSUE TITLE
Unable to convert instance of imageview to type FFImageLoading.Views.ImageViewAsync

### ISSUE THREAD

**Issue by rusty21** [molinch/FFImageLoading#176]
I'm running in the Beta channel of Xamarin and we just received an update today to xamarin studio 6 as well as a bunch of other updates. Now when I run my Android project I get this error:
A System.InvalidCastException was thrown.
Unable to convert instance of type 'Android.Widget.ImageView' to type 'FFImageLoading.Views.ImageViewAsync'.

Granted, I'm not in the stable channel but if the problem finds its way into the stable channel then I will have a huge problem because I won't be able to run any of my android apps. I don't know if this is a problem with FFImageLoading, or its a problem with the update to Xamarin.Android or Mono or what but could you please take a look at it.

**Comment by daniel-luberda** [comment]
@rusty21 I'll make a nuget compiled with XF Alpha soon and do some tests. Do you have any reproduction?

**Comment by rusty21** [comment]
I assume by "Do you have any reproduction?" means can I reliably reproduce this. Like I said all i did was  open an existing project that used FFImageloading go into Xamarin studio on my Mac and install everything in the beta branch. After installing I get the error. Installing everything in the stable branch causes the error to go away. I actually attempted going into the alpha branch about 2 weeks ago to try out xamarin 6 before it came to the beta branch and the same problem occurred so I had to switch back.

**Comment by daniel-luberda** [comment]
@rusty21  Please try newest 2.1.0-alpha2. Can you still reproduce it?

**Comment by rusty21** [comment]
Yes the problem still occurs.

**Comment by molinch** [comment]
@rusty21 Could you go in XS>About>Show details and post your configuration?

**Comment by rusty21** [comment]
=== Xamarin Studio Business ===

Version 6.0 (build 5104)
Installation UUID: 33b02efd-12be-454b-bef5-7609235ddcad
Runtime:
	Mono 4.4.0 (mono-4.4.0-branch/81f38a9) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 404000142

=== Xamarin.Profiler ===

Version: 0.31.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 7.3 (10183.3)
Build 7D175

=== Xamarin.iOS ===

Version: 9.8.0.294 (Xamarin Business)
Hash: 6950f7b
Branch: cycle7
Build date: 2016-04-24 15:35:14-0400

=== Xamarin.Android ===

Version: 6.1.0.48 (Xamarin Business)
Android SDK: /Users/rusty21/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.2   (API level 17)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)

SDK Tools Version: 25.1.1
SDK Platform Tools Version: 23.1
SDK Build Tools Version: 23.0.3

Java SDK: /usr
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Android Player ===

Not Installed

=== Xamarin.Mac ===

Version: 2.8.0.294 (Xamarin Business)

=== Build Information ===

Release ID: 600005104
Git revision: 1345d355d4f1b9677d91e1290a6034e2047bdf36
Build date: 2016-04-26 12:21:45-04
Xamarin addins: 7d85147c75b6dbb4b351906636ef76fdf60307c2
Build lane: monodevelop-lion-cycle7

=== Operating System ===

Mac OS X 10.11.4
Darwin rustys-MacBook-Pro.local 15.4.0 Darwin Kernel Version 15.4.0
    Fri Feb 26 22:08:05 PST 2016
    root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

**Comment by rusty21** [comment]
I just ran this simple test in the C# interactive in visual studio
```
public class BaseClass
{
    public string BaseProperty { get; set; }
}
public class SubClass : BaseClass
{
    public string SubProperty { get; set; } 
}
var baseClass = new BaseClass();
var sub = (SubClass)baseClass;
```

This error gets thrown
`Unable to cast object of type 'BaseClass' to type 'SubClass'.`

As you can see I attempted to new up a base class then cast it so a sub class. This obviously failed. You guys are attempting to do the same thing. Going from ImageView to ImageViewAsync probably isn't going to work anymore. Not sure why it ever did work to be honest with you. We may have to stop putting ImageViews in our axml files and start putting ImageViewAsyncs there instead.

**Comment by molinch** [comment]
Now I start understanding.
So you use `ImageView`in your axml files and not `ImageViewAsync`?

**Comment by rusty21** [comment]
Yes just as I always have and it was working just fine.

**Comment by molinch** [comment]
TBH I have no idea how it worked so far for you :)
Yes it is mandatory to use `ImageViewAsync` on Android:  https://github.com/molinch/FFImageLoading/wiki/Android-API#imageviewasync

**Comment by rusty21** [comment]
What is the xaml definition for an imageviewasync object?

**Comment by rusty21** [comment]
For anyone who cares it looks like this
```
<ffimageloading.view.ImageViewAsync
    /*Properies*/
/>
```
What sucks is now in all my views I see this massive grey blobs...

I attempted this but it never worked, so if anyone can tell me why or how I could make it work that would be appreciated.
```
<ImageView
    class="ffimageloading.view.ImageViewAsync"
    /*Properies*/
/>
```

**Comment by molinch** [comment]
I will check and come back to you if I find anything.

**Comment by vackup** [comment]
The lastes prebuilt app from xamarin called Acquaint (https://www.xamarin.com/prebuilt) has the same issue when opened with the beta channel

**Comment by molinch** [comment]
@vackup Yes you are right Acquaint.Native uses FFImageLoading. Therefore it is not an FFImageLoading issue but a code issue in Acquaint.Native: an ImageView is defined in AXML and an ImageViewAsync is used in code.

I submit a PR: https://github.com/xamarinhq/app-acquaint/pull/3

**Comment by vackup** [comment]
so ImageView and ImageViewAsync are not compatible? just asking... why i could be working in previous version?

Thanks!

**Comment by molinch** [comment]
ImageViewAsync inherits from ImageView, hence the compatibility.

So you cast an ImageViewAsync to an ImageView.
But the opposite is not possible, which was the issue in this case.

In previous version of Xamarin it worked, even though it shouldn't have, it was already an issue.

**Comment by robjens** [comment]
Make that `FFImageLoading.Views.ImageViewAsync` here, capitalization matters to visual studio intellisense at least, before with all lower caps it would point at the parent LinearLayout not knowing this type child.
