### ISSUE TITLE
ImageService.LoadBitmap(Android.Graphics.Bitmap bitmap) method would be really useful.

### ISSUE THREAD

**Issue by msivers** [molinch/FFImageLoading#178]
I have a scenario (Android project) where I have bitmaps and would like to create an ImageViewAsync from the existing bitmap rather than having to use a path or url to an image. This seems like a useful addition to the library? It would also be great to be able to define a placeholder or error image from a bitmap irrespective of how the main image is being loaded.

**Comment by daniel-luberda** [comment]
@msivers FFImageLoading uses its own bitmap drawable subclass internally for performance / memory optimizations and it's not compatible with existing generic ones. You can use Stream image sources instead. Look here: https://github.com/molinch/FFImageLoading/tree/master/source/FFImageLoading.Droid/Drawables
