### ISSUE TITLE
On Xamarin.Forms after update to pre version:2.2.0.5-pre2  Android project fail to build

### ISSUE THREAD

**Issue by lecnierfreeman** [molinch/FFImageLoading#180]
After updating Xamarin.Forms to the latest prerelease version IOS project builds but Android doesn't an all error are related to FFImageLoading  library. Maybe the cause is because in Xamarin.Forms they update the dependencies to Xamarin.Android.Support.(v4, v7, Design) to 23.1.1.1 and there they changed things  ?
These are **39 errors** if **Xamarin.FFImageLoading** and **Xamarin.FFImageLoading.Forms**,
 version **2.1.0-alpha1** are included in project for Android: 

'Resource.Attribute' does not contain a definition for 'mediaRouteSettingsDrawable'		257	
'Resource.Dimension' does not contain a definition for 'design_tab_min_width'		538	
'Resource.Dimension' does not contain a definition for 'dialog_fixed_height_major'		539	
'Resource.Dimension' does not contain a definition for 'dialog_fixed_height_minor'		540	
'Resource.Dimension' does not contain a definition for 'dialog_fixed_width_major'		541	
'Resource.Dimension' does not contain a definition for 'dialog_fixed_width_minor'		542	
'Resource.Dimension' does not contain a definition for 'mr_media_route_controller_art_max_height'		
'Resource.Drawable' does not contain a definition for 'ic_setting_dark'		636	
'Resource.Drawable' does not contain a definition for 'ic_setting_light'		637	
'Resource.Drawable' does not contain a definition for 'mr_ic_settings_dark'		648	
'Resource.Drawable' does not contain a definition for 'mr_ic_settings_light'		649	
'Resource.Id' does not contain a definition for 'art'		669	
'Resource.Id' does not contain a definition for 'buttons'		673	
'Resource.Id' does not contain a definition for 'default_control_frame'			688	
'Resource.Id' does not contain a definition for 'disconnect'			690	
'Resource.Id' does not contain a definition for 'media_route_control_frame'			715	
'Resource.Id' does not contain a definition for 'media_route_list'			716	
'Resource.Id' does not contain a definition for 'media_route_volume_layout'			717	
'Resource.Id' does not contain a definition for 'media_route_volume_slider'			718	
'Resource.Id' does not contain a definition for 'play_pause'			728	
'Resource.Id' does not contain a definition for 'route_name'			733	
'Resource.Id' does not contain a definition for 'settings'			749	
'Resource.Id' does not contain a definition for 'stop'			762	
'Resource.Id' does not contain a definition for 'subtitle'			764	
'Resource.Id' does not contain a definition for 'title_bar'			771	
'Resource.Layout' does not contain a definition for 'mr_media_route_chooser_dialog'			819	
'Resource.Layout' does not contain a definition for 'mr_media_route_controller_material_dialog_b'			
'Resource.Layout' does not contain a definition for 'mr_media_route_list_item'			821	
'Resource.String' does not contain a definition for 'mr_media_route_button_content_description'			
'Resource.String' does not contain a definition for 'mr_media_route_chooser_searching'			
'Resource.String' does not contain a definition for 'mr_media_route_chooser_title'			857	
'Resource.String' does not contain a definition for 'mr_media_route_controller_disconnect'			
'Resource.String' does not contain a definition for 'mr_media_route_controller_no_info_available'			
'Resource.String' does not contain a definition for 'mr_media_route_controller_pause'			860	
'Resource.String' does not contain a definition for 'mr_media_route_controller_play'			861	
'Resource.String' does not contain a definition for 'mr_media_route_controller_settings_description'			
'Resource.String' does not contain a definition for 'mr_media_route_controller_stop'			863	
'Resource.Style' does not contain a definition for 'RtlOverlay_Widget_AppCompat_ActionButton_Overflow'	
'Resource.Styleable' does not contain a definition for 'FloatingActionButton_android_background'

**Comment by daniel-luberda** [comment]
@lecnierfreeman Hi, it's not FFImageLoading issue. Read more here: https://forums.xamarin.com/discussion/63983/xamarin-forms-2-2-0-pre2-released

> Important notes
> When upgrading Xamarin.Forms take care not to simply "update all" as that will update the Xamarin.Android.Support packages to an incompatible version. More info here: https://developer.xamarin.com/guides/xamarin-forms/troubleshooting/

You must use 23.1.1.1 support packages.

**Comment by vsarnataro** [comment]
so we wait that FFImageLoading library support 23.1.1.1 version?

**Comment by daniel-luberda** [comment]
@vsarnataro It's not FFImageLoading issue. It applies to prerelease version of Forms nuget package. Just be sure your support packages are correct version.

**Comment by lecnierfreeman** [comment]
@daniel-luberda Hi,

Sorry to say that in indeed it's a FFImageLoading issue, but I think is an easy one, since in this new pre-release version of Xamarin.Forms they moved to Xamarin.Android.Support.v4(and Friends) to version 23.1.1.1 all you need to do is just re-build the nugget packages with that version.

For confirming that it's a FFImageLoading I tried removing all packages from my project, install lates pre-release of Xamarin.Forms 2.2.0.5-pre2, install again all packages that I was using except FFImageLoading and try to build, and It succeeded, then Add  FFImageLoading and try to build, it failed with the errors I posted before. 
After that I created a new project, installed Xamarin.Forms 2.2.0.5-pre2, build succeeded, install FFImageLoading and Failed again.
I was reading in the same post you point it out and people says they are having this issues with 3rd party libs that need to update their Xamarin.Android.Support.v4(and Friends) to version 23.1.1.1

Thank You

**Comment by molinch** [comment]
@daniel-luberda Should we do anything?

**Comment by daniel-luberda** [comment]
@molinch  It should be fixed in 2.1.0-alpha2

**Comment by molinch** [comment]
FFImageLoading 2.1.0-alpha2 nuget released which brings this fix.
If you have any problems, please write details here. Many thanks.
