### ISSUE TITLE
Question: Image Clicking support in Xamarin Forms?

### ISSUE THREAD

**Issue by jasonCodesAway** [molinch/FFImageLoading#181]
It's rather common to use an image as a button or let it be clickable (e.g. viewing profile pics, clicking/tapping an image opens it), is there any MVVM support for that (existing or planned)? I.e. `<CachedImage ClickedCommand="{Binding LoginCommand}" Source="{Binding LoginImageSource}"/>`

**Comment by daniel-luberda** [comment]
Hi @jasonCodesAway It's already possible using standard GestureRecognizers: 
```XML
<ffimageloading:CachedImage Source="{Binding LoginImageSource}">
	<ffimageloading:CachedImage.GestureRecognizers>
		<TapGestureRecognizer Command="{Binding LoginCommand}"/>
	</ffimageloading:CachedImage.GestureRecognizers>
</ffimageloading:CachedImage>
```

**Comment by jasonCodesAway** [comment]
Hi Daniel. Sorry for taking a while to respond, I was on travel. I've seen the gesture recognizers approach but was hoping for the more modern 1-liner (like MR.Gestures or XamSvg). The above turns one line into 5, spreading that over all the XAML is one heck of an eye-sore.
