### ISSUE TITLE
Android: device log shows a lot of [ReuseBitmapDrawableCache] not coming through the FF logger

### ISSUE THREAD

**Issue by softwaremills** [molinch/FFImageLoading#184]
So on Android, in my Application Output window when I'm scrolling my RecyclerView, I'm seeing a lot of this:

```
[ReuseBitmapDrawableCache] Cache hit
[ReuseBitmapDrawableCache] Cache hit
[ReuseBitmapDrawableCache] OnEntryAdded(key = https://xxx.vo.msecnd.net:443/yyy/zzz;CircleTransformation,borderSize=0,borderHexColor=)
[ReuseBitmapDrawableCache] Cache hit
[ReuseBitmapDrawableCache] Cache hit
[ReuseBitmapDrawableCache] Cache hit from reuse pool
[ReuseBitmapDrawableCache] Cache hit from reuse pool
[ReuseBitmapDrawableCache] Cache hit
[ReuseBitmapDrawableCache] Cache hit
```

This happens even though I've redirected the logger to a logger that doesn't log to the console. Any chance we could get those messages to go through the FF standard logger?

**Comment by molinch** [comment]
You are right these should be debug info and not be in the release.
I will check it.

**Comment by molinch** [comment]
FFImageLoading 2.1.0-alpha2 nuget with Xamarin.Forms 2.2.0.31 support released.If you have any problems, please write details here. Thanks.
