### ISSUE TITLE
Drawing cache of async image colors problem

### ISSUE THREAD

**Issue by nvasilescu** [molinch/FFImageLoading#22]
![imageloadedfromgallery](https://cloud.githubusercontent.com/assets/4938117/8144116/9d1fb182-11d5-11e5-8201-1c9b44b16061.jpg)
This is when I select it from the gallery. 

This is when it gets saved http://files.parsetfss.com/fc4a96e8-ee74-417b-8107-6728e9dec97b/tfss-36d24d3e-1795-4166-b24e-544d8b3c02fd-profilePic.jpeg

-- > layout
<FFImageLoading.Views.ImageViewAsync
            android:layout_width="80dp"
            android:layout_height="80dp"
            android:src="@drawable/defaultprofilepic"
            android:background="@android:color/transparent"
            android:layout_marginTop="10dp"
            android:layout_marginLeft="10dp"
            android:id="@+id/profilePic" />

--> on activity result from gallery pic selection

ImageService.LoadFile(GetPathToImage(data.Data)).DownSample(width: 150)
						.Success(() =>
							{
								// your code here...

								loadedPicPath = GetPathToImage(data.Data) ;
								Console.WriteLine("image loading succes");
								profilePic.SetScaleType (ImageView.ScaleType.CenterCrop);
								profilePic.DrawingCacheEnabled  = true ;
								profilePic.BuildDrawingCache(true);

							})
						.Error(exception =>
							{
								// your code here...
								Console.WriteLine("image loading failed");
							})
						.Into(profilePic)

						;

--> converting it for server saving

Bitmap bitmap = profilePic.GetDrawingCache (true);

					MemoryStream stream = new MemoryStream();
					bitmap.Compress(Bitmap.CompressFormat.Jpeg, 80, stream);
					byte[] bitmapData = stream.ToArray();

					ParseFile file = new ParseFile(string.Concat("profilePic.jpeg"), bitmapData);
					await file.SaveAsync();

					userDetails["profilePicture"] = file;

**Comment by molinch** [comment]
Hi, are you able to upload a repro sample somewhere?
We have a samples solution, if you want you can fork the repository for example and put your stuff there.

**Comment by nvasilescu** [comment]
http://nvasilescu.net/FFImageDrawingCache.zip

I can't figure out how to preserve the samples and being able to make a folder with the files that are able to compile, and the github desktop is not working as it should so here's a zip. 

You browse for a picture, then press the 2nd button after the pic loads from device.

**Comment by nvasilescu** [comment]
https://bitbucket.org/nvasilescu/ffimagedrawingcache/src/6eb51169ca2f04342c22fcc15cece597d35be9d8?at=master

This client worked.

**Comment by nvasilescu** [comment]
Do you have any ideea why this is happening ?

**Comment by molinch** [comment]
Hi, next week I will work on it

**Comment by nvasilescu** [comment]
Can I help ? Do you have any ideea where should I look? I use the library for saving pictures to a database and it's a deal breaker for me, but I wouldn't want to change the picture loading library.

Thank you.

**Comment by molinch** [comment]
This issue comes from your call:
<pre>Bitmap bitmap = profilePic.GetDrawingCache (true);</pre>
Especially the autoscale parameter seems to mess with the image.
Please note that this topic is in no way related to our lib.

What I suggest you is to take the ImageView's Drawable. Please note that in our case it's always a BitmapDrawable, so casting is safe. Then you have a Bitmap property in the BitmapDrawable instance.

**Comment by molinch** [comment]
Is this OK for you @nvasilescu ? I would like to close the issue

**Comment by nvasilescu** [comment]
bitmap gets drawned correctly. Thank you.  Do you want me to submit the sample for you to update after I fork your library ?

**Comment by molinch** [comment]
I think it's OK we already have some Android samples but thanks for proposing @nvasilescu !
