### ISSUE TITLE
How can you add this to your project?

### ISSUE THREAD

**Issue by mwillebrands** [molinch/FFImageLoading#23]
I cant add it to a PCL or IOS project.. What do you need?

**Comment by molinch** [comment]
Have you tried the NuGet packages?

**Comment by mwillebrands** [comment]
Yes, tried adding them on every project, but none are compatible
Op 27 jul. 2015 09:36 schreef "Fabien Molinet" <notifications@github.com>:

**Comment by molinch** [comment]
Are you using Xamarin Studio on a Mac, or Visual Studio with the Xamarin plugin?

**Comment by mwillebrands** [comment]
When adding to a PCL the following error exists:
Could not install package 'Xamarin.FFImageLoading 1.1.3'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

When adding toa IOS project the following error exists:
Could not install package 'Xamarin.FFImageLoading 1.1.3. You are trying to install this package into a project that targets 'Monotouch,Version=v1.0' but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Adding to an Android project works!

**Comment by molinch** [comment]
I'm pretty sure you are using a "Xamarin iOS Classic API" project. Classic API is obsolete now.
Could you try with a "Xamarin iOS Unified API" project one?

**Comment by mwillebrands** [comment]
Yes we are, thanks for the info! I'll try it out.

**Comment by molinch** [comment]
Can you confirm me I can close the issue ?

**Comment by molinch** [comment]
I close this since there is no bug. If you have any other issue please create a new one.
Thanks

**Comment by mwillebrands** [comment]
I've just got back from my holliday, and will have a try tomorrow. Thanks for all the help!

**Comment by mwillebrands** [comment]
Works with the Unified api!

**Comment by molinch** [comment]
Great! :)
