### ISSUE TITLE
Way to create a custom caching key for an image

### ISSUE THREAD

**Issue by robbederks** [molinch/FFImageLoading#25]
Hello,

I'm using your loader in our app, and so far I really like it. The only problem I have with it is that on the end of our images, a 'random' security token has to be added to request the image from our server. Unfortunately, due to this difference in URL, the image is cached over and over again.
Would it be possible to have some kind of extra parameter to specify a caching key (in our case the url without the security token)?

Thank you!
Robbe

**Comment by molinch** [comment]
I would suggest customizing the DownloadCache: https://github.com/molinch/FFImageLoading/blob/master/FFImageLoading.Shared/Cache/DownloadCache.cs

We could have an optional parameter "key" that could be:
- when not specified the same as the url
- otherwise it would be used, and in your case it could be the URL without the security token?

I don't know if this would suit your needs?

**Comment by robbederks** [comment]
Yes, I think that would be the correct way to handle this. I think it would be nice if there was some kind of 'parameter' like the transforms, something like:
ImageService.LoadUrl(requestUrl).SetKey(cleanUrl).Into(imageView)

**Comment by molinch** [comment]
Now added in branch custom-cache-key https://github.com/molinch/FFImageLoading/commit/84f0a4b857bb34b162e285927f3e758d6ab23689

It will be merged soon.

**Comment by molinch** [comment]
It would be great @daniel-luberda if you could add CachedImage support

**Comment by daniel-luberda** [comment]
Great! Nice work :) I'll add key support soon (for CachedImage and FFImage).

**Comment by daniel-luberda** [comment]
https://github.com/molinch/FFImageLoading/commits/custom-cache-key

**Comment by molinch** [comment]
Very cool :+1: Thanks @daniel-luberda

**Comment by daniel-luberda** [comment]
Docs for Forms: https://github.com/molinch/FFImageLoading/wiki/Xamarin.Forms-Advanced#custom-cache-key

**Comment by molinch** [comment]
Merged
