### ISSUE TITLE
add hook for processing downloaded file (e.g. SVG) into drawable image

### ISSUE THREAD

**Issue by kenkyee** [molinch/FFImageLoading#27]
Wish there were a hook to process a file into a drawable image that can be processed by the rest of the pipeline...e.g., to include XamSvg so you can load an SVG into an image...

**Comment by molinch** [comment]
You can either inherit from ImageLoaderTask or implement IImageLoaderTask interface.

**Comment by molinch** [comment]
Have you been able to do it?

**Comment by molinch** [comment]
Closing since this won't be done in FFImageLoading and a solution has been proposed.
