### ISSUE TITLE
Xamarin.Forms support

### ISSUE THREAD

**Issue by NVentimiglia** [molinch/FFImageLoading#28]
Being able to apply this to a XamarinForms Image or ImageSource would be nice. Heck, even if Success returned a byte[] would make my life easier.

**Comment by molinch** [comment]
@NVentimiglia that's something I'm also interested to have. In fact there is already a task for it: https://github.com/molinch/FFImageLoading/issues/11

That could be done pretty easily using a custom renderer.

**Comment by NVentimiglia** [comment]
I ended up coming up with my own solution. The solution included two classes. The first was a file cache which was responsible for catching the image as well as acquiring the image using HTTP client. The second class was a async image which inherited from grid. Internally I had a placeholder image as well as the instance image. Once dependency properties were set I would load the image using the file path in the background. And remove the placeholder image.

**Comment by daniel-luberda** [comment]
I created CachedImage - Image compatible renderer for Xamarin.Forms. Here: https://gist.github.com/daniel-luberda/f2381b736eb62afd238a

**Comment by NVentimiglia** [comment]
Nice, ill close the issue and look into migrating over.

**Comment by daniel-luberda** [comment]
Added PR https://github.com/molinch/FFImageLoading/pull/32
