### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by NimaGhaedsharafi** [molinch/FFImageLoading#29]
Hi

every time I try to use the package it's gonna throwing a null pointer exception,
this is the stack trace

I tried to run it on UIThread but there was no hope too and also the inputs are true and meaningful.
the URL is valid and the Image taken as ImageViewAsync.

thanks

<img width="1280" alt="screen shot 2015-08-21 at 8 46 35 pm" src="https://cloud.githubusercontent.com/assets/3203970/9413508/719f1c66-4847-11e5-8c69-1f670ee06725.png">

<img width="1280" alt="screen shot 2015-08-21 at 8 52 57 pm" src="https://cloud.githubusercontent.com/assets/3203970/9413458/2d854fa0-4847-11e5-9596-5622ba2c49f9.png">

Thread started:  #5
[Mono] DllImport attempting to load: '/system/lib/liblog.so'.
[Mono] DllImport loaded library '/system/lib/liblog.so'.
[Mono] DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
[Mono] Searching for '__android_log_print'.
[Mono] Probing '__android_log_print'.
[Mono] Found as '__android_log_print'.
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x00078>
[MonoDroid] at Android.Runtime.JNIEnv.CallNonvirtualObjectMethod (intptr,intptr,intptr) [0x00084] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:596
[MonoDroid] at Android.Content.ContextWrapper.get_ApplicationContext () [0x0005f] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Content.ContextWrapper.cs:86
[MonoDroid] at FFImageLoading.Work.ImageLoaderTask..ctor (FFImageLoading.Cache.IDownloadCache,FFImageLoading.Helpers.IMainThreadDispatcher,FFImageLoading.Helpers.IMiniLogger,FFImageLoading.Work.TaskParameter,Android.Widget.ImageView) <IL 0x0001b, 0x0011b>
[MonoDroid] at FFImageLoading.TaskParameterExtensions.Into (FFImageLoading.Work.TaskParameter,FFImageLoading.Views.ImageViewAsync) <IL 0x0001b, 0x0012b>
[MonoDroid] at FFImageLoading.TaskParameterExtensions.IntoAsync (FFImageLoading.Work.TaskParameter,FFImageLoading.Views.ImageViewAsync) <IL 0x0004d, 0x002ef>
[MonoDroid] at Nabsh.Droid.FragmentProfile.setAvatar (string) [0x00000] in /Users/nghaedsharafi/Projects/Mobile/Nabsh/Nabsh.Droid/Fragments/FragmentProfile.cs:186
[MonoDroid] at Nabsh.Droid.FragmentProfile.updateInformation (Nabsh.UserCollection) [0x000f4] in /Users/nghaedsharafi/Projects/Mobile/Nabsh/Nabsh.Droid/Fragments/FragmentProfile.cs:446
[MonoDroid] at Nabsh.Droid.FragmentProfile.OnResume () [0x000ca] in /Users/nghaedsharafi/Projects/Mobile/Nabsh/Nabsh.Droid/Fragments/FragmentProfile.cs:118
[MonoDroid] at Android.App.Fragment.n_OnResume (intptr,intptr) [0x00009] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Fragment.cs:2231
[MonoDroid] at (wrapper dynamic-method) object.61cf03a3-77d7-4ebc-b1f2-69c24bd42ada (intptr,intptr) <IL 0x00011, 0x0003b>
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] java.lang.NullPointerException
[MonoDroid] 	at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:109)
[MonoDroid] 	at md53ce6c8f55ef4cac3974be43930779339.FragmentProfile.n_onResume(Native Method)
[MonoDroid] 	at md53ce6c8f55ef4cac3974be43930779339.FragmentProfile.onResume(FragmentProfile.java:38)
[MonoDroid] 	at android.app.Fragment.performResume(Fragment.java:1753)
[MonoDroid] 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:925)
[MonoDroid] 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1063)
[MonoDroid] 	at android.app.BackStackRecord.run(BackStackRecord.java:684)
[MonoDroid] 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1450)
[MonoDroid] 	at android.app.Activity.performResume(Activity.java:5365)
[MonoDroid] 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2787)
[MonoDroid] 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2826)
[MonoDroid] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
[MonoDroid] 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:136)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:5103)
[MonoDroid] 	at java.lang.reflect.Method.invokeNative(Native Method)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Method.java:515)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
[MonoDroid] 	at dalvik.system.NativeStart.main(Native Method)
[AndroidRuntime] Shutting down VM
[libc] Fatal signal 6 (SIGABRT) at 0x00000399 (code=0), thread 31059 (ir.nifi.nabsh)

____________

﻿System.Diagnostics.Debugger.Mono_UnhandledException_internal () in 
System.Diagnostics.Debugger.Mono_UnhandledException (ex={Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.

  --- End of managed exception stack trace ---
java.lang.RuntimeException: Unable to resume activity {ir.nifi.nabsh/md53ce6c8f55ef4cac3974be43930779339.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2797)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2826)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
	at android.app.ActivityThread.access$800(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:109)
	at md53ce6c8f55ef4cac3974be43930779339.FragmentProfile.n_onResume(Native Method)
	at md53ce6c8f55ef4cac3974be43930779339.FragmentProfile.onResume(FragmentProfile.java:38)
	at android.app.Fragment.performResume(Fragment.java:1753)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:925)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1063)
	at android.app.BackStackRecord.run(BackStackRecord.java:684)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1450)
	at android.app.Activity.performResume(Activity.java:5365)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2787)
	... 12 more
}) in 
Android.Runtime.UncaughtExceptionHandler.UncaughtException (thread=, ex=) in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/src/Runtime/UncaughtExceptionHandler.cs:35
Java.Lang.Thread.IUncaughtExceptionHandlerInvoker.n_UncaughtException_Ljava_lang_Thread_Ljava_lang_Throwable_ (Parameters=) in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.Thread.cs:221
object.19268583-cbff-491c-a1fe-7ef1bac4af23 (Parameters=) in

**Comment by molinch** [comment]
From what I see it looks like retrieving the Android Context is failing...
We rely on Android.App.Application.Context to get it. That is very weird.
Would you upload a sample somewhere or email a sample to me?

**Comment by NimaGhaedsharafi** [comment]
I figured it out whats the problem but too wired to me!!
setting default shared preferences  to (this) make the null pointer exception problems!!
i had a static class like this.
```
using System;
using Android.App;
using Android.Content;

namespace Nabsh.Droid
{
	public class MyApp: Application
	{
		private static Context context;

		public MyApp(Context c)
		{
			MyApp.context = c;
		}

		public static Context getAppContext() {
			return MyApp.context;
		}
	}
}
```
and i get the context form this class and set it as default 
```PreferenceManager.GetDefaultSharedPreferences (Nabsh.Droid.MyApp.getAppContext()); ```

now I changed my code to this, 
```PreferenceManager.GetDefaultSharedPreferences (Android.App.Application.Context); ```
and now it's works well!

thanks :)

**Comment by NimaGhaedsharafi** [comment]
btw thank you for ur caring about others' problems :+1:

**Comment by molinch** [comment]
Thanks for the feedback !! :)
