### ISSUE TITLE
Can this work for min 4.0?

### ISSUE THREAD

**Issue by dhaligas** [molinch/FFImageLoading#3]
Can this lib work android 4.0?  We need to support 4.0 and up

**Comment by molinch** [comment]
Everything is doable. I'll see how much effort it and come back to you

**Comment by dhaligas** [comment]
thanks!

**Comment by dhaligas** [comment]
looking to use this in Xamarin.Forms on custom lists

**Comment by molinch** [comment]
It now works in Xam.iOS too
I need to continue for 4.0. If you do some Xamarin.Forms integration would you share your work?

**Comment by molinch** [comment]
I just checked and it should work on Android 4.0

**Comment by dhaligas** [comment]
yes I will be trying this out on Forms.  will gladly share with you

**Comment by molinch** [comment]
Hi @dhaligas 
Do you still plan to release a XForms integration?
