### ISSUE TITLE
no option to turn off fade-in on Android?

### ISSUE THREAD

**Issue by kenkyee** [molinch/FFImageLoading#31]
When you use FFImageLoading, the images always fade in on Android even if you use an image from the Assets folder.  Is there any way to disable the fade?

**Comment by molinch** [comment]
If you want to do it: you can add a parameter `bool PerformFade` to TaskParameter and also add his Fluent method. Then you can use this in Android ImageLoaderTask instead of the property `UseFadeInBitmap` which is always true right now.

I am happy to merge such a PR :+1:

**Comment by daniel-luberda** [comment]
https://github.com/daniel-luberda/FFImageLoading/commit/78677fd41f8c89c0a52e8a0f2e2a1366af6565c2

**Comment by molinch** [comment]
@daniel-luberda Awesome! 
I will just activate them by default in Configuration, instead of having them disabled by default, otherwise it is a change for existing apps.

**Comment by molinch** [comment]
Dammit! You already did it in https://github.com/daniel-luberda/FFImageLoading/commit/57317966b8a134900bd05bdd212f789c1621621c
You can forget my comment :+1:

**Comment by molinch** [comment]
Please note that it is also possible now to globally disable the fade (so for all images loaded via the lib).
This is done using ImageService.Initialize() see https://github.com/molinch/FFImageLoading/commit/270e509558b79f956765bd07ce233bc0b3722f35
