### ISSUE TITLE
Change HttpClient (or moreover the HttpClientHandler)

### ISSUE THREAD

**Issue by KroanNL** [molinch/FFImageLoading#35]
For a project our images are on a server that is secured with credentials. We use the following to create an HttpClient with the correct credentials.

```
var handler = new HttpClientHandler();
handler.Credentials = new NetworkCredential(_username, _password);
var httpClient = new HttpClient(handler);
ImageService.Initialize(0, httpClient);
```

If the user logs out and tries to login with different credentials, we can't create a new HttpClient with those new credentials and assign it to the ImageService.

Initalizing it a second time throws the "FFImageLoading.ImageService is already initialized" error.

Is there any way to change the HttpClient to a public property?

**Comment by molinch** [comment]
I'm happy to merge a PR for that :)

Basically the change would be in ImageService, DownloadCache and IDownloadCache.
DownloadCache should probably have a method, or a property, that allows changing the HttpClient.
ImageService should have a static method that would pass the HttpClient to the DownloadCache instance.

**Comment by molinch** [comment]
Finally I had some free time so I implemented this. Currently it's in git only though. Could you test it?

**Comment by KroanNL** [comment]
Will do and report back!

Sent from my iPhone

**Comment by molinch** [comment]
You can test this prerelease NuGet package which contains it: https://www.nuget.org/packages/Xamarin.FFImageLoading/1.1.6-alpha

If it works fine I'll make a release.

**Comment by KroanNL** [comment]
Hey man,

Sorry, I had not yet time to test this out. I hope to do this before the
end of the week. Thanks for your hard work!

Kind regards
Vincent
