### ISSUE TITLE
Xamarin.Forms PCL project not working

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#36]
Can we add a PCL profile for nuget? We need only FFImageLoading.Forms.dll which is PCL compatible. 

> Could not install package 'Xamarin.FFImageLoading 1.1.5'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by molinch** [comment]
Mmh that's quite weird I tested the Nuget in a Forms project and it used to work.
Maybe I tried only the shared project I think you can have both PCL and shared isn't it?

**Comment by daniel-luberda** [comment]
Yes, Forms project can be shared or PCL (PCL library for almost everything and native project for renderers etc).

**Comment by molinch** [comment]
It was a lot of pain but I have now a Nuget that should be OK for PCL project too: https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/1.1.6-alpha4

**Comment by daniel-luberda** [comment]
It still doesn't install. You have to add 
portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10
as target for FFImageLoading.Forms.dll

**Comment by molinch** [comment]
That's weird cause on my XF PCL it did install.. Are you sure you tried the Alpha4 Nuget package?

**Comment by daniel-luberda** [comment]
Yes, I'm sure. Try to install package on library project (it's where App class of Xamarin.Forms resides), not platform specific project. 
Something like:
<file src="FFImageLoading.Forms/bin/Release/FFImageLoading.Forms.dll" target="lib/portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10/FFImageLoading.Forms.dll" />
It doesn't need any other file than FFImageLoading.Forms.dll (shared stuff)  - renderers are initialized through dependency injection in platform specific project)

**Comment by molinch** [comment]
Ok I found what happens. Package does work in XF PCL project but only if it has profile 49.
Since you use profile 78 it doesn't install. I will change that.

**Comment by daniel-luberda** [comment]
Yes, that's a default Xamarin.Forms project profile. Thanks!

**Comment by molinch** [comment]
Ok a new alpha is on Nuget that should work with profile 78: https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/1.1.6-alpha5

**Comment by daniel-luberda** [comment]
Works good! Can be closed :)
