### ISSUE TITLE
Callback Problem

### ISSUE THREAD

**Issue by mgorbach** [molinch/FFImageLoading#39]
Referencing my earlier issue [https://github.com/molinch/FFImageLoading/issues/34], this is a separate one to address the callback problem.
When loading from the in-memory cache, the finish callback is called and both "completed" and "cancelled" are false. It seems like "completed" should be true in this case.

**Comment by molinch** [comment]
You can test it if you want in this Alpha nuget https://www.nuget.org/packages/Xamarin.FFImageLoading/1.1.6-alpha2
