### ISSUE TITLE
Error when using ImageViewAsync

### ISSUE THREAD

**Issue by dasmikko** [molinch/FFImageLoading#4]
I get this error when using ``ImageViewAsync``

```
No constructor found for FFImageLoading.Views.ImageViewAsync::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
```

What am i doing wrong?

**Comment by molinch** [comment]
ImageViewAsync has two constructors:
```C#
public ImageViewAsync(Context context, SizeF? predefinedSize=null)
public ImageViewAsync(Context context, IAttributeSet attrs, SizeF? predefinedSize=null)
```

I believe that is why you have this issue: there is no constructor with the signature:
```C#
System.IntPtr, Android.Runtime.JniHandleOwnership
```

Could you paste some code here or attach a zip file of your solution?

**Comment by dasmikko** [comment]
Here is my code:

```
using System;

using Android.App;
using Android.Content;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;
using RestSharp;
using FFImageLoading;
using FFImageLoading.Views;
using FFImageLoading.Helpers;
using FFImageLoading.Extensions;

namespace SimpleshopApp
{
	[Activity (Label = "SimpleshopApp", MainLauncher = true, Icon = "@drawable/icon")]
	public class MainActivity : Activity
	{
		int count = 1;

		protected override void OnCreate (Bundle bundle)
		{
			base.OnCreate (bundle);


			// Set our view from the "main" layout resource
			SetContentView (Resource.Layout.Main);

			// Get our button from the layout resource,
			// and attach an event to it
			Button button = FindViewById<Button> (Resource.Id.myButton);
			ImageViewAsync imgView = FindViewById<ImageViewAsync> (Resource.Id.imageView1);
			var client = new RestClient ("http://xkcd.com/");

			var request = new RestRequest (String.Format ("info.0.json"));

			var asyncHandle = client.ExecuteAsync<Comic>(request, response => {
				var img = response.Data.img;
				Console.WriteLine(img);



			});
			
			button.Click += delegate {
				button.Text = string.Format ("{0} clicks!", count++);


			};
		}
	}
}
```

**Comment by molinch** [comment]
Looks like this is a known issue of Xam.Android: http://stackoverflow.com/questions/26573627/no-constructor-found-for-system-intptr-android-runtime-jnihandleownership

Solutions seems to be simple: adding the other constructor and calling the base one.
This is what I just did: https://github.com/molinch/FFImageLoading/commit/22bed2204871fc9de5081ddaecb00844cdcca40c

Do you have the possibility to test using master's sources?
I can make a new NuGet package once I get your confirmation.

**Comment by dasmikko** [comment]
I'm not sure how to :(

**Comment by molinch** [comment]
Don't worry I just made a prerelease NuGet package.
If you go in the Package console in Visual studio you can have it by executing
<pre>
Install-Package Xam.Android.ImageLoading -Pre
</pre>

**Comment by dasmikko** [comment]
How to, in Xamarin Studio? :)

**Comment by molinch** [comment]
In the Add Nuget package popup search for "imageloading" and tick "Show pre-release packages".
Then you can take the 1.0.2-beta

**Comment by dasmikko** [comment]
Still throws the same error.

**Comment by molinch** [comment]
My bad. I think that something went wrong and the nuget doesn't contain the latest changes.
I just removed bin/obj and made a new nuget which is now 1.0.3-beta

**Comment by dasmikko** [comment]
Works perfectly now! Thanks!
