### ISSUE TITLE
Xamarin.Forms Sample

### ISSUE THREAD

**Issue by molinch** [molinch/FFImageLoading#41]
I would be very grateful if somebody was able to make a sample. Something similar to what we have on Android would be perfect

**Comment by daniel-luberda** [comment]
I can do that :) First, I'll add placeholders  handling support and than I'll send PR with some examples.

**Comment by molinch** [comment]
Great! Thanks @daniel-luberda :+1:

**Comment by molinch** [comment]
It's already nice but it would be awesome if your sample used more features on both iOS and Android: local placeholders, maybe a list view to have more images (so we can test cancellation), ...

**Comment by daniel-luberda** [comment]
Ok, I'll add some more advanced example with lists, etc. 

BTW: I noticed that error placeholder doesn't work with local images. However, loading placeholder works good with local images (they use the same CompiledResource type). Do we have a bug here? Or something else?

**Comment by molinch** [comment]
Weird it shouldn't be the case, error and loading placeholders rely on the same logic.
I'm really busy now but if you find anything I'm happy to have a look at it

**Comment by daniel-luberda** [comment]
https://github.com/molinch/FFImageLoading/pull/43

**Comment by molinch** [comment]
I consider this as done. If in the future you want to add functionalities (WebP decoding, other?) feel free to do that.

**Comment by daniel-luberda** [comment]
I'll be definitely adding some, when I'll have more free time.

It would be nice to implement Finish, Success, Error Actions.

Also Transformations in renderers would be useful. (That way we could have circle image which a lot people use). What do you think about moving `samples/ImageLoading.Sample/Transformations/` files to regular library?

**Comment by molinch** [comment]
If somebody makes a PR that contains the same transformations for both iOS and Android then yes: I would be OK to make a specific nuget.

**Comment by daniel-luberda** [comment]
Yes, definitely cross-platform all the way. I have something: https://github.com/molinch/FFImageLoading/pull/47, tell me what do you think about it. 

![screenshot](https://raw.githubusercontent.com/daniel-luberda/FFImageLoading/master/samples/Screenshots/android_transformations.png)

**Comment by molinch** [comment]
That's cool :+1:  I will check the PR and let you know
