### ISSUE TITLE
Xamarin.Forms - Error placeholders not working

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#44]
Error Placeholders not working. Don't have time now to check it. I really don't know why it isn't working. It's handled the same way as Loading Placeholders (and they work fine!). You can test it in samples I uploaded: https://github.com/molinch/FFImageLoading/pull/43 (Placeholders button)

![nexus 4 lollipop screenshot 16](https://cloud.githubusercontent.com/assets/13569983/10143924/2aa78f18-661b-11e5-9ab5-98b79de92ceb.png)

**Comment by molinch** [comment]
Thanks @daniel-luberda it will be easier to spot what's going on

**Comment by daniel-luberda** [comment]
Ups, didn't add csproj files to commit, so you have to manually add "error.png" and "loading.jpg" to you project files. I'll make a commit for this.

**Comment by daniel-luberda** [comment]
Thanks! What a typo! :) I didn't see that!

**Comment by daniel-luberda** [comment]
Still not working for me, even after https://github.com/molinch/FFImageLoading/commit/34a0a98eef19f1b6ad3f3e79f22309d5675086ea

**Comment by molinch** [comment]
It works fine. If you want to see it faster then use something else than notexisting.com your website doesn't respond

**Comment by molinch** [comment]
Btw there are issues with the Xamarin.Forms renderer: in the placeholder example, when you tap a link it does 2 loading request. I tried to debug it and SetImage is called twice. Could you have look?

**Comment by daniel-luberda** [comment]
Yes, I'll check it out and let you know

**Comment by daniel-luberda** [comment]
How did you check if it's called twice? Did you check Application output? If you use System.Diagnostics.Debug.WriteLine then it always generate two lines (one blue and one black). Is it that?

**Comment by molinch** [comment]
If you set a breakpoint in SetImage you will see that it's called twice.
Basically what happens is that 1st call starts, then 2nd call arrives, and since it uses the same native control we cancel the 1st one (this makes sense).
Therefore why SetImage is called twice I have no idea... :|

**Comment by daniel-luberda** [comment]
Yes, I noticed it. I'll try to find the issue. Thanks.

**Comment by daniel-luberda** [comment]
Found the issue! Will commit soon.

**Comment by daniel-luberda** [comment]
https://forums.xamarin.com/discussion/52500/bindableproperty-of-imagesource-type-raises-propertychanged-twice-in-custom-views#latest

I'll commit a temporary fix. Can you check it it's the same on iOS?

**Comment by daniel-luberda** [comment]
It should be ok now: https://github.com/molinch/FFImageLoading/pull/47

**Comment by molinch** [comment]
FYI you might be interested to look this ModernHttpClient issue: https://github.com/paulcbetts/ModernHttpClient/issues/184

That is why on Android the error placeholder is displayed after 1 minute... On iOS it's after 15s.

**Comment by daniel-luberda** [comment]
Yes, that's what I was experiencing.
