### ISSUE TITLE
Windows (Phone, Universal apps) support

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#46]
It would be really nice to have this. 

For the start, I could make a renderer for Windows, which inherits from standard Xamarin.Forms `Image`, without FFImage features - just for compatibility reasons (Windows can automatically cache loaded images). 

This way we could use FFImageLoading on all Xamarin.Forms supported platforms.

**Comment by molinch** [comment]
Great idea ! :+1:

**Comment by kirajhpang** [comment]
hi, I willing to use FFImageLoading in my xamarin.forms project, but wp will throw exception when it come to that page which needed FFImageLoading library. 

I already added the FF library into wp project which I understand it cannot init(). I will use devie on platform to avoid wp use FF, but it still crush when come to that page.

btw, my wp project use PCL also. 

Any comment to solve the wp problem ?

**Comment by daniel-luberda** [comment]
@kirajhpang FFImageLoading isn't currently compatible with Windows but I'm working on it.

**Comment by KroanNL** [comment]
This would be incredible helpful to have. Is there any progress on this?

**Comment by daniel-luberda** [comment]
Very soon

**Comment by daniel-luberda** [comment]
https://github.com/molinch/FFImageLoading/pull/70
