### ISSUE TITLE
Use Mono default HttpClientHandler instead of ModernHttpClient?

### ISSUE THREAD

**Issue by molinch** [molinch/FFImageLoading#49]
I found two issues when using ModernHttpClient's HttpClientHandler
* https://github.com/paulcbetts/ModernHttpClient/issues/184
* https://github.com/paulcbetts/ModernHttpClient/issues/185

Because of that I am wondering if by default we should not provide the Mono/.NET HttpClientHandler (instead of ModernHttpClient) but let the user be able to specify an other one with ImageService.Initialize().

@daniel-luberda What do you think?

**Comment by daniel-luberda** [comment]
@molinch As this is https://github.com/paulcbetts/ModernHttpClient/issues/184 not so bad, this one: https://github.com/paulcbetts/ModernHttpClient/issues/185 is a real problem. 

It would be nice to be able to choose alternative http clients in Initialize method. For now, I would also switch to mono HttpClientHandler. It will also make FFImageLoading independent of ModernHttpClient, which is another bright side (not everyone can use it). 

Instead, when those bugs are fixed, I would add a short tutorial in README.md showing how to change http client to ModernHttpClient and make FFImageLoading requests faster.

**Comment by molinch** [comment]
I agree with you #185 is really bad. #184 might be difficult to fix, it seems to be the Android network stack that has an issue. Mono has a different network stack, it opens its own sockets, so it is not affected.

Have you been able to reproduce these issues? And just switching the HttpClient in `ImageService.Initialize` fixes both. Could you also give it a try?

Once I have your feedback I will switch to default HttpClient. It makes sense and people can still override it.

I'm all in for a blog post it's a great idea :+1:  Also if you would like to improve the README then don't hesitate. I'm a bit worried about it's size, it could be splitted in more files IMO.

**Comment by daniel-luberda** [comment]
Tested it, and it looks like it's solved on Android. Didn't test on iOS yet though.

**Comment by daniel-luberda** [comment]
Actually, didn't notice performance difference at all when using mono HttpClientHandler.

**Comment by molinch** [comment]
Yeah me neither...

**Comment by daniel-luberda** [comment]
Maybe the requests rate it's still to low to benefit from ModernHttpClient (eg. large image data responses vs high rate rest requests, etc).

**Comment by molinch** [comment]
True, could be that our scenario is different from most use cases

**Comment by daniel-luberda** [comment]
It looks like it's a win-win situation (less dependencies and no bugs) :)
