### ISSUE TITLE
loadurl into imageview makes imageView not centered

### ISSUE THREAD

**Issue by dasmikko** [molinch/FFImageLoading#5]
When I load an image from a URL into a ImageView it resets the position and makes my centered imageview not centered.

My imageView is centered by this:
```
android:layout_width="match_parent"
android:layout_height="match_parent"
```
Image:
![2015-02-27_10-17-36](https://cloud.githubusercontent.com/assets/4254869/6409932/12d15d78-be6a-11e4-993c-9a0fd2d51a9e.png)

**Comment by molinch** [comment]
Could you post the full axml and also your loading code?

**Comment by molinch** [comment]
I just added some new properties into ImageViewAsync on Android (ScaleToFit and BottomAlign). Maybe the latest changes will solve the issue you are facing.

Please keep me updated.

**Comment by molinch** [comment]
Closed due to inactivity
