### ISSUE TITLE
Images Do Not Load

### ISSUE THREAD

**Issue by highplains** [molinch/FFImageLoading#55]
Xamarin.Forms - latest
Xcode 7 - latest
Xam Studio - Latest
Platform Tested - iOS ONLY

This issue is that when you are building for release/appstore version and the iOS project settings are configured as iOS Build -> Advanced -> Supported Architectures (ARMv7 + ARM64) (required for a AppStore release) this breaks image loading. But if you change this setting to (Armv7) only and rebuild which is what Debug builds seem to default to it works fine.

I've seen this problem in a few Xam.Plugins projects as well and found a few lines of code that made the difference...

https://github.com/aritchie/userdialogs/issues/55

**Comment by molinch** [comment]
Wow that is ultra weird! I looked at the fix you submitted in Acr UserDialogs and it's really random things that fixes this...
Should be fixed asap

**Comment by highplains** [comment]
Also note that in the sample app... Forms Example.... You have to go into "Release" build config for this error to happen. Seems ok in "Debug", and has to be tested on a actual device, works fine in simulator.

**Comment by molinch** [comment]
Huge thanks for debugging this @highplains :+1:

**Comment by molinch** [comment]
Btw I tested FFImageLoading with Arm7+64, in release mode, on a real 64b device. It works fine.
So I guess it comes from the Xamarin Forms wrapper.

**Comment by highplains** [comment]
Ya i spent a little bit of time looking for it, but couldn't find it. I know that the previous stable build didn't have this bug so it's something new within those commits.

**Comment by highplains** [comment]
What was weird is that i matched up my Debug and Release configurations to be identical, and the issue still only occurs when in Release mode. But the main problem is that with the latest build release versions are worthless making a App Store push now impossible without reverting to an old version.

**Comment by molinch** [comment]
I'm trying all options.... A few more things:
* ARMv7: OK
* ARM64: OK
* ARMv7+ARM64: KO... WHAT THE FUCK

**Comment by highplains** [comment]
lol RIGHT! Freaking mind boggling.

**Comment by daniel-luberda** [comment]
Ok, if it's with forms I'll check on this. REALLY strange bug though. Maybe it's something with project options? "Compilation Turned on optimizations" <- it's what comes into my mind (it wasn't checked in previous builds).

**Comment by highplains** [comment]
I tried every combination of optimizations in all projects... Still couldn't get it to work.

**Comment by daniel-luberda** [comment]
It could be also a bug with Xamarin.Forms ViewRenderer (we switched from ImageRenderer to ViewRenderer). I could make a commit with "the old way". Could you test it?

**Comment by highplains** [comment]
sure

**Comment by daniel-luberda** [comment]
Give me a few minutes and I'll send you a PR link.

**Comment by molinch** [comment]
YAY: https://bugzilla.xamarin.com/show_bug.cgi?id=31076
Looks like this one...

**Comment by daniel-luberda** [comment]
Ok... That's quite reasonable explanation. It could be a linking problem. It's easy to fix, just include this in 

```
		public override bool FinishedLaunching(UIApplication app, NSDictionary options)
		{
			FFImageLoading.Forms.Touch.CachedImageRenderer.Init();
			var dummy = new FFImageLoading.Forms.Touch.CachedImageRenderer();

			global::Xamarin.Forms.Forms.Init();
			LoadApplication(new App());

			return base.FinishedLaunching(app, options);
		}
```

**Comment by highplains** [comment]
Makes sense, but just tried the workaround and still not working.

**Comment by daniel-luberda** [comment]
What did you try?

**Comment by molinch** [comment]
I confirm that it works fine with the "hack" :+1:

**Comment by daniel-luberda** [comment]
```
		/// <summary>
		///   Used for registration with dependency service
		/// </summary>
		public static new void Init()
		{
		}
```
as you see it hides iOS specific method. Maybe it's this?

**Comment by highplains** [comment]
<img width="989" alt="screen shot 2015-10-09 at 3 14 27 pm" src="https://cloud.githubusercontent.com/assets/1825076/10405767/7acecf3a-6e98-11e5-9699-9a1a0fd43543.png">

**Comment by highplains** [comment]
You got this working in release mode with (Arm7 + Arm64) with that workaround molinch?

**Comment by molinch** [comment]
@highplains Yes dunno why it doesn't work on your side :( Could you try removing app and cleaning/rebuilding?

@daniel-luberda I'm almost sure it isn't related to method hiding. Method hiding shouldn't do anything to the linker. It generates a different method signature, classes will still invoke the iOS Init(), not this one.

**Comment by daniel-luberda** [comment]
@molinch Yes, but who knows how does it works inside. Original method is commented as necessary for preventing linking.

**Comment by highplains** [comment]
rookie move on my part, my bad! Ya the workaround does the trick.

**Comment by daniel-luberda** [comment]
So I have two questions:
- Should we modify or abandon CachedRenderer.Init method? 
- Should we update REAMDE.md to put a dummy instance instead of using Init method?

**Comment by molinch** [comment]
I don't think we need to do anything regarding Init() since this issue is absolutely unrelated to it. But maybe can you explain what you mean here: "Original method is commented as necessary for preventing linking."?

For your second point please don't do that. I'm trying something else.

**Comment by molinch** [comment]
No need to change the Readme. This way it's easier for the users of the package.
I will recreate the Forms nuget.

**Comment by highplains** [comment]
Appreciate it guys!

**Comment by daniel-luberda** [comment]
<ok> 

> But maybe can you explain what you mean here: "Original method is commented as necessary for preventing linking."?

I'm VERY sure that I read something in Xamarin docs about it. While making FFImageLoading renderer I was trying to find if it will collide with something.

**Comment by daniel-luberda** [comment]
On the other side, many controls use Init method, eg SyncFusion charts (SfDataGridRenderer.Init() method), so maybe I'm oversensitive about it.

**Comment by molinch** [comment]
TBH I quickly googled and couldn't find anything about it, all examples use Init(). But if you find something I'm happy to change it.

**Comment by molinch** [comment]
@daniel-luberda @highplains https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/1.1.7.1
Could you try it?

**Comment by daniel-luberda** [comment]
I can't find it too now, but I'm sure I read something about it. I'll try to find it and post it here :D

**Comment by highplains** [comment]
@daniel-luberda you good with Forms.Droid? Is there a way to get in touch with you? We are close to initial seed funding on a startup and am going to need dev's familiar with Forms soon.

**Comment by highplains** [comment]
actually same with you @molinch

**Comment by highplains** [comment]
New nuget works in my app !

**Comment by molinch** [comment]
:+1: Love to fix Xamarin bugs

@highplains I would love such challenges therefore I'm much more into plain Xamarin iOS/Xamarin Android. I didn't tackled Forms much.

**Comment by highplains** [comment]
Hard to find a good Xam / Xam.Forms team nowadays.

**Comment by highplains** [comment]
Android isn't my best either, better with iOS @molinch

**Comment by daniel-luberda** [comment]
@molinch The best bugs IMO is still some magic happening with ImageSource and propertychanged :)

Yes sure, I'm playing with Forms since its beginning (and a lot with Xamarin.Android too (since Novell times)). Just mail me. myName.mySurname (at) gmail.com

**Comment by highplains** [comment]
@daniel-luberda i feel like half of my day is fixing Forms bugs lol

**Comment by daniel-luberda** [comment]
@highplains Yes true, a lot of bugs but can live with that if you know them. Actually a lot has changed for good. First version were like alpha not tested builds :) There were even bugs like if you had a ListView and scrolled it, its items were magically and dynamically mixing while scrolling (5th element became 1st) :D I remember that well because I filled it as a bug then.

**Comment by highplains** [comment]
lol ya i filed a few ListView bugs too.. There "HasUnevenRows" has been pretty bad and they way the listview behaves after adding or removing models to the observablecollections is still weird. But the last stable and recent pre release is showing promise. Overall though im a fan of the framework.

**Comment by daniel-luberda** [comment]
@highplains @molinch The good thing is it's progress. Xamarin.Forms is a great framework - but as you see, it cannot live without native Xamarin.iOS, Xamarin.Android renderers :) Ok. Thanks for catching / fixing bug.
