### ISSUE TITLE
Change title of nuget packages

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#56]
Could we change it to be compatibile with this requirements:  https://github.com/xamarin/plugins (we could list FFImageLoading there)

- FFImageLoading Plugin for Xamarin iOS/Android
- FFImageLoading Plugin for Xamarin Forms
- FFImageLoading Transformations

**Comment by molinch** [comment]
I already have one of my plugins there: ManageSleep.
Unfortunately since FFImageLoading doesn't have WP support I don't think we can list it.

**Comment by daniel-luberda** [comment]
I didn't know if it's required to support Windows too. We'll work on this later :)

But... nuget names could be changed. "Xamarin forms renderer..." title is a little confusing.

**Comment by molinch** [comment]
Nuspec changed and packages are also already changed on nuget.org.
