### ISSUE TITLE
Build issue - TransformationBase missing

### ISSUE THREAD

**Issue by bertbeck** [molinch/FFImageLoading#57]
I'm doing a build of the entire solution and get an error: TransformationBase could not be found.

See attached screen shot

![screen shot 2015-10-12 at 4 23 51 pm](https://cloud.githubusercontent.com/assets/6159170/10437842/f0f83aae-70fd-11e5-8482-c216d47dad1e.png)

**Comment by daniel-luberda** [comment]
Transformations are in a separate DLL. Just add this package https://www.nuget.org/packages/Xamarin.FFImageLoading.Transformations/ as a reference or add transformations as a reference.

**Comment by daniel-luberda** [comment]
Forgot about it. And add `using FFImageLoading.Transformations;` This sample should be fixed, we forgot about it.

**Comment by daniel-luberda** [comment]
If you only want to build FFImageLoading, you can safely unload this project.

**Comment by bertbeck** [comment]
Thanks Daniel - I added the using statement to all tranformations and it
builds ok now

Bert

**Comment by bertbeck** [comment]
I just ran the demo - looks great!

In trying to use it though - I'm running into a problem. My app needs to
display circular images - so I'm using this:

            ImageCircle.Forms.Plugin.Abstractions.CircleImage picture = new
 ImageCircle.Forms.Plugin.Abstractions.CircleImage();
            picture.SetBinding (Image.SourceProperty, "ImageUrl",converter:
new WebUtil.CacheConverter());
            picture.HeightRequest = 50;
            picture.WidthRequest = 50;
            picture.Aspect = Aspect.AspectFill;
            picture.BorderColor = Color.White;

Is there a way to have ImageCircle use your mechanism for  caching images ?

Is there a good book/reference for learning the details of Xamarin Forms
building blocks and understanding how for instance - the listview can have
a list of images that dynamically change (like you do - changing the
placeholder image into the real image). I'm going to study your code - but
how did you learn how to do this ?

Thanks mucho

Bert

**Comment by daniel-luberda** [comment]
Actually, FFImageLoading can display Circle Image out-of the box. Just use CircleImageTransformation:

`.Transform(new CircleImageTransformation());`

Look at this: 
https://raw.githubusercontent.com/molinch/FFImageLoading/master/samples/Screenshots/android_transformations.png

I'm not changing images dynamically. FFImageLoading has Loading And Error placeholders support. It handles everything automatically (while image is downloading, the placeholder is shown, then when it finishes - it shows downloaded image).

Xamarin.Forms uses binding system, almost the same as Microsoft WPF which is used in Windows/WindowsPhone. I'm using Xamarin.Forms for quite a long long time. There's http://www.xforms-kickstarter.com and good tutorials on official docs https://developer.xamarin.com/guides/cross-platform/xamarin-forms/

**Comment by bertbeck** [comment]
thanks!

btw - what do you charge per hour? I may need some help down the road or
may have some work

Bert

**Comment by daniel-luberda** [comment]
You can contact me with email provided on my github profile.
