### ISSUE TITLE
picasso functionality

### ISSUE THREAD

**Issue by c1rus** [molinch/FFImageLoading#6]
hi, this library looks great, thanks for it.

do you have any plans to implement same functionality like Picasso, particulary functions like transform or placeholder???

if not, can you give some hints?

Thanks.

**Comment by molinch** [comment]
Placeholder functionality could be done very easily.

Transform might be more tricky tough. We could have an optional Transform callback that would allow you to do any manipulation on the image before having it displayed.
iOS signature could then be something like: TaskParameter.Transform(UIImage image, string transformationCacheKey)
Android signature could be like: TaskParameter.Transform(Bitmap bitmap, string transformationCacheKey)
The additional parameter "transformationCacheKey" would be useful for the memory cache. Basically since we apply a transformation on the source image, if we want to cache it then we need an extra key.

What do you think of this?

**Comment by c1rus** [comment]
It shouldn't look like this?
```
Transform(string transformationCacheKey, Func<Bitmap, Bitmap> action)
```
I think i would prefer picasso style.
```
public interface ITransformation
{
	string Key { get;}
	Bitmap Transform(Bitmap bitmap);
}

ImageService.LoadUrl (urlToImage)
	.Transform(new RoundedTransformation())
	.Into (imgDisplay);
```
However both options are fine to me, so i can completly replace picasso with your library :)

Would you have time to look at it or should i give it a try?

**Comment by molinch** [comment]
You are totally right about signature :+1:  I was probably sleepy when I wrote this. 
I can look at it but I won't be very fast: it will take me a couple of days.

If you want to submit a PR that is also an option.

**Comment by c1rus** [comment]
couple of days sounds great.
i think you will do it better, so i'd rather wait. :)

**Comment by molinch** [comment]
Loading & error placeholders have been added.

```
ImageService.LoadUrl(urlToImage)
.LoadingPlaceholder("loading.png") // by default placeholders load from file
.ErrorPlaceholder("http://mydomain.com/error.png", ImageSource.Url) // but they can also load from a URL
.Into(_imageView);
```

Unfortunately I won't have time to make the Transform stuff right now. If you want to make a PR you are more than welcome.
In that case files that you would need to change are:
* TaskParameter: for your new Fluent method
* iOS ImageLoaderTask: you can hook into RunAsync
* Android ImageLoaderTask: you can hook into RunAsync

**Comment by c1rus** [comment]
Great, thanks. I will test it tomorrow, but one question:
Is there a way how to load image from Resources.Drawable?

**Comment by molinch** [comment]
Currently images having "Build Action" set to AndroidResources can't be loaded with the lib.

Therefore images having "Build Action" set to AndroidAssets can be loaded using ImageService.LoadFileFromApplicationBundle(relativePathToImage).

**Comment by molinch** [comment]
Hi @c1rus 
Have you been able to test this?

**Comment by c1rus** [comment]
Hi. 

Today i finally had time to look at it, but i was just testing. :)

1. when i'm loading placeholder images from ApplicationBundle, i'm getting OutOfMemoryError.
2. also it would be nice, if the fade animation works from placeholder.

i have created a sample project. so if you want, you can look at it here -> https://github.com/c1rus/ImageLoading.Sample

am i doing something wrong?

**Comment by molinch** [comment]
Hi @c1rus I just tested with GenyMotion and don't have this issue. I will test later on with a real device.
Are you testing with a simulator or a real device? Could you tell me your hardware specs?

**Comment by molinch** [comment]
Now I understood the issue you face and managed to reproduce it.
I will look into it

**Comment by c1rus** [comment]
Sorry, i have commited the version with url loading. Just change this -> https://github.com/c1rus/ImageLoading.Sample/blob/master/ImageLoading.Sample/ImageFragment.cs
I'm testing it with GenyMotion (Google Nexus 5 - predefined settings) and with Samsung Galaxy S2 - I9100.

**Comment by molinch** [comment]
I just changed the logic on Android so now loading large assets will take care about given DownSample parameter and we stream the data. With theses changes I don't see any OOM anymore.
I will make a nuget later in the day

**Comment by c1rus** [comment]
i just tried it with emulator and real device, and its working.
awesome, thanks for fast response :)

**Comment by c1rus** [comment]
about fade animation:

i think it would be better to change  FADE_TRANSITION_MILISECONDS from 50 to 200, 50 is hard to see.
and to get work fade animatiom from placeholder, just change to this:
```
var drawables = new[] {
	imageView.Drawable ?? new ColorDrawable(Color.Transparent),
	drawable
};
```

**Comment by molinch** [comment]
Done. I will close the task
