### ISSUE TITLE
Xamarin.Forms - Images get mixed after a lot of requests (cell reusing)

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#60]
Please try this sample: 
https://github.com/daniel-luberda/FFImageLoading/commit/c916f4c5b8b4de67d275414ffd39d1a00b6b2a12

Steps to reproduce: 
- Open List Demo
- Scroll the list FAST few times from start to end
- Click the "Duplicate list items"
- Scroll the list FAST few times from start to end
Result: 
Images get mixed (wrong order).

**Comment by daniel-luberda** [comment]
Fixed it. It would be nice to make a new build. https://github.com/daniel-luberda/FFImageLoading/commit/8d506a4121173b2ca015c15fad0cb257ec3e7cac

**Comment by molinch** [comment]
Seems like a Xamarin Forms bug that you "fixed" am I right ?
What does the Invalidate?

**Comment by daniel-luberda** [comment]
Of course. Invalidate is an Android method. If invalidate() gets called it tells the system that the current view has changed and it should be redrawn as soon as possible. Original Image renderer had an Invalidate override that skips Invalidate operation once after setting ImageSource. That was the cause why images didn't always reload when FAST scrolling. I just removed override and that's all.

About the hack that was removed:
I'm still thinking if we should merge it know, a lot of people still uses Xamarin.Forms 1.4.4 (I sent you a mail about it). The hack doesn't collide with anything. What do you think?

**Comment by molinch** [comment]
Thanks Daniel it's much clearer now.
I think it would be better to remove the hack and change nuspec. As you said the lib automatically auto cancels previous requests so it's quite safe to do so.

**Comment by daniel-luberda** [comment]
Ok, if canceling a lot of requests is fine, we could merge it. :) But don't change dependencies to XF >-1.5, 1.4 is fine too (it'll just cancel requests)

**Comment by molinch** [comment]
Fine for me!

**Comment by daniel-luberda** [comment]
Ok :)

**Comment by molinch** [comment]
New nuget pushed: https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/
Could you give it a try?

**Comment by daniel-luberda** [comment]
Working good. Can be closed :)
