### ISSUE TITLE
Malformed rounded image (RoundedTransformation)

### ISSUE THREAD

**Issue by davidtavarez** [molinch/FFImageLoading#62]
I'm using FFImageLoading.Transformations.RoundedTransformation to get circular image and is working, but the final rendering is malformed.
![simulator screen shot oct 15 2015 2 28 16 am](https://cloud.githubusercontent.com/assets/337107/10506364/311f210e-72e5-11e5-8f28-8415f00e267a.png)

ExampleFile: http://files.parsetfss.com/bac1c207-ac7e-428b-b7ab-ebd97e023c60/tfss-7340424e-9323-4b47-a727-4d62a279cff7-2015_10_01_014755.jpg

![screen shot 2015-10-15 at 2 29 00 am](https://cloud.githubusercontent.com/assets/337107/10506370/404cc500-72e5-11e5-90d0-9b6c740235ac.png)

**Comment by molinch** [comment]
We will need to investigate.

In case you want to have a look implementation for the circle transformation is here: [CircleTransformation](https://github.com/molinch/FFImageLoading/blob/master/FFImageLoading.Transformations.Droid/CircleTransformation.cs) which relies on [RoundedTransformation](https://github.com/molinch/FFImageLoading/blob/master/FFImageLoading.Transformations.Droid/RoundedTransformation.cs).

**Comment by daniel-luberda** [comment]
@davidtavarez  Can you try it without `DownsampleWidth` - `leave only `DownsampleHeight`? You don't need to set two properties. It downsamples one of the dimension, preserving aspect Ratio.

**Comment by daniel-luberda** [comment]
iOS transformations here, previous were for Android: 
[CircleTransformation.cs](https://github.com/molinch/FFImageLoading/blob/master/FFImageLoading.Transformations.Touch/CircleTransformation.cs)
[RoundedTransformation.cs](https://github.com/molinch/FFImageLoading/blob/master/FFImageLoading.Transformations.Touch/RoundedTransformation.cs)

**Comment by molinch** [comment]
@daniel-luberda Implementation is different on iOS
I wonder if we shouldn't try to have something more similar

**Comment by daniel-luberda** [comment]
We could. Will have to think about it, if you have some ideas, just write to me.

**Comment by davidtavarez** [comment]
I tried without downsampling the size. The Bitmap should be resize it properly.

Android
```csharp
public Bitmap ResizeImage (Bitmap sourceImage, float maxWidth = 800, float maxHeight = 600)
		{
			var maxResizeFactor = Math.Max (maxWidth / sourceImage.Width, maxHeight / sourceImage.Height);
			if (maxResizeFactor > 1)
				return sourceImage;
			var width = (int)(maxResizeFactor * sourceImage.Width);
			var height = (int)(maxResizeFactor * sourceImage.Height);

			var bitmapScalled = Bitmap.CreateScaledBitmap (sourceImage, width, height, true);
			return bitmapScalled;
		}

```

iOS
```csharp
public byte[] ResizeImage (byte[] sourceImage, float maxWidth = 400, float maxHeight = 300)
		{
			UIImage image = new UIImage (NSData.FromArray (sourceImage));
			var sourceSize = image.Size;
			var maxResizeFactor = Math.Min (maxWidth / sourceSize.Width, maxHeight / sourceSize.Height);
			if (maxResizeFactor > 1)
				return sourceImage;
			var width = (float)(maxResizeFactor * sourceSize.Width);
			var height = (float)(maxResizeFactor * sourceSize.Height);
			UIGraphics.BeginImageContextWithOptions (new SizeF (width, height), false, 2.0f);
			image.Draw (new RectangleF (0, 0, width, height));
			var resultImage = UIGraphics.GetImageFromCurrentImageContext ();
			UIGraphics.EndImageContext ();
			return resultImage.AsJPEG ().ToArray ();
		}
```

**Comment by daniel-luberda** [comment]
My proposal is to: 

- Add optional parameters widthAspectRation and heightAspectRatio for CircleTransformation and RoundedTransformation. With this, the transformation could be done to our desired size - eg. if we want to have rounded square but the image is rectangle we could pass 200, 200 and the image will clipped to desired aspect ratio. 
- Unify Android/iOS implementations (should work similar even without optional parameters. 

What do you think?

**Comment by molinch** [comment]
I think that we can have a helper method that accepts a couple of parameters but Transformations should remain easy to use.

So we could have:
* the helper method with some extra parameters, used only internally
* a CircleTransformation
* a CropCircleTransformation

Depending on the needs users could choose either CircleTransformation or CropCircleTransformation.

**Comment by daniel-luberda** [comment]
This is a nice idea but there should be at least something like AspectRatioRoundedTransformation. Use case: if we have a different sizes of images and have a rectangle container for an image and we know it's width/height. Without it it would be impossible to make unified rounding for those images (which have different sizes, so rounding without knowing aspect ratio will be different for every of them)

**Comment by daniel-luberda** [comment]
BTW: Actually CircleTransformation should be crop circle transformation by default in my opinion :) There's no point for having both. On the other hand CropRoundedTransformation and AspectRatioRoundedTransformation would be useful.

**Comment by davidtavarez** [comment]
What I think is something like CropCircleTransformation should by done by default.

**Comment by daniel-luberda** [comment]
What is better: 

- `RoundedTransformation` and `AspectRatioRoundedTransformation`
- `RoundedTransformation` with **optional** parameters (`widthAspectRatio`, `height AspectRatio`)

?

**Comment by davidtavarez** [comment]
I vote for RoundedTransformation with optional parameters.

**Comment by molinch** [comment]
I would prefer the same class but two constructors

**Comment by daniel-luberda** [comment]
Two constructors could actually be better than optional parameters. (Activator usage, etc). That's fine for me too.

**Comment by daniel-luberda** [comment]
Link: https://github.com/molinch/FFImageLoading/pull/63 Please test it.

**Comment by davidtavarez** [comment]
I can't test it... just try with this image http://files.parsetfss.com/bac1c207-ac7e-428b-b7ab-ebd97e023c60/tfss-7340424e-9323-4b47-a727-4d62a279cff7-2015_10_01_014755.jpg

**Comment by molinch** [comment]
I tested it with @davidtavarez image and it looks good to me. I will make an alpha nuget for the Transformations package

**Comment by molinch** [comment]
Alpha Nuget is here: https://www.nuget.org/packages/Xamarin.FFImageLoading.Transformations/1.1.8-alpha1

**Comment by davidtavarez** [comment]
Working good now :)
![screen shot 2015-10-16 at 10 00 07 am](https://cloud.githubusercontent.com/assets/337107/10543553/bddfdb8a-73ec-11e5-8eaa-02609d39c1b0.png)

**Comment by molinch** [comment]
Thanks Daniel you rock!
And thanks David for reporting this :)

**Comment by daniel-luberda** [comment]
FFImageLoading rocks! :P Glad it's working. I definitely not rock today. Just finished rollerblading. Result: hands and one knee teared of a lot. :P

**Comment by davidtavarez** [comment]
@daniel-luberda get well soon... there is a lot of work to do here :smile:

**Comment by daniel-luberda** [comment]
Thanks, I'm almost fine now. Made a new transformation. You can choose different style of every corner in image. https://github.com/daniel-luberda/FFImageLoading/commit/a50e006c1fe3ab93a855b68a24c4519aedbc67cc

![nexus 4 lollipop screenshot 10](https://cloud.githubusercontent.com/assets/13569983/10623705/a9012950-7791-11e5-8137-9e14bad5f79f.png)
