### ISSUE TITLE
IntoAsync weird work

### ISSUE THREAD

**Issue by DarthRamone** [molinch/FFImageLoading#7]
Why behaviour of IntoAsync so weird?
For example, if I use 

async Task<someImageView> Test()
{
  var someImageView = new UIImageView();
  await ImageService.LoadUrl(someURL).IntoAsync(someImageView);
  return someImageView;
}

When it loads image first time(doesn't matter from cache of internet) it works fine and returns value. But when I'm pushing this controller second time with calling this method - it stucks at IntoAsync and returns nothing. Return statement not reached.

I understand, that it's better to use Into() and define completion in .Success, but anyway, it's kinda weird.

**Comment by molinch** [comment]
Hi @DarthRamone 
That is now fixed in master branch, revision 62f69ec59c88f07906229ec02efff159b17dbd5e
I will update NuGet as soon as possible
