### ISSUE TITLE
Ability to invalidate cache

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#71]
It would be nice to have ability:

- to invalidate single cache entry for an item.
- to invalidate all cached images (clear all caches)

**Comment by molinch** [comment]
It would be nice if you could play with the new ImageService methods

**Comment by daniel-luberda** [comment]
Ok, I'll add them for Window too. What about Forms? What do you think about static methods:

- `CachedImage.ClearCache()`
- `CachedImage.RemoveKeyFromCache(string key)`

?

**Comment by molinch** [comment]
Fine for me. I still think that knowing from which cache it's removed would
make sense.
Most of the time you don't want to mess with disk cache

2015-11-20 13:49 GMT+01:00 Daniel Luberda <notifications@github.com>:

**Comment by daniel-luberda** [comment]
Ok, I can add an enum as a parameter :)

**Comment by daniel-luberda** [comment]
Done with https://github.com/molinch/FFImageLoading/commit/a52d91dd69e7488442fcd905f3c72499fe44855b https://github.com/molinch/FFImageLoading/commit/a1ccfa56679f4cefb1946390942fdcb662ff3929 https://github.com/molinch/FFImageLoading/commit/a2625c9321487026c41b0a3d91152339331eed70

**Comment by molinch** [comment]
That's great ! :+1:

**Comment by daniel-luberda** [comment]
Forgot to include Forms static methods for clearing cache. But I'll do it very soon :)

**Comment by kpespisa** [comment]
It doesn't appear the Forms static method for clearing cache ever made it in?

**Comment by molinch** [comment]
It did but we changed some parts to be in ImageService only.

So for Forms, if you invalidate a single image, then you can do it with the custom renderer static method:
https://github.com/luberda-molinet/FFImageLoading/blob/eb58e9d1fe95a9cf6f24db5fe5d7d9693e20c95c/source/FFImageLoading.Forms/CachedImage.cs#L576
Or directly with `ImageService.Instance`:
https://github.com/luberda-molinet/FFImageLoading/blob/017541135eba42fee001b11016556231e8524772/source/FFImageLoading.Common/Work/IImageService.cs#L125

And if you want to invalidate all images then you should use `ImageService.Instance` methods:
https://github.com/luberda-molinet/FFImageLoading/blob/017541135eba42fee001b11016556231e8524772/source/FFImageLoading.Common/Work/IImageService.cs#L125
