### ISSUE TITLE
Unexpected behaviour using Xamarin.Forms 2.0

### ISSUE THREAD

**Issue by davidtavarez** [molinch/FFImageLoading#72]
I just update to Xamarin.Forms 2.0 and I did migrate all my ListView constructors, now I'm experimenting an unexcpected result.

The video here (look at the right column): https://vid.me/jgfz

While is scrolling the image do not load. The first image loaded is repeated.

**Comment by daniel-luberda** [comment]
I do not understand what do you mean by "While is scrolling the image do not load. The first image loaded is repeated." Could you explain it in details?

**Comment by davidtavarez** [comment]
The same image is repeated, don't you see? And this was working perfectly with XF < 2.0

**Comment by daniel-luberda** [comment]
Do you use new Xamarin.ListView items recycling feature (ListViewCachingStrategy.RecycleElement)? If yes, you should update ImageSource inside ViewCell OnBindingContextChanged override.  Do you do that? 

> When the RecycleElement value is specified, OnElementChanged events are not raised when cells are recycled. Instead, the cell is retained and its property values change when the binding context is updated to that of an available cell, with OnElementPropertyChanged events then being raised.

**Comment by daniel-luberda** [comment]
@davidtavarez Any news?

**Comment by davidtavarez** [comment]
I'm changing some logic in my code, I'll post the results :)

**Comment by daniel-luberda** [comment]
Any news?

**Comment by daniel-luberda** [comment]
If you use new Xamarin.ListView items recycling feature (ListViewCachingStrategy.RecycleElement), then it's not a FFImageLoading specific behavior. You shouldn't use bindings, instead inside ViewCell OnBindingContextChanged override you should do:

- clear, reapply transformations, cached image properties, etc, etc
- **after that** update ImageSource

**Comment by daniel-luberda** [comment]
Hi @davidtavarez. Do you still experience those issues?

**Comment by davidtavarez** [comment]
Yes, but I will find a solution soon.

**Comment by daniel-luberda** [comment]
@davidtavarez Any news? Did you try the latest alpha6?

**Comment by davidtavarez** [comment]
@daniel-luberda I found it! on the next comment and is nothing with the CachedImage. Please, close this issue when I post the details.

**Comment by daniel-luberda** [comment]
Ok, if it's not FFImageLoading issue, I am closing it. Luckily, it looks like there are no more bugs to fix for the stable release! :P Thanks!
