### ISSUE TITLE
Nuget Package targeting PCL Profile259?

### ISSUE THREAD

**Issue by mariusmuntean** [molinch/FFImageLoading#75]
We'd like to use FFImageLoading in our project that targets PCl Profile259[Xamarin.Forms 2.0].
Unfortunately your Nuget package targets Profile111 and hence we cannot use it. 

Do you have a reason for targeting the Nuget package to Profile111? Do you plan to also provide one that targets Profile259?

**Comment by daniel-luberda** [comment]
No I haven't any reason, I added those packages few days ago, I just missed that. If you test Windows FFImageLoading and have any issues or suggestions just write to me: danlub01(at) gmail.com

**Comment by mariusmuntean** [comment]
We've compiled the Forms PCL targeting Profile259 and referenced the .DLL in our PCL project (in our Android and iOS projects we added the Nuget packages) and until now it works flawlessly(Scrolling in a ListView is now much smoother).

It would be cool if you could update the .nuspec file and re-release the Nuget packages so we can reference them instead of our compiled .DLL

**Comment by daniel-luberda** [comment]
@mariusmuntean Nice to hear that. Could you tell me what projects had to be changed to profile 259?

As to nuget - I'll do that soon too. 

Thanks,
Daniel

**Comment by mariusmuntean** [comment]
Your PCL project already targets Profile259. You don't have to change there anything.

The Nuget package you published seems to target Profile111 but PCL Profile259 targets portable45-net45+win8+wp8+wpa81. Updating the .nuspec file should be enough.

**Comment by daniel-luberda** [comment]
@mariusmuntean Thanks for the info. It'll definitely speed things up.

**Comment by daniel-luberda** [comment]
https://github.com/molinch/FFImageLoading/pull/77

**Comment by daniel-luberda** [comment]
### FFImageLoading v2.0.0-alpha1 nuget released
https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/2.0.0-alpha1
https://www.nuget.org/packages/Xamarin.FFImageLoading.Transformations/2.0.0-alpha1

Can you try it?

**Comment by mariusmuntean** [comment]
Hi Daniel,

I just replaced the self-compiled .DLLs from my PCL project with the Nuget Package v2.0.0-alpha1 and it works just fine.
The Profile is fine and after ~1 hour of testing I haven't found any problems.

Thanks a lot!

**Comment by daniel-luberda** [comment]
Thanks!
