### ISSUE TITLE
Shared Project nugetpackage is not installable for Xamarin.Forms

### ISSUE THREAD

**Issue by TMNDevelop** [molinch/FFImageLoading#79]
Hello,
after trying to install in a deviceless surrounding (I use this project to share the Xamarin.Forms stuff)

The following Error comes up:
Adding 'Xamarin.FFImageLoading.Forms 1.1.7.2' to Firmeo.UI.
Could not install package 'Xamarin.FFImageLoading.Forms 1.1.7.2'. You are trying to install this package into a project that targets 'portable-net45+win+wpa81+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is it possible to install it in this kind of projects? In the samples it looks like it should...

Thanks,
Gerhard

**Comment by daniel-luberda** [comment]
Hi..

Yes, it's possible but we didn't release updated nuget yet. You can clone repo by yourself and build it or wait for a new nuget release (it's quite a major one), so we have to test some things first. 

Here are the updated files for building nugets: https://github.com/molinch/FFImageLoading/pull/77

**Comment by daniel-luberda** [comment]
### FFImageLoading v2.0.0-alpha1 nuget released
https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/2.0.0-alpha1
https://www.nuget.org/packages/Xamarin.FFImageLoading.Transformations/2.0.0-alpha1

Can you try it?
