### ISSUE TITLE
Transformation Randomly Occurs In Cell without transformation

### ISSUE THREAD

**Issue by highplains** [molinch/FFImageLoading#81]
I'm not sure how to recreate this, and it happens almost randomly.
Here is a screen shot showing a ListView in Forms with a cell that does not have transformations applied.
Could this be an issue of how Forms handles cell reuse?

![img_2133](https://cloud.githubusercontent.com/assets/1825076/11515301/7e4f47c2-983a-11e5-871c-e45f037abbb2.PNG)

**Comment by daniel-luberda** [comment]
Do you use new Xamarin.ListView items recycling feature (ListViewCachingStrategy.RecycleElement)? If yes, inside ViewCell OnBindingContextChanged override you should do:

- clear, reapply transformations, cached image properties, etc, etc
- *after that* update ImageSource

See this: https://github.com/molinch/FFImageLoading/issues/72

**Comment by highplains** [comment]
I'm using the default ListViewCachingStrategy not the RecycleElement.

**Comment by daniel-luberda** [comment]
- Did you mean ListViewCachingStrategy.RetainElement? If yes, that could be a bug. 
- Is `Transformations` property binded to something? Or it doesn't change at all?

**Comment by highplains** [comment]
Yes im using RetainElement. The weirdest part is that there is no code in that Cell that has to do with transformations. I couldn't believe it when I saw it behave like that because it made no sense.

Here is a screenshot of the only code that touches the control.

![screen shot 2015-12-01 at 3 27 12 pm](https://cloud.githubusercontent.com/assets/1825076/11516379/1469ab44-9840-11e5-94c6-fd2e084f82f9.png)

**Comment by highplains** [comment]
Also a side note... The screenshot was showing the same image over and over when it should have been different.

**Comment by daniel-luberda** [comment]
It's always important to have `Transformations` property changed **before** ImageSource. I'm not sure if Xamarin.Forms preserves that order when using bindings. You could try to switch from bindings to `OnBindingContextChanged` override and see if that would help - if yes, it's a Xamarin.Forms binding issue.

**Comment by daniel-luberda** [comment]
So... that's a really strange one... I don't have a clue how it's possible. Are you sure that you create a new CachedImage instance in ViewCell contructor for every cell?

**Comment by highplains** [comment]
Positive. I'll let you know if i figure out a way to recreate it.

**Comment by daniel-luberda** [comment]
Ok :)

**Comment by daniel-luberda** [comment]
@highplains Does this bug still apply to 2.0.0-alpha3?

**Comment by highplains** [comment]
So hard to reproduce i'm really not sure. Feel free to close this out
though.

**Comment by daniel-luberda** [comment]
Ok :) BTW: That could be also a Forms renderer bug. I released alpha4 with some stability improvements. If you'll experience it once again - feel free to reopen this bug. We'll try to find out what's causing this bug. Thanks.

**Comment by molinch** [comment]
Btw, if there is a memory issue then transformation won't be applied (since it consumes even more memory)
