### ISSUE TITLE
Clear cache image on Xamarin Forms (PCL)

### ISSUE THREAD

**Issue by luonganhtuanTMA** [molinch/FFImageLoading#83]
Dear All,
I saw static method ClearCache for CachedImage in source code for Xamarin Forms.
But when I can't using it for my project.
I'm using the latest one in nuget:
Xamarin.Forms NuGet package: https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/
Please help!

**Comment by molinch** [comment]
Can you try Alpha Forms package?
https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/2.0.0-alpha1

**Comment by luonganhtuanTMA** [comment]
Thanks @molinch 
I'll try it!

**Comment by daniel-luberda** [comment]
As @molinch said - it works starting from 2.0.0-alpha1.

**Comment by luonganhtuanTMA** [comment]
@molinch @daniel-luberda 
I got this bug in latest version 2.0.7.1 for Xamarin Forms.
I had a profile picture that user can override by uploading another. 
The URL to profile picture haven't changed. 
So I tried to clear cache after uploading new profile picture then reloaded but the old image still showed up.
I did try all following methods but not working:
await CachedImage.ClearCacheAsync (CacheType.All);
await CachedImage.InvalidateCacheEntryAsync (patient.ImageUrl, CacheType.All);
CachedImage.InvalidateCache (profileImg.Source, CacheType.All);
What can I do to solve my problem?
Please help!

**Comment by daniel-luberda** [comment]
@luonganhtuanTMA If you're using downsampling or custom transformations, use another override: 

`await CachedImage.InvalidateCacheEntryAsync (patient.ImageUrl, CacheType.All, removeSimilar: true);`

Did you try it?

**Comment by luonganhtuanTMA** [comment]
@daniel-luberda Yep, I just gave a try but it didn't work.
The "key" that you use to cache image is the url, isn't it?
Here is my code:
`public class CircleImage : CachedImage
	{
		public CircleImage ()
		{
			Transformations = new System.Collections.Generic.List<FFImageLoading.Work.ITransformation> {
				new CircleTransformation ()	
			};
			CacheDuration = TimeSpan.FromDays (1);
		}
	}`

After upload image to S3, I tried to clear cache by
`await CachedImage.InvalidateCacheEntryAsync (patient.ImageUrl, CacheType.All, removeSimilar: true);`

**Comment by molinch** [comment]
@luonganhtuanTMA I just checked it and for me it works so that's quite strange :(

Yes if you give the URL then it should clear all caches with the method:
```c#
await CachedImage.InvalidateCacheEntryAsync (patient.ImageUrl, CacheType.All, removeSimilar: true);
```

**Comment by daniel-luberda** [comment]
@molinch Do you use new disk cache or the old one (with journal)?

**Comment by daniel-luberda** [comment]
https://github.com/molinch/FFImageLoading/commit/0ede6b614f7351b997355ce584e909d6628d9ea0

**Comment by molinch** [comment]
I tried & fixed both but what I fixed was unrelated to this issue.

**Comment by vijayMmenlo** [comment]
I am also facing this issue. what @luonganhtuanTMA got. 
I am just using profile pic and trying to update but it's updating when it comes to the profile screen for the next time. Clearing cache not working for me.  I am using below code.
  **await CachedImage.InvalidateCache(rootObj.data.patron_photo_thumb_url, FFImageLoading.Cache.CacheType.All, removeSimilar: true);**
 And using the latest version v2.2.9.

Can any one help me on this issue.
