### ISSUE TITLE
Android transformations ignore TransparencyEnabled

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#84]
```C#
if (!ImageService.Config.LoadWithTransparencyChannel || Parameters.LoadTransparencyChannel == null || !Parameters.LoadTransparencyChannel.Value)
{
	// Same quality but no transparency channel. This allows to save 50% of memory: 1 pixel=2bytes instead of 4.
	options.InPreferredConfig = Bitmap.Config.Rgb565;
}
```

Android transformations ignore TransparencyEnabled property if new bitmap is created. How could we use it inside some transformations to save memory? Should we modify Transform method to pass also task parameters?

**Comment by molinch** [comment]
We should definitely pass this parameter :)

**Comment by daniel-luberda** [comment]
Ok :) just, let me know - I could modify transformations then.

**Comment by molinch** [comment]
Damn it took me more time than expected because some transformations NEED to have Alpha transparency :)

**Comment by daniel-luberda** [comment]
Cool! :) I think we can close it :)
