### ISSUE TITLE
Retrieving image first time fails

### ISSUE THREAD

**Issue by KroanNL** [molinch/FFImageLoading#86]
When I use the following code:

`ImageService.LoadUrl(newsItem.ImageUrl)
.Success(() =>
{ })
.Error(exception =>
{ })
.Into(iconImageView);`

The code will not go into success, but into the Error-[art the first time I call it. Once I call the same code for the same url thereafter (even after restart) the required image is shown. Removing the app from the device and then running it again will result again in first-time error.

The url of the image has no file-extension (so basically "https://domain.com/image"). My guess is that this causes the problem somewhere in the code.

(Also there is a problem that the ImageService is looking for a "loader_img" file in the bundle, which is not included apparently. Including this yourself, does not fix the problem above).

**Comment by daniel-luberda** [comment]
Hi @KroanNL 

- What version of FFImageLoading? Did you try 2.0.0-alpha4? 
- `Error` returns an exception. Could you give it to us? (message and stack trace)
- `loader_img` - I don't think there's a hardcoded file anywhere in FFImageLoading. Are you sure it isn't your code which sets it?

**Comment by KroanNL** [comment]
You are correct. The loader_img was actually in my storyboard. I forgot about it somehow hah!

Here is the requested info:
`{System.Exception: FFImageLoading is unable to generate image.}
	Data: Count = 0
	HResult: -2146233088
	HelpLink: (null)
	InnerException: (null)
	Message: "FFImageLoading is unable to generate image."
	Source: (null)
	StackTrace: (null)
	TargetSite: (null)
	Non-public members: `

Unfortunatly no stack trace as you can see :(

**Comment by daniel-luberda** [comment]
Ok. 2.0.0 will go stable soon. I think we can close the issue if it's fixed :) Feel free to reopen it if you experience it once again.
