### ISSUE TITLE
Resolution / Pixelation after upgrading to latest alphas

### ISSUE THREAD

**Issue by highplains** [molinch/FFImageLoading#87]
I'm not using any downsampling. Here is the code relating to the CachedImage

```
            ProfileImage.LoadingPlaceholder = Device.OnPlatform<string>("missingprofile.png", "2130837648", "");
            ProfileImage.ErrorPlaceholder = Device.OnPlatform<string>("missingprofile.png", "2130837648", "");
            ProfileImage.CacheDuration = TimeSpan.FromDays(30);
            ProfileImage.RetryCount = 2;
            ProfileImage.TransparencyEnabled = false;
```

This is the resulting image after updating the nugets tot he latest alphas
![screen shot 2015-12-09 at 1 09 35 pm](https://cloud.githubusercontent.com/assets/1825076/11697289/220ce07c-9e76-11e5-9d4b-5a2c06696356.png)

Image after downgrading the nugets back to Stable....
![screen shot 2015-12-09 at 1 13 44 pm](https://cloud.githubusercontent.com/assets/1825076/11697418/b939d0b8-9e76-11e5-8e62-4a8c49b40e19.png)

**Comment by daniel-luberda** [comment]
Hi @highplains  Can you PM me a url of the image?

**Comment by highplains** [comment]
Sent to your gmail.

**Comment by daniel-luberda** [comment]
@highplains I debugged it and I'm quite sure you have downsampling to a very small size enabled somewhere. For me, all is working fine! Screenshot.

BTW: This image is VERY large. I strongly advice to use `DownsampleToViewSize=true` on `CachedImage` - you won't loose image quality but app should be a lot more responsive. 
![ios simulator screen shot 10 gru 2015 03 44 10](https://cloud.githubusercontent.com/assets/13569983/11705551/1496a2a4-9ef1-11e5-91b2-5815d524580a.png)

**Comment by molinch** [comment]
Daniel couldn't it come from  a transformation since now we use 8bit when
possible ?

Le jeudi 10 décembre 2015, Daniel Luberda <notifications@github.com> a
écrit :

**Comment by daniel-luberda** [comment]
@molinch Hi Fabien. It's on iOS, so it can't be related :)

**Comment by molinch** [comment]
Valid point!

2015-12-10 7:43 GMT+01:00 Daniel Luberda <notifications@github.com>:

**Comment by highplains** [comment]
I'm not using a transformation or Down sampling on that image.

**Comment by daniel-luberda** [comment]
I couldn't reproduce it, all is working fine. Can you send a reproduction? Please also note, that older stable versions didn't have iOS downsampling, so you wouldn't notice even if it was enabled. After update, when the feature was added - it just started to work. Are you sure it isn't the case?

**Comment by daniel-luberda** [comment]
@molinch User sent me this info (PM).

**Comment by highplains** [comment]
OK I think I know why this is happening to me.
So I have a list view that downsamples the images to thumbnail sizes roughly 60x60
![screen shot 2015-12-10 at 10 03 30 am](https://cloud.githubusercontent.com/assets/1825076/11722342/6b91cc8a-9f25-11e5-8abb-d57e57ffb23b.png)

This image I think is then being cached at the 60x60 size so when i click on the profile picture to open up the next screen which contains a CachedImage using the same URL but in a bigger size, I think it is loading up the downsampled image from the cache. (Notice the blur)

![screen shot 2015-12-10 at 10 05 45 am](https://cloud.githubusercontent.com/assets/1825076/11722382/98ef2b32-9f25-11e5-8fdb-55c68a71fe2d.png)


When i turn downsampling off on the listview the image loads properly in the profile view.

**Comment by daniel-luberda** [comment]
Ok. Got it :) If it's that, it won't be hard to fix. I'll let you know when it's fixed. Thanks!

**Comment by highplains** [comment]
Thanks!

**Comment by daniel-luberda** [comment]
Fixed

**Comment by highplains** [comment]
This gonna end up in a Nuget anytime soon?

**Comment by molinch** [comment]
Perfect fix @daniel-luberda that's definitely the way to do it ;)

**Comment by daniel-luberda** [comment]
@highplains I'll make a nuget alpha6 soon.
