### ISSUE TITLE
Windows Phone loads the image just the first time

### ISSUE THREAD

**Issue by fedemkr** [molinch/FFImageLoading#89]
Hi, I'm having trouble loading an image from Url  in Windows Phone using FFImageLoading.WIndows 2.0.0-alpha6.
The problem is that it loads the image just the first time I run the app, but if I open it up again, the image doesn't load. The only way it reappears is to uninstall the app and run it again.

The code:

        <ff:FFImage
            Name="image"
            VerticalAlignment="Stretch" 
            HorizontalAlignment="Stretch"
            LoadingPlaceholder="/Assets/combined_logo.png"
            CacheDuration="1"
            RetryCount="3"
            RetryDelay="250"
            DownsampleHeight="300"
            Source="http://imagenes.es.sftcdn.net/es/scrn/76000/76818/microsoft-small-basic-22.jpg">
        </ff:FFImage>

**Comment by daniel-luberda** [comment]
@fedemkr That was a disk cache initialization problem. It's fixed now. I'll try to release a nuget soon (2.0.0-alpha6fix). Thanks!

**Comment by daniel-luberda** [comment]
https://www.nuget.org/packages/FFImageLoading.Windows/2.0.0-alpha6fix

**Comment by daniel-luberda** [comment]
@fedemkr Did it work for you?

**Comment by fedemkr** [comment]
It works perfectly. Thank you very much. :+1:
