### ISSUE TITLE
Get image dimensions after dowloading

### ISSUE THREAD

**Issue by wsvdmeer** [molinch/FFImageLoading#9]
Is there a way to get the original image dimensions after downloading the image?

    ImageService.LoadUrl(url).Success(() => {
              //GET ORIGINAL SIZE
     }).Into(positionImage);

I need it to show markers on top of the imageview

**Comment by molinch** [comment]
That is something I can easily implement. I will keep you updated.

**Comment by molinch** [comment]
It has been implemented in this commit https://github.com/molinch/FFImageLoading/commit/c9c91a5e1f5a62f0c61a2df5818ecce93452bac7

There is now an extra Success method that allows an Action<int, int> as the callback. As you can imagine first parameter is the width, then the height.
It is not yet on NuGet though. Could you make a feedback?

**Comment by molinch** [comment]
This is now on NuGet so I close the task

**Comment by wsvdmeer** [comment]
Sorry for the late response but it works perfectly!
