### ISSUE TITLE
Possible Android cache bug

### ISSUE THREAD

**Issue by daniel-luberda** [molinch/FFImageLoading#91]
Didn't have much time to debug it, but it looks like we've got some bug when using transformations on Android. 

I added new CropTransformation with a demo: https://github.com/molinch/FFImageLoading/commit/cd196c8c3a20a5ba7d77b42049c9de8070edeed9

- Run sample Xamarin.Forms app
- Open CropTransformation demo
- Try to zoom in / zoom out few times
- After a few transformation you'll get blank image and probably some ffimageloading threads have deadlocks (`Transform` method is not executed)
- on iOS it works fine!

It doesn't matter if another transformation type is used here. All transformations have the same unexpected behavior.

![ios simulator screen shot 15 gru 2015 23 21 46](https://cloud.githubusercontent.com/assets/13569983/11826139/b46d6970-a383-11e5-8a66-c935c7b0230f.png)
![ios simulator screen shot 15 gru 2015 23 21 54](https://cloud.githubusercontent.com/assets/13569983/11826138/b46cb7e6-a383-11e5-89c0-9883f6e236d5.png)
![screen shot 2015-12-15 at 23 30 12](https://cloud.githubusercontent.com/assets/13569983/11826180/f7ca7118-a383-11e5-9030-af356eada09f.png)
![screen shot 2015-12-15 at 23 30 26](https://cloud.githubusercontent.com/assets/13569983/11826182/f7ce1534-a383-11e5-9660-a75c1f46d937.png)
![screen shot 2015-12-15 at 23 30 33](https://cloud.githubusercontent.com/assets/13569983/11826181/f7ccf546-a383-11e5-940e-6eb6b59701e7.png)

**Comment by molinch** [comment]
I don't have any issue with any transformation: I just tested. Therefore with CropTransformation there is a dezoom issue when image is taken from cache though.

**Comment by daniel-luberda** [comment]
It's not only with CropTransformation. If you use any other transformation in that example the issue is the same. Any clues what that could be? The issue is only on Android.

**Comment by daniel-luberda** [comment]
@molinch It's caching problem. If I change Key property to: 
```
		public override string Key
		{
			get { return Guid.NewGuid().ToString(); }
		}
```

... everything works fine! Any clues?

**Comment by molinch** [comment]
Fixed

2015-12-16 3:28 GMT+02:00 Daniel Luberda <notifications@github.com>:

**Comment by daniel-luberda** [comment]
Superb! That was a hard one I think :)

**Comment by molinch** [comment]
Yes it was a lot of pain!
Btw this issue happened because two requests were done almost at same time: one succeeded, one got cancelled as expected. But then cancellation code was buggy.

Now it works but we still have two requests done (this part is strange).

**Comment by daniel-luberda** [comment]
Yes! That's because of Xamarin.Forms bug (duplicating propertychanged calls), we deleted the fix, but samples use older Forms version. I'm going to update to Xamarin.Forms 2.0 but only after they will release a stable release... current has a lot of bugs.
