### ISSUE TITLE
Windows Phone does not load ErrorPlaceholder image when Source null or empty

### ISSUE THREAD

**Issue by fedemkr** [molinch/FFImageLoading#92]
Hi, it's me again. I'm currently using version FFImageLoading.Windows 2.0.0-alpha6fix and when the Source is null or empty the control does not load the Error Placeholder image.
In the other platforms (iOS & Android) works perfectly but in WP does that. Am I missing something?

The code:

    <ff:FFImage Name="image"
                                    Grid.Row="0" Grid.Column="0" Grid.RowSpan="2" 
                                    VerticalAlignment="Center"
                                    HorizontalAlignment="Stretch"
                                    Width="60"
                                    Height="60"
                                    Margin="3"
                                    LoadingPlaceholder="ic_defaultuser.png"
                                    ErrorPlaceholder="ic_defaultuser.png"
                                    CacheDuration="30"
                                    RetryCount="3"
                                    RetryDelay="250"
                                    DownsampleToViewSize="True"
                                    Source="{Binding Path=UserImagePath, Mode=OneWay}">
    </ff:FFImage>

Thanks.

**Comment by daniel-luberda** [comment]
Hi @fedemkr,

I don't really understand why would you want to load an error placeholder if the source is null? Null source means you want to clear the view. It's not possible to get error when setting null as a source. Could you elaborate? 

Thanks,
Daniel

**Comment by daniel-luberda** [comment]
Also you could make a custom `Source ` value converter which replaces `null` `UserImagePath` strings with a default `ic_defaultuser.png` for that.

**Comment by fedemkr** [comment]
@daniel-luberda Thanks for your quick answer and I was thinking about the converter to solve this. But when source is Empty should the control also clear the view? If so I'm on my way to create the converter :+1:

**Comment by daniel-luberda** [comment]
Do you mean source is `string.Empty`? Currently, View is cleared when a source is `null`.

**Comment by fedemkr** [comment]
Yes, I'm binding against UserImagePath, and when the user does not have an image, that property is set to `string.Empty` . In that case, should the control show the ErrorPlaceholder or clear the view?

**Comment by fedemkr** [comment]
The converter worked perfectly. Thank you very much for the help :+1:
