### ISSUE TITLE
Error: System.Net.WebException: Aborted

### ISSUE THREAD

**Issue by Rajeshr34** [molinch/FFImageLoading#93]
I am getting this error every time 
```System.Net.WebException: Aborted.```

```c#
using FFImageLoading.Views;
using FFImageLoading.Transformations;
public static class classname {
    public static void InsertImage(Context context, FFImageLoading.Views.ImageViewAsync imagevew, string url)
    {
        ImageService.LoadUrl(url).Into(imagevew); // xamarin stops here shows the error
    }
}
```

**Comment by molinch** [comment]
You have activated break on all exceptions I think.
So if your image cannot be loaded this is the expected behaviour.

**Comment by Rajeshr34** [comment]
Images are loading. Problem is when i play with the application like going to another activity and when i come back to old activity after some time it triggers the error.

**Comment by molinch** [comment]
Does it crash the app?
If not it's expected behaviour: you must have all exceptions turned on.

**Comment by Rajeshr34** [comment]
I have turned all the exceptions. yes it crashes the app.

**Comment by molinch** [comment]
Ok thanks for the info.
Could you send us a sample that reproduces this? It should be easy to fix once we get it.

**Comment by molinch** [comment]
@Rajeshr34 I will close this issue now. If you have more feedback please create a new one. Thanks.
