### ISSUE TITLE
Images load very slow on slower devices

### ISSUE THREAD

**Issue by ahohns** [molinch/FFImageLoading#97]
Testing on a slow phone with what seems to be a much slower disk (slow write speeds) results in very slow image loading. With lots of images loading at once on first load (and when scrolling through new list items with images) it causes images to load in order quite a bit more slowly compared to newer/faster phones. This was noticed last week using alpha-6 and also this week using 2.0.0.  Is it possible images are only returned once they've been written to disk? If not already, is it possible to return the image to be processed/displayed either before or during disk write?

**Comment by daniel-luberda** [comment]
Yes. The image is updated after it's written to the disk. See: https://github.com/molinch/FFImageLoading/blob/d4182ea84c688eb7a3d1abc9c9d0b236dfe71c75/source/FFImageLoading.Shared/Cache/DownloadCache.cs#L94

There's also a lock which forces only one file writing operation at a time. That could be it. https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Shared/Cache/DiskCache.cs#L221 

It's faster to queue file writes. Although, on slow devices that could be a problem. @molinch @ahohns  Do you have any suggestions?

**Comment by daniel-luberda** [comment]
SemaphoreSlim fileWriteLock supports setting timeout. Maybe we could set some timeout to allow multiple file writes after specified time?

**Comment by molinch** [comment]
Please wait before changing anything here @daniel-luberda. I would like to check a few things

**Comment by david-pershouse** [comment]
Maybe create a new memory stream after downloading using getbuffer and the new memorystream(byte[],offset,count) constructor (to share memory) and then skip await on save to disk (pass it the new memory stream) since even if we can't cache to disk, we probably are happy with downloaded file

**Comment by daniel-luberda** [comment]
@molinch Ok. I'm currently quite busy, so I can't do anything now. You could check that. 

+1 for @david-pershouse idea

**Comment by molinch** [comment]
So to sum it up:
- we need a queue where disk writes gets queued
- there is one entry of the queue processed at a time
- if an item with the same key exists in the queue, or in the disk cache, then we should just skip it
- Thread pool tasks or a dedicated thread. Ideally I would rather use the thread pool.

**Comment by daniel-luberda** [comment]
@molinch  Are you sure we need a queue. Maybe SemaphoreSlim is enough. We only need to move it to the async task which is not awaited. And that should be all. All in all FFImageloading deduplicates similar requests.

**Comment by molinch** [comment]
If we want non blocking writes then yes it is needed

**Comment by daniel-luberda** [comment]
What about this (psuedocode): 
```
var stream = new Stream();
var streamCopy = stream.Copy(); 

// it's non-blocking
var task = Task.Run(async () => {
  await semaphore.WaitAsync();
  await DoTheFileWrite(streamCopy);
  semaphore.Release();
})

return stream;
```

**Comment by daniel-luberda** [comment]
I tried this approach. Works good! Take a look:

### DownloadCache.cs

```C#
private async Task<MemoryStream> DownloadAndCacheAsync(string url, string filename, string filepath, CancellationToken token, TimeSpan? duration)
{
	if (duration == null)
		duration = new TimeSpan(30, 0, 0, 0); // by default we cache data 30 days

	int headersTimeout = ImageService.Config.HttpHeadersTimeout;
	int readTimeout = ImageService.Config.HttpReadTimeout - headersTimeout;

	var cancelHeadersToken = new CancellationTokenSource();
	cancelHeadersToken.CancelAfter(TimeSpan.FromSeconds(headersTimeout));
	var linkedHeadersToken = CancellationTokenSource.CreateLinkedTokenSource(token, cancelHeadersToken.Token);

	using (var response = await DownloadHttpClient.GetAsync(url, HttpCompletionOption.ResponseHeadersRead, linkedHeadersToken.Token).ConfigureAwait(false))
	{
		if (!response.IsSuccessStatusCode || response.Content == null)
			return null;

		var cancelReadToken = new CancellationTokenSource();
		cancelReadToken.CancelAfter(TimeSpan.FromSeconds(readTimeout));

		var responseBytes = await response.Content.ReadAsByteArrayAsync();
		var memoryStream = new MemoryStream(responseBytes, false);
		var fileWriteStream = new MemoryStream(responseBytes, false);

		memoryStream.Position = 0;
		fileWriteStream.Position = 0;

		var nonBlockingTask = _diskCache.AddOrUpdateAsync(filename, fileWriteStream, token, duration.Value).ConfigureAwait(false);

		memoryStream.Position = 0;
		return memoryStream;
	}
}
```

### DownloadCache.cs

```C#
public async Task AddOrUpdateAsync (string key, Stream stream, CancellationToken token, TimeSpan duration)
{
	key = SanitizeKey (key);

	bool existed = entries.ContainsKey (key);
	string filepath = Path.Combine(basePath, key);

	try
	{
		await fileWriteLock.WaitAsync();
		using (stream)
		{
			using (var fs = FileStore.GetOutputStream(filepath))
			{
				await stream.CopyToAsync(fs, BufferSize, token).ConfigureAwait(false);
			}	
		}
	}
	finally
	{
		fileWriteLock.Release();
	}
		
	AppendToJournal (existed ? JournalOp.Modified : JournalOp.Created,
		key,
		DateTime.UtcNow,
		duration);
	entries[key] = new CacheEntry (DateTime.UtcNow, duration);
}
```

**Comment by daniel-luberda** [comment]
Should I commit this?

**Comment by molinch** [comment]
Please don't. It needs to be tested against big lists first and ideally on devices with slow writes (we can simulate it with a delay).

**Comment by daniel-luberda** [comment]
Ok, let me know about the results if you do some tests :)

**Comment by daniel-luberda** [comment]
BTW: I don't think passing cancellation token to: `var nonBlockingTask = _diskCache.AddOrUpdateAsync(filename, fileWriteStream, token, duration.Value).ConfigureAwait(false);` is a good thing, if the file was downloaded it should be saved anyway.

**Comment by molinch** [comment]
I agree even though writing to disk may slow down other operations. So that's the only negative effect, and why in the first place I passed the token.

We would go for the change you propose, without a queue, therefore I still think we need a list that stores pending writes:
- If a file is pending for write then we shouldn't rewrite it (so we should stop any future write request for the same URL)

**Comment by daniel-luberda** [comment]
@molinch Ok, I could make a commit with those changes (already using it when testing and there're no bugs). We could use a ConcurrentDictionary<string, Task> and check if key exists before running a new task and after write is removed from it. What do you think?

**Comment by molinch** [comment]
Sounds good for me!

**Comment by daniel-luberda** [comment]
Updated, non-blocking disk cache implementations which I was testing since a few days: 
- iOS/Android: https://github.com/molinch/FFImageLoading/commit/a5cb2f965736bea145d6c2fafb65612a72a16735
- Windows: https://github.com/molinch/FFImageLoading/commit/82c9bf40cc9ee9a6818a18e5bfc40b4a38712d90

@molinch Do you accept it?

**Comment by daniel-luberda** [comment]
https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/2.0.1-alpha1

**Comment by molinch** [comment]
@daniel-luberda It's really nice. I have made a few changes in a00ee637c62a9aaf7c2798e148b9b6c694296a9e

**Comment by daniel-luberda** [comment]
@molinch As all work is done we could do some tests. I'm having some strange debug info on Windows when testing HeavyList:

```
Similar request finished but the image is not in the cache: https://farm8.staticflickr.com/7635/16823997277_9455dc4df1_z_d.jpg;CircleTransformation;0x140
Exception thrown: 'System.Exception' in FFImageLoading.Windows.DLL
Similar request finished but the image is not in the cache: https://farm8.staticflickr.com/7635/16823997277_9455dc4df1_z_d.jpg;CircleTransformation;0x140
Exception thrown: 'System.Exception' in FFImageLoading.Windows.DLL
Exception thrown: 'System.Exception' in FFImageLoading.Windows.DLL
Similar request finished but the image is not in the cache: https://farm8.staticflickr.com/7236/7171671407_1671ccd763_z_d.jpg;CornersTransformation,cornersSizes=50,50,50,50,cornersTransformType=RightRounded,cropWidthRatio=1,cropHeightRatio=1,;0x140
Similar request finished but the image is not in the cache: https://farm8.staticflickr.com/7236/7171671407_1671ccd763_z_d.jpg;CornersTransformation,cornersSizes=50,50,50,50,cornersTransformType=RightRounded,cropWidthRatio=1,cropHeightRatio=1,;0x140
```

But all in all, everything works just fine. What that could be?

**Comment by molinch** [comment]
Do you have it on Android too?

**Comment by daniel-luberda** [comment]
No, only on Windows.

**Comment by molinch** [comment]
Could you debug with all exceptions turned on so we know what happens?

**Comment by daniel-luberda** [comment]
Sure

**Comment by daniel-luberda** [comment]
```
Exception thrown: 'System.Exception' in FFImageLoading.Windows.DLL

Additional information: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))
```

```
Parameters.OnSuccess(new ImageSize(value.PixelWidth, value.PixelHeight), LoadingResult.MemoryCache);
```

I have to dig into it.

**Comment by molinch** [comment]
Almost sure it's ConfigureAwait(false) changes that did this.
Not sure which one since I cannot test

**Comment by daniel-luberda** [comment]
It isn't, I rolled back and it's still there. But the fix was really easy :) https://github.com/molinch/FFImageLoading/commit/5ed1f804065763b137e8d35d80b67b655dfef97a

**Comment by daniel-luberda** [comment]
Oh no, it isn't fixed. There are more exceptions. I'll try to work on that.

**Comment by daniel-luberda** [comment]
Oh no, it isn't fixed. Still getting `Similar request finished but the image is not in the cache`. I'll try to work on that.

**Comment by daniel-luberda** [comment]
Ok, I'll mail it to you when it's fixed. Caching works good. It's because of exceptions. I need to make more changes similar to: https://github.com/molinch/FFImageLoading/commit/5ed1f804065763b137e8d35d80b67b655dfef97a (there are more places where it's need to be rewritten)

**Comment by molinch** [comment]
@ahohns Could you give a feedback? Btw nugets have been updated and include these fixes.

**Comment by ahohns** [comment]
On holidays until Monday, home pc not set up to do any development
currently so won't be able to test until next week.

**Comment by ahohns** [comment]
Seems a lot better on the slower device, thanks!
