### ISSUE TITLE
change copytoasync default buffer size to match .net 4.5

### ISSUE THREAD

**Issue by david-pershouse** [molinch/FFImageLoading#99]
MS changed the default buffer size in 4.5 claiming improved performance. Maybe we should do the same: 
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L48

**Comment by molinch** [comment]
I wonder if we can find the `large object heap threshold` used on Xam.iOS and Xam.Android.
I will ask our Xamarin key account.

**Comment by daniel-luberda** [comment]
We should test it out.

**Comment by molinch** [comment]
I would rather have Xamarin answer on this topic than just committing .NET stuff.
This kind of change can improve performance but create more OOMs.

**Comment by daniel-luberda** [comment]
We could easily revert it. I'm doing some tests now to see if it changes anything. Please, let me know if you get any response from Xamarin.

**Comment by daniel-luberda** [comment]
BTW: 
> SGen considers any objects using more than than 8,000 bytes to be large objects (SGEN_MAX_SMALL_OBJ_SIZE )

**Comment by daniel-luberda** [comment]
Reverted it.

**Comment by molinch** [comment]
@daniel-luberda @david-pershouse Xamarin confirmed me that the large object heap threshold is 8K.
Hence I don't think we should change anything
